// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppEntitlementView - The app entitlement view contains the serialized app entitlement and paths to objects referenced by the app entitlement.
type AppEntitlementView struct {
	// The app entitlement represents one permission in a downstream App (SAAS) that can be granted. For example, GitHub Read vs GitHub Write.
	//
	// This message contains a oneof named max_grant_duration. Only a single field of the following list may be set at a time:
	//   - durationUnset
	//   - durationGrant
	//
	AppEntitlement *AppEntitlement `json:"appEntitlement,omitempty"`
	// JSONPATH expression indicating the location of the App object in the  array.
	AppPath *string `json:"appPath,omitempty"`
	// JSONPATH expression indicating the location of the App Resource Type object in the expanded array.
	AppResourcePath *string `json:"appResourcePath,omitempty"`
	// JSONPATH expression indicating the location of the App Resource object in the  array.
	AppResourceTypePath *string `json:"appResourceTypePath,omitempty"`
}
