// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// AppEntitlementUserView - The AppEntitlementUserView (aka grant view) describes the relationship between an app user and an entitlement. They have more recently been referred to as grants.
type AppEntitlementUserView struct {
	AppEntitlementUserBindingCreatedAt     *time.Time `json:"appEntitlementUserBindingCreatedAt,omitempty"`
	AppEntitlementUserBindingDeprovisionAt *time.Time `json:"appEntitlementUserBindingDeprovisionAt,omitempty"`
	// The AppUserView contains an app user as well as paths for apps, identity users, and last usage in expanded arrays.
	AppUser *AppUserView `json:"appUser,omitempty"`
}
