// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppEntitlementSearchServiceSearchRequest - Search app entitlements by a variety of filters.
type AppEntitlementSearchServiceSearchRequest struct {
	// Search for app entitlements that are being reviewed as part of this access review campaign.
	AccessReviewID *string `json:"accessReviewId,omitempty"`
	// Search for app entitlements that have this alias (exact match).
	Alias *string `json:"alias,omitempty"`
	// Search for app entitlements contained in any of these apps.
	AppIds []string `json:"appIds,omitempty"`
	// Search for app entitlements that are granted to any of these app user ids.
	AppUserIds []string `json:"appUserIds,omitempty"`
	// Search for app entitlements that are part of these compliace frameworks.
	ComplianceFrameworkIds []string `json:"complianceFrameworkIds,omitempty"`
	// Exclude app entitlements from the results that are in these app IDs.
	ExcludeAppIds []string `json:"excludeAppIds,omitempty"`
	// Exclude app entitlements from the results that these app users have granted.
	ExcludeAppUserIds []string `json:"excludeAppUserIds,omitempty"`
	// The app entitlement expand mask allows the user to get additional information when getting responses containing app entitlement views.
	ExpandMask *AppEntitlementExpandMask `json:"expandMask,omitempty"`
	// Restrict results to only those who have expiring app entitlement user bindings.
	OnlyGetExpiring *bool `json:"onlyGetExpiring,omitempty"`
	// The pageSize where 0 <= pageSize <= 100. Values < 10 will be set to 10. A value of 0 returns the default page size (currently 25)
	PageSize *float64 `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// Query the app entitlements with a fuzzy search on display name and description.
	Query *string `json:"query,omitempty"`
	// Search for app entitlements that are for items on these resource types.
	ResourceTypeIds []string `json:"resourceTypeIds,omitempty"`
	// Search for app entitlements with these risk levels.
	RiskLevelIds []string `json:"riskLevelIds,omitempty"`
}
