// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppResourceTypeServiceGetResponse - The AppResourceTypeServiceGetResponse contains an expanded array containing the expanded values indicated by the expand mask
//
//	in the request and an app resource type view containing the resource type and JSONPATHs indicating which objects are where in the expand mask.
type AppResourceTypeServiceGetResponse struct {
	// The AppResourceTypeView message.
	AppResourceTypeView *AppResourceTypeView `json:"appResourceTypeView,omitempty"`
	// List of serialized related objects.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
}
