// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppUserServiceUpdateRequestInput - The AppUserServiceUpdateRequest message contains the app user and the fields to be updated.
type AppUserServiceUpdateRequestInput struct {
	// Application User that represents an account in the application.
	AppUser *AppUserInput `json:"appUser,omitempty"`
	// The AppUserExpandMask message contains a list of paths to expand in the response.
	ExpandMask *AppUserExpandMask `json:"expandMask,omitempty"`
	UpdateMask *string            `json:"updateMask,omitempty"`
}
