// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConnectorServiceGetCredentialsResponse - ConnectorServiceGetCredentialsResponse is the response returned by the get method.
type ConnectorServiceGetCredentialsResponse struct {
	// ConnectorCredential is used by a connector to authenticate with conductor one.
	Credential *ConnectorCredential `json:"credential,omitempty"`
}
