// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConnectorServiceUpdateRequestInput - The ConnectorServiceUpdateRequest message contains the fields required to update a connector.
type ConnectorServiceUpdateRequestInput struct {
	// A Connector is used to sync objects into Apps
	Connector *ConnectorInput `json:"connector,omitempty"`
	// The ConnectorExpandMask is used to expand related objects on a connector.
	ExpandMask *ConnectorExpandMask `json:"expandMask,omitempty"`
	UpdateMask *string              `json:"updateMask,omitempty"`
}
