// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateAppRequest - The CreateAppRequest message is used to create a new app.
type CreateAppRequest struct {
	// Creates the app with this certify policy.
	CertifyPolicyID *string `json:"certifyPolicyId,omitempty"`
	// Creates the app with this description.
	Description *string `json:"description,omitempty"`
	// Creates the app with this display name.
	DisplayName *string `json:"displayName,omitempty"`
	// Creates the app with this grant policy.
	GrantPolicyID *string `json:"grantPolicyId,omitempty"`
	// Creates the app with this monthly cost per seat.
	MonthlyCostUsd *float64 `json:"monthlyCostUsd,omitempty"`
	// Creates the app with this array of owners.
	Owners []string `json:"owners,omitempty"`
	// Creates the app with this revoke policy.
	RevokePolicyID *string `json:"revokePolicyId,omitempty"`
}
