// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Facets - Indicates one value of a facet.
type Facets struct {
	// The count of items in this facet.
	Count *string `json:"count,omitempty"`
	// The facet being referenced.
	Facets []FacetCategory `json:"facets,omitempty"`
}
