// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PersonalClientServiceCreateResponse - The PersonalClientServiceCreateResponse message contains the created personal client and client secret.
type PersonalClientServiceCreateResponse struct {
	// The PersonalClient message contains information about a presonal client credential.
	Client *PersonalClient `json:"client,omitempty"`
	// The client secret that corresponds to the personal client. Make sure to save this, because it cannot be returned or queried again.
	ClientSecret *string `json:"clientSecret,omitempty"`
}
