// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PolicyRef - The PolicyRef message.
type PolicyRef struct {
	// The id field.
	ID *string `json:"id,omitempty"`
}
