// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RequestCatalogManagementServiceUpdateRequestInput - Update a request catalog object by ID.
type RequestCatalogManagementServiceUpdateRequestInput struct {
	// The RequestCatalog is used for managing which entitlements are requestable, and who can request them.
	Catalog *RequestCatalogInput `json:"catalog,omitempty"`
	// The RequestCatalogExpandMask includes the paths in the catalog view to expand in the return value of this call.
	ExpandMask *RequestCatalogExpandMask `json:"expandMask,omitempty"`
	UpdateMask *string                   `json:"updateMask,omitempty"`
}
