// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TaskActionsServiceEscalateToEmergencyAccessRequest - The TaskActionsServiceEscalateToEmergencyAccessRequest message.
type TaskActionsServiceEscalateToEmergencyAccessRequest struct {
	// The comment field.
	Comment *string `json:"comment,omitempty"`
	// The task expand mask is an array of strings that specifes the related objects the requester wishes to have returned when making a request where the expand mask is part of the input. Use '*' to view all possible responses.
	ExpandMask *TaskExpandMask `json:"expandMask,omitempty"`
	// The policyStepId field.
	PolicyStepID *string `json:"policyStepId,omitempty"`
}
