// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TaskTypeInput - Task Type provides configuration for the type of task: certify, grant, or revoke
//
// This message contains a oneof named task_type. Only a single field of the following list may be set at a time:
//   - grant
//   - revoke
//   - certify
type TaskTypeInput struct {
	// The TaskTypeCertify message indicates that a task is a certify task and all related details.
	Certify *TaskTypeCertify `json:"certify,omitempty"`
	// The TaskTypeGrant message indicates that a task is a grant task and all related details.
	Grant *TaskTypeGrantInput `json:"grant,omitempty"`
	// The TaskTypeRevoke message indicates that a task is a revoke task and all related details.
	Revoke *TaskTypeRevokeInput `json:"revoke,omitempty"`
}

// TaskType - Task Type provides configuration for the type of task: certify, grant, or revoke
//
// This message contains a oneof named task_type. Only a single field of the following list may be set at a time:
//   - grant
//   - revoke
//   - certify
type TaskType struct {
	// The TaskTypeCertify message indicates that a task is a certify task and all related details.
	Certify *TaskTypeCertify1 `json:"certify,omitempty"`
	// The TaskTypeGrant message indicates that a task is a grant task and all related details.
	Grant *TaskTypeGrant `json:"grant,omitempty"`
	// The TaskTypeRevoke message indicates that a task is a revoke task and all related details.
	Revoke *TaskTypeRevoke `json:"revoke,omitempty"`
}
