// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateAppEntitlementRequestInput - The UpdateAppEntitlementRequest message contains the app entitlement and the fields to be updated.
type UpdateAppEntitlementRequestInput struct {
	// The app entitlement represents one permission in a downstream App (SAAS) that can be granted. For example, GitHub Read vs GitHub Write.
	//
	// This message contains a oneof named max_grant_duration. Only a single field of the following list may be set at a time:
	//   - durationUnset
	//   - durationGrant
	//
	Entitlement *AppEntitlementInput `json:"entitlement,omitempty"`
	// The app entitlement expand mask allows the user to get additional information when getting responses containing app entitlement views.
	ExpandMask *AppEntitlementExpandMask `json:"expandMask,omitempty"`
	UpdateMask *string                   `json:"updateMask,omitempty"`
}
