// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRolesResponse - UpdateRolesResponse is the response message containing the updated role.
type UpdateRolesResponse struct {
	// Role is a role that can be assigned to a user in ConductorOne.
	Role *Role `json:"role,omitempty"`
}
