// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserServiceGetResponse - The UserServiceGetResponse returns a user view which has a user including JSONPATHs to the expanded items in the expanded array.
type UserServiceGetResponse struct {
	// List of serialized related objects.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
	// The UserView object provides a user response object, as well as JSONPATHs to related objects provided by expanders.
	UserView *UserView `json:"userView,omitempty"`
}
