// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1ConnectorServiceRotateCredentialRequest struct {
	ConnectorServiceRotateCredentialRequest *shared.ConnectorServiceRotateCredentialRequest `request:"mediaType=application/json"`
	AppID                                   string                                          `pathParam:"style=simple,explode=false,name=app_id"`
	ConnectorID                             string                                          `pathParam:"style=simple,explode=false,name=connector_id"`
}

type C1APIAppV1ConnectorServiceRotateCredentialResponse struct {
	// ConnectorServiceRotateCredentialResponse is the response returned by the rotate method.
	ConnectorServiceRotateCredentialResponse *shared.ConnectorServiceRotateCredentialResponse
	ContentType                              string
	StatusCode                               int
	RawResponse                              *http.Response
}
