// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppResourceOwnersListRequest struct {
	AppID          string   `pathParam:"style=simple,explode=false,name=app_id"`
	PageSize       *float64 `queryParam:"style=form,explode=true,name=page_size"`
	PageToken      *string  `queryParam:"style=form,explode=true,name=page_token"`
	ResourceID     string   `pathParam:"style=simple,explode=false,name=resource_id"`
	ResourceTypeID string   `pathParam:"style=simple,explode=false,name=resource_type_id"`
}

type C1APIAppV1AppResourceOwnersListResponse struct {
	ContentType string
	// The ListAppResourceOwnersResponse message contains a list of results and a nextPageToken if applicable
	ListAppResourceOwnersResponse *shared.ListAppResourceOwnersResponse
	StatusCode                    int
	RawResponse                   *http.Response
}
