// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIUserV1UserServiceGetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIUserV1UserServiceGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The UserServiceGetResponse returns a user view which has a user including JSONPATHs to the expanded items in the expanded array.
	UserServiceGetResponse *shared.UserServiceGetResponse
}
