// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppResourceSearchSearchAppResourceTypesResponse struct {
	ContentType string
	// The SearchAppResourceTypesResponse message contains a list of results and a nextPageToken if applicable.
	SearchAppResourceTypesResponse *shared.SearchAppResourceTypesResponse
	StatusCode                     int
	RawResponse                    *http.Response
}
