// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppUserServiceUpdateRequest struct {
	AppUserServiceUpdateRequestInput *shared.AppUserServiceUpdateRequestInput `request:"mediaType=application/json"`
	AppUserAppID                     string                                   `pathParam:"style=simple,explode=false,name=app_user_app_id"`
	AppUserID                        string                                   `pathParam:"style=simple,explode=false,name=app_user_id"`
}

type C1APIAppV1AppUserServiceUpdateResponse struct {
	// Successful response
	AppUserServiceUpdateResponse *shared.AppUserServiceUpdateResponse
	ContentType                  string
	StatusCode                   int
	RawResponse                  *http.Response
}
