// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIRequestcatalogV1RequestCatalogManagementServiceGetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIRequestcatalogV1RequestCatalogManagementServiceGetResponse struct {
	ContentType string
	// The request catalog management service get response returns a request catalog view with the expanded items in the expanded array indicated by the expand mask in the request.
	RequestCatalogManagementServiceGetResponse *shared.RequestCatalogManagementServiceGetResponse
	StatusCode                                 int
	RawResponse                                *http.Response
}
