// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIDirectoryV1DirectoryServiceGetRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
}

type C1APIDirectoryV1DirectoryServiceGetResponse struct {
	ContentType string
	// The Directory Service Get Response returns a directory view with a directory and JSONPATHs indicating the
	//  location in the expanded array that items are expanded as indicated by the expand mask in the request.
	DirectoryServiceGetResponse *shared.DirectoryServiceGetResponse
	StatusCode                  int
	RawResponse                 *http.Response
}
