// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1ConnectorServiceGetCredentialsRequest struct {
	AppID       string `pathParam:"style=simple,explode=false,name=app_id"`
	ConnectorID string `pathParam:"style=simple,explode=false,name=connector_id"`
	ID          string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1ConnectorServiceGetCredentialsResponse struct {
	// ConnectorServiceGetCredentialsResponse is the response returned by the get method.
	ConnectorServiceGetCredentialsResponse *shared.ConnectorServiceGetCredentialsResponse
	ContentType                            string
	StatusCode                             int
	RawResponse                            *http.Response
}
