// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAuthV1AuthIntrospectResponse struct {
	ContentType string
	// IntrospectResponse contains information about the current user who is authenticated.
	IntrospectResponse *shared.IntrospectResponse
	StatusCode         int
	RawResponse        *http.Response
}
