// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppResourceTypeServiceGetRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	ID    string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1AppResourceTypeServiceGetResponse struct {
	// The AppResourceTypeServiceGetResponse contains an expanded array containing the expanded values indicated by the expand mask
	//  in the request and an app resource type view containing the resource type and JSONPATHs indicating which objects are where in the expand mask.
	AppResourceTypeServiceGetResponse *shared.AppResourceTypeServiceGetResponse
	ContentType                       string
	StatusCode                        int
	RawResponse                       *http.Response
}
