// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAttributeV1AttributeSearchSearchAttributeValuesResponse struct {
	ContentType string
	// SearchAttributeValuesResponse is the response for searching AttributeValues.
	SearchAttributeValuesResponse *shared.SearchAttributeValuesResponse
	StatusCode                    int
	RawResponse                   *http.Response
}
