// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppsUpdateRequest struct {
	UpdateAppRequestInput *shared.UpdateAppRequestInput `request:"mediaType=application/json"`
	ID                    string                        `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1AppsUpdateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the updated app's new values.
	UpdateAppResponse *shared.UpdateAppResponse
}
