// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppEntitlementsListForAppResourceRequest struct {
	AppID             string   `pathParam:"style=simple,explode=false,name=app_id"`
	AppResourceID     string   `pathParam:"style=simple,explode=false,name=app_resource_id"`
	AppResourceTypeID string   `pathParam:"style=simple,explode=false,name=app_resource_type_id"`
	PageSize          *float64 `queryParam:"style=form,explode=true,name=page_size"`
	PageToken         *string  `queryParam:"style=form,explode=true,name=page_token"`
}

type C1APIAppV1AppEntitlementsListForAppResourceResponse struct {
	ContentType string
	// The ListAppEntitlementsResponse message contains a list of results and a nextPageToken if applicable.
	ListAppEntitlementsResponse *shared.ListAppEntitlementsResponse
	StatusCode                  int
	RawResponse                 *http.Response
}
