// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest struct {
	RequestCatalogManagementServiceRemoveAppEntitlementsRequest *shared.RequestCatalogManagementServiceRemoveAppEntitlementsRequest `request:"mediaType=application/json"`
	CatalogID                                                   string                                                              `pathParam:"style=simple,explode=false,name=catalog_id"`
}

type C1APIRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse struct {
	ContentType string
	// Empty response with a status code indicating success
	RequestCatalogManagementServiceRemoveAppEntitlementsResponse *shared.RequestCatalogManagementServiceRemoveAppEntitlementsResponse
	StatusCode                                                   int
	RawResponse                                                  *http.Response
}
