// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APITaskV1TaskServiceCreateRevokeTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The TaskServiceCreateRevokeResponse returns a task view which has a task including JSONPATHs to the expanded items in the expanded array.
	TaskServiceCreateRevokeResponse *shared.TaskServiceCreateRevokeResponse
}
