// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppEntitlementOwnersRemoveRequest struct {
	RemoveAppEntitlementOwnerRequest *shared.RemoveAppEntitlementOwnerRequest `request:"mediaType=application/json"`
	AppID                            string                                   `pathParam:"style=simple,explode=false,name=app_id"`
	EntitlementID                    string                                   `pathParam:"style=simple,explode=false,name=entitlement_id"`
	UserID                           string                                   `pathParam:"style=simple,explode=false,name=user_id"`
}

type C1APIAppV1AppEntitlementOwnersRemoveResponse struct {
	ContentType string
	// The empty response message for removing an app entitlement owner.
	RemoveAppEntitlementOwnerResponse *shared.RemoveAppEntitlementOwnerResponse
	StatusCode                        int
	RawResponse                       *http.Response
}
