// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APITaskV1TaskActionsServiceCommentRequest struct {
	TaskActionsServiceCommentRequest *shared.TaskActionsServiceCommentRequest `request:"mediaType=application/json"`
	TaskID                           string                                   `pathParam:"style=simple,explode=false,name=task_id"`
}

type C1APITaskV1TaskActionsServiceCommentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Task actions service comment response returns the task view inluding the expanded array of items that are indicated by the expand mask on the request.
	TaskActionsServiceCommentResponse *shared.TaskActionsServiceCommentResponse
}
