// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceUpdateRequest struct {
	EdgeServiceUpdateRequest *shared.EdgeServiceUpdateRequest `request:"mediaType=application/json"`
	AppID                    string                           `pathParam:"style=simple,explode=false,name=app_id"`
	ID                       string                           `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIEdgeV1EdgeServiceUpdateRequest) GetEdgeServiceUpdateRequest() *shared.EdgeServiceUpdateRequest {
	if c == nil {
		return nil
	}
	return c.EdgeServiceUpdateRequest
}

func (c *C1APIEdgeV1EdgeServiceUpdateRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceUpdateRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiedgev1edgeserviceupdaterequest
// #endregion class-body-c1apiedgev1edgeserviceupdaterequest

type C1APIEdgeV1EdgeServiceUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServiceUpdateResponse returns the updated Edge.
	EdgeServiceUpdateResponse *shared.EdgeServiceUpdateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceUpdateResponse) GetEdgeServiceUpdateResponse() *shared.EdgeServiceUpdateResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceUpdateResponse
}

func (c *C1APIEdgeV1EdgeServiceUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeserviceupdateresponse
// #endregion class-body-c1apiedgev1edgeserviceupdateresponse
