// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIArtifactV1ArtifactServiceSearchResponse struct {
	// ArtifactServiceSearchResponse contains only currently authorized metadata.
	//  Readers see published Artifacts; Owners may also see their unpublished entries.
	//  No raw candidate totals, denied/scanned counts or global facets are exposed.
	ArtifactServiceSearchResponse *shared.ArtifactServiceSearchResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIArtifactV1ArtifactServiceSearchResponse) GetArtifactServiceSearchResponse() *shared.ArtifactServiceSearchResponse {
	if c == nil {
		return nil
	}
	return c.ArtifactServiceSearchResponse
}

func (c *C1APIArtifactV1ArtifactServiceSearchResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIArtifactV1ArtifactServiceSearchResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIArtifactV1ArtifactServiceSearchResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiartifactv1artifactservicesearchresponse
// #endregion class-body-c1apiartifactv1artifactservicesearchresponse
