// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1VirtualMCPServerServiceDeleteRequest struct {
	VirtualMCPServerServiceDeleteRequest *shared.VirtualMCPServerServiceDeleteRequest `request:"mediaType=application/json"`
	ID                                   string                                       `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteRequest) GetVirtualMCPServerServiceDeleteRequest() *shared.VirtualMCPServerServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.VirtualMCPServerServiceDeleteRequest
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiaigovernancev1virtualmcpserverservicedeleterequest
// #endregion class-body-c1apiaigovernancev1virtualmcpserverservicedeleterequest

type C1APIAiGovernanceV1VirtualMCPServerServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// VirtualMCPServerServiceDeleteResponse confirms deletion.
	VirtualMCPServerServiceDeleteResponse *shared.VirtualMCPServerServiceDeleteResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPServerServiceDeleteResponse) GetVirtualMCPServerServiceDeleteResponse() *shared.VirtualMCPServerServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.VirtualMCPServerServiceDeleteResponse
}

// #region class-body-c1apiaigovernancev1virtualmcpserverservicedeleteresponse
// #endregion class-body-c1apiaigovernancev1virtualmcpserverservicedeleteresponse
