// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ClassifierServiceListClassifiersRequest struct {
	PageSize  *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

// #region class-body-c1apiaigovernancev1classifierservicelistclassifiersrequest
// #endregion class-body-c1apiaigovernancev1classifierservicelistclassifiersrequest

type C1APIAiGovernanceV1ClassifierServiceListClassifiersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ListClassifiersResponse *shared.ListClassifiersResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersResponse) GetListClassifiersResponse() *shared.ListClassifiersResponse {
	if c == nil {
		return nil
	}
	return c.ListClassifiersResponse
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifiersResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaigovernancev1classifierservicelistclassifiersresponse
// #endregion class-body-c1apiaigovernancev1classifierservicelistclassifiersresponse
