// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket - The bucket field.
type C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket string

const (
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucketTbTimeBucketUnspecified C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket = "TB_TIME_BUCKET_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucketTbTimeBucketHour        C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket = "TB_TIME_BUCKET_HOUR"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucketTbTimeBucketDay         C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket = "TB_TIME_BUCKET_DAY"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TIME_BUCKET_UNSPECIFIED", "TB_TIME_BUCKET_HOUR", "TB_TIME_BUCKET_DAY":
			return true
		}
	}
	return false
}

// C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension - The dimension field.
type C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension string

const (
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimensionTbUsageAttributionDimensionUnspecified C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimensionTbUsageAttributionDimensionTeam        C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimensionTbUsageAttributionDimensionApplication C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimensionTbUsageAttributionDimensionAgent       C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimensionTbUsageAttributionDimensionCostCenter  C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	// The bucket field.
	Bucket *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket `queryParam:"style=form,explode=true,name=bucket"`
	// The dimension field.
	Dimension *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension `queryParam:"style=form,explode=true,name=dimension"`
	ID        string                                                           `pathParam:"style=simple,explode=false,name=id"`
	PageSize  *int                                                             `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string                                                          `queryParam:"style=form,explode=true,name=page_token"`
	Since     *int64                                                           `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64                                                           `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetBucket() *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamBucket {
	if c == nil {
		return nil
	}
	return c.Bucket
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetDimension() *C1APIEdgeV1EdgeServiceListInferenceTopAgentsQueryParamDimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistinferencetopagentsrequest
// #endregion class-body-c1apiedgev1edgeservicelistinferencetopagentsrequest

type C1APIEdgeV1EdgeServiceListInferenceTopAgentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListInferenceTopAgentsResponse *shared.EdgeServiceListInferenceTopAgentsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsResponse) GetEdgeServiceListInferenceTopAgentsResponse() *shared.EdgeServiceListInferenceTopAgentsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListInferenceTopAgentsResponse
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopAgentsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistinferencetopagentsresponse
// #endregion class-body-c1apiedgev1edgeservicelistinferencetopagentsresponse
