// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIUserV1UserAttributeManagementServiceDeleteRequest struct {
	UserAttributeManagementServiceDeleteRequest *shared.UserAttributeManagementServiceDeleteRequest `request:"mediaType=application/json"`
	ID                                          string                                              `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteRequest) GetUserAttributeManagementServiceDeleteRequest() *shared.UserAttributeManagementServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.UserAttributeManagementServiceDeleteRequest
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiuserv1userattributemanagementservicedeleterequest
// #endregion class-body-c1apiuserv1userattributemanagementservicedeleterequest

type C1APIUserV1UserAttributeManagementServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	UserAttributeManagementServiceDeleteResponse *shared.UserAttributeManagementServiceDeleteResponse
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIUserV1UserAttributeManagementServiceDeleteResponse) GetUserAttributeManagementServiceDeleteResponse() *shared.UserAttributeManagementServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.UserAttributeManagementServiceDeleteResponse
}

// #region class-body-c1apiuserv1userattributemanagementservicedeleteresponse
// #endregion class-body-c1apiuserv1userattributemanagementservicedeleteresponse
