// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// Dimension - The dimension field.
type Dimension string

const (
	DimensionTbUsageAttributionDimensionUnspecified Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	DimensionTbUsageAttributionDimensionTeam        Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	DimensionTbUsageAttributionDimensionApplication Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	DimensionTbUsageAttributionDimensionAgent       Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	DimensionTbUsageAttributionDimensionCostCenter  Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e Dimension) ToPointer() *Dimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Dimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest struct {
	// The dimension field.
	Dimension *Dimension `queryParam:"style=form,explode=true,name=dimension"`
	PageSize  *int       `queryParam:"style=form,explode=true,name=page_size"`
	Since     *int64     `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64     `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) GetDimension() *Dimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apitbcontrolplanev1tbcontrolplaneservicegetusageattributionrequest
// #endregion class-body-c1apitbcontrolplanev1tbcontrolplaneservicegetusageattributionrequest

type C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	TBControlPlaneServiceGetUsageAttributionResponse *shared.TBControlPlaneServiceGetUsageAttributionResponse
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceGetUsageAttributionResponse) GetTBControlPlaneServiceGetUsageAttributionResponse() *shared.TBControlPlaneServiceGetUsageAttributionResponse {
	if c == nil {
		return nil
	}
	return c.TBControlPlaneServiceGetUsageAttributionResponse
}

// #region class-body-c1apitbcontrolplanev1tbcontrolplaneservicegetusageattributionresponse
// #endregion class-body-c1apitbcontrolplanev1tbcontrolplaneservicegetusageattributionresponse
