// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest struct {
	AppID                       string `pathParam:"style=simple,explode=false,name=app_id"`
	EventID                     string `pathParam:"style=simple,explode=false,name=event_id"`
	EventTime                   *int64 `integer:"string" queryParam:"style=form,explode=true,name=event_time"`
	ID                          string `pathParam:"style=simple,explode=false,name=id"`
	IncludeParsedVerdictReasons *bool  `queryParam:"style=form,explode=true,name=include_parsed_verdict_reasons"`
}

func (c C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetEventID() string {
	if c == nil {
		return ""
	}
	return c.EventID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetEventTime() *int64 {
	if c == nil {
		return nil
	}
	return c.EventTime
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetIncludeParsedVerdictReasons() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeParsedVerdictReasons
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficeventrequest
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficeventrequest

type C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceGetEgressTrafficEventResponse *shared.EdgeServiceGetEgressTrafficEventResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetEdgeServiceGetEgressTrafficEventResponse() *shared.EdgeServiceGetEgressTrafficEventResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceGetEgressTrafficEventResponse
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficeventresponse
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficeventresponse
