// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension - The dimension field.
type C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension string

const (
	C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimensionTbUsageAttributionDimensionUnspecified C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimensionTbUsageAttributionDimensionTeam        C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimensionTbUsageAttributionDimensionApplication C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimensionTbUsageAttributionDimensionAgent       C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimensionTbUsageAttributionDimensionCostCenter  C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension) ToPointer() *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest struct {
	// The dimension field.
	Dimension *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension `queryParam:"style=form,explode=true,name=dimension"`
	PageSize  *int                                                                         `queryParam:"style=form,explode=true,name=page_size"`
	Since     *int64                                                                       `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64                                                                       `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) GetDimension() *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupQueryParamDimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicegetinferenceusageattributionrolluprequest
// #endregion class-body-c1apiedgev1edgeservicegetinferenceusageattributionrolluprequest

type C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceGetInferenceUsageAttributionRollupResponse *shared.EdgeServiceGetInferenceUsageAttributionRollupResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupResponse) GetEdgeServiceGetInferenceUsageAttributionRollupResponse() *shared.EdgeServiceGetInferenceUsageAttributionRollupResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceGetInferenceUsageAttributionRollupResponse
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceGetInferenceUsageAttributionRollupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicegetinferenceusageattributionrollupresponse
// #endregion class-body-c1apiedgev1edgeservicegetinferenceusageattributionrollupresponse
