// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest struct {
	PageSize *int   `queryParam:"style=form,explode=true,name=page_size"`
	Since    *int64 `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until    *int64 `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistegresstopagentsrolluprequest
// #endregion class-body-c1apiedgev1edgeservicelistegresstopagentsrolluprequest

type C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListEgressTopAgentsRollupResponse *shared.EdgeServiceListEgressTopAgentsRollupResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupResponse) GetEdgeServiceListEgressTopAgentsRollupResponse() *shared.EdgeServiceListEgressTopAgentsRollupResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListEgressTopAgentsRollupResponse
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRollupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistegresstopagentsrollupresponse
// #endregion class-body-c1apiedgev1edgeservicelistegresstopagentsrollupresponse
