// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIIamV1ModelAPIKeyServiceRevokeRequest struct {
	ModelAPIKeyServiceRevokeRequest *shared.ModelAPIKeyServiceRevokeRequest `request:"mediaType=application/json"`
	ID                              string                                  `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeRequest) GetModelAPIKeyServiceRevokeRequest() *shared.ModelAPIKeyServiceRevokeRequest {
	if c == nil {
		return nil
	}
	return c.ModelAPIKeyServiceRevokeRequest
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiiamv1modelapikeyservicerevokerequest
// #endregion class-body-c1apiiamv1modelapikeyservicerevokerequest

type C1APIIamV1ModelAPIKeyServiceRevokeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ModelAPIKeyServiceRevokeResponse *shared.ModelAPIKeyServiceRevokeResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeResponse) GetModelAPIKeyServiceRevokeResponse() *shared.ModelAPIKeyServiceRevokeResponse {
	if c == nil {
		return nil
	}
	return c.ModelAPIKeyServiceRevokeResponse
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIIamV1ModelAPIKeyServiceRevokeResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiiamv1modelapikeyservicerevokeresponse
// #endregion class-body-c1apiiamv1modelapikeyservicerevokeresponse
