// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket - The bucket field.
type C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket string

const (
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucketTbTimeBucketUnspecified C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket = "TB_TIME_BUCKET_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucketTbTimeBucketHour        C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket = "TB_TIME_BUCKET_HOUR"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucketTbTimeBucketDay         C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket = "TB_TIME_BUCKET_DAY"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TIME_BUCKET_UNSPECIFIED", "TB_TIME_BUCKET_HOUR", "TB_TIME_BUCKET_DAY":
			return true
		}
	}
	return false
}

// C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension - The dimension field.
type C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension string

const (
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimensionTbUsageAttributionDimensionUnspecified C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimensionTbUsageAttributionDimensionTeam        C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimensionTbUsageAttributionDimensionApplication C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimensionTbUsageAttributionDimensionAgent       C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimensionTbUsageAttributionDimensionCostCenter  C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	// The bucket field.
	Bucket *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket `queryParam:"style=form,explode=true,name=bucket"`
	// The dimension field.
	Dimension *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension `queryParam:"style=form,explode=true,name=dimension"`
	ID        string                                                               `pathParam:"style=simple,explode=false,name=id"`
	PageSize  *int                                                                 `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string                                                              `queryParam:"style=form,explode=true,name=page_token"`
	Since     *int64                                                               `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64                                                               `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetBucket() *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamBucket {
	if c == nil {
		return nil
	}
	return c.Bucket
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetDimension() *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsQueryParamDimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistinferencetrafficeventsrequest
// #endregion class-body-c1apiedgev1edgeservicelistinferencetrafficeventsrequest

type C1APIEdgeV1EdgeServiceListInferenceTrafficEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListInferenceTrafficEventsResponse *shared.EdgeServiceListInferenceTrafficEventsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsResponse) GetEdgeServiceListInferenceTrafficEventsResponse() *shared.EdgeServiceListInferenceTrafficEventsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListInferenceTrafficEventsResponse
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTrafficEventsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistinferencetrafficeventsresponse
// #endregion class-body-c1apiedgev1edgeservicelistinferencetrafficeventsresponse
