// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ClassifierTemplateServiceListClassifierTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ListClassifierTemplatesResponse *shared.ListClassifierTemplatesResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceListClassifierTemplatesResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceListClassifierTemplatesResponse) GetListClassifierTemplatesResponse() *shared.ListClassifierTemplatesResponse {
	if c == nil {
		return nil
	}
	return c.ListClassifierTemplatesResponse
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceListClassifierTemplatesResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceListClassifierTemplatesResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaigovernancev1classifiertemplateservicelistclassifiertemplatesresponse
// #endregion class-body-c1apiaigovernancev1classifiertemplateservicelistclassifiertemplatesresponse
