// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitRequest struct {
	MyFundLimitsServiceClearTemporaryLimitRequest *shared.MyFundLimitsServiceClearTemporaryLimitRequest `request:"mediaType=application/json"`
	AppID                                         string                                                `pathParam:"style=simple,explode=false,name=app_id"`
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitRequest) GetMyFundLimitsServiceClearTemporaryLimitRequest() *shared.MyFundLimitsServiceClearTemporaryLimitRequest {
	if c == nil {
		return nil
	}
	return c.MyFundLimitsServiceClearTemporaryLimitRequest
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

// #region class-body-c1apifundsv1myfundlimitsservicecleartemporarylimitrequest
// #endregion class-body-c1apifundsv1myfundlimitsservicecleartemporarylimitrequest

type C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	MyFundLimitsServiceClearTemporaryLimitResponse *shared.MyFundLimitsServiceClearTemporaryLimitResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitResponse) GetMyFundLimitsServiceClearTemporaryLimitResponse() *shared.MyFundLimitsServiceClearTemporaryLimitResponse {
	if c == nil {
		return nil
	}
	return c.MyFundLimitsServiceClearTemporaryLimitResponse
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIFundsV1MyFundLimitsServiceClearTemporaryLimitResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apifundsv1myfundlimitsservicecleartemporarylimitresponse
// #endregion class-body-c1apifundsv1myfundlimitsservicecleartemporarylimitresponse
