// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceDeleteRequest struct {
	EdgeServiceDeleteRequest *shared.EdgeServiceDeleteRequest `request:"mediaType=application/json"`
	AppID                    string                           `pathParam:"style=simple,explode=false,name=app_id"`
	ID                       string                           `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIEdgeV1EdgeServiceDeleteRequest) GetEdgeServiceDeleteRequest() *shared.EdgeServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.EdgeServiceDeleteRequest
}

func (c *C1APIEdgeV1EdgeServiceDeleteRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiedgev1edgeservicedeleterequest
// #endregion class-body-c1apiedgev1edgeservicedeleterequest

type C1APIEdgeV1EdgeServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServiceDeleteResponse confirms deletion. The Edge's entitlement
	//  stack cascade-deletes; a replacement Edge mints an all-new stack.
	EdgeServiceDeleteResponse *shared.EdgeServiceDeleteResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceDeleteResponse) GetEdgeServiceDeleteResponse() *shared.EdgeServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceDeleteResponse
}

func (c *C1APIEdgeV1EdgeServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicedeleteresponse
// #endregion class-body-c1apiedgev1edgeservicedeleteresponse
