// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest struct {
	AuditOriginID         *string `queryParam:"style=form,explode=true,name=audit_origin_id"`
	AuditOriginInstanceID *string `queryParam:"style=form,explode=true,name=audit_origin_instance_id"`
	PageSize              *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken             *string `queryParam:"style=form,explode=true,name=page_token"`
	Since                 *int64  `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until                 *int64  `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetAuditOriginID() *string {
	if c == nil {
		return nil
	}
	return c.AuditOriginID
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetAuditOriginInstanceID() *string {
	if c == nil {
		return nil
	}
	return c.AuditOriginInstanceID
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistauditattestationmanifestsrequest
// #endregion class-body-c1apiedgev1edgeservicelistauditattestationmanifestsrequest

type C1APIEdgeV1EdgeServiceListAuditAttestationManifestsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListAuditAttestationManifestsResponse *shared.EdgeServiceListAuditAttestationManifestsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsResponse) GetEdgeServiceListAuditAttestationManifestsResponse() *shared.EdgeServiceListAuditAttestationManifestsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListAuditAttestationManifestsResponse
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListAuditAttestationManifestsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistauditattestationmanifestsresponse
// #endregion class-body-c1apiedgev1edgeservicelistauditattestationmanifestsresponse
