// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsRequest struct {
	VirtualMCPToolsetBindingServiceDeleteBindingsRequest *shared.VirtualMCPToolsetBindingServiceDeleteBindingsRequest `request:"mediaType=application/json"`
	VirtualMcpServerID                                   string                                                       `pathParam:"style=simple,explode=false,name=virtual_mcp_server_id"`
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsRequest) GetVirtualMCPToolsetBindingServiceDeleteBindingsRequest() *shared.VirtualMCPToolsetBindingServiceDeleteBindingsRequest {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolsetBindingServiceDeleteBindingsRequest
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsRequest) GetVirtualMcpServerID() string {
	if c == nil {
		return ""
	}
	return c.VirtualMcpServerID
}

// #region class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicedeletebindingsrequest
// #endregion class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicedeletebindingsrequest

type C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// VirtualMCPToolsetBindingServiceDeleteBindingsResponse confirms the assignments were deleted.
	VirtualMCPToolsetBindingServiceDeleteBindingsResponse *shared.VirtualMCPToolsetBindingServiceDeleteBindingsResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceDeleteBindingsResponse) GetVirtualMCPToolsetBindingServiceDeleteBindingsResponse() *shared.VirtualMCPToolsetBindingServiceDeleteBindingsResponse {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolsetBindingServiceDeleteBindingsResponse
}

// #region class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicedeletebindingsresponse
// #endregion class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicedeletebindingsresponse
