// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateRequest struct {
	EdgeServicePreviewEgressRulesUpdateRequest *shared.EdgeServicePreviewEgressRulesUpdateRequest `request:"mediaType=application/json"`
	AppID                                      string                                             `pathParam:"style=simple,explode=false,name=app_id"`
	ID                                         string                                             `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateRequest) GetEdgeServicePreviewEgressRulesUpdateRequest() *shared.EdgeServicePreviewEgressRulesUpdateRequest {
	if c == nil {
		return nil
	}
	return c.EdgeServicePreviewEgressRulesUpdateRequest
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiedgev1edgeservicepreviewegressrulesupdaterequest
// #endregion class-body-c1apiedgev1edgeservicepreviewegressrulesupdaterequest

type C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServicePreviewEgressRulesUpdateResponse reports the save check and each
	//  host's verdict before and after the change.
	EdgeServicePreviewEgressRulesUpdateResponse *shared.EdgeServicePreviewEgressRulesUpdateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateResponse) GetEdgeServicePreviewEgressRulesUpdateResponse() *shared.EdgeServicePreviewEgressRulesUpdateResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServicePreviewEgressRulesUpdateResponse
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServicePreviewEgressRulesUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicepreviewegressrulesupdateresponse
// #endregion class-body-c1apiedgev1edgeservicepreviewegressrulesupdateresponse
