// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ClassifierServiceCreateClassifierResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	CreateClassifierResponse *shared.CreateClassifierResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAiGovernanceV1ClassifierServiceCreateClassifierResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ClassifierServiceCreateClassifierResponse) GetCreateClassifierResponse() *shared.CreateClassifierResponse {
	if c == nil {
		return nil
	}
	return c.CreateClassifierResponse
}

func (c *C1APIAiGovernanceV1ClassifierServiceCreateClassifierResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ClassifierServiceCreateClassifierResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaigovernancev1classifierservicecreateclassifierresponse
// #endregion class-body-c1apiaigovernancev1classifierservicecreateclassifierresponse
