// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIGolinkV1GoLinkServiceDeleteRequest struct {
	GoLinkServiceDeleteRequest *shared.GoLinkServiceDeleteRequest `request:"mediaType=application/json"`
	ID                         string                             `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIGolinkV1GoLinkServiceDeleteRequest) GetGoLinkServiceDeleteRequest() *shared.GoLinkServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.GoLinkServiceDeleteRequest
}

func (c *C1APIGolinkV1GoLinkServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apigolinkv1golinkservicedeleterequest
// #endregion class-body-c1apigolinkv1golinkservicedeleterequest

type C1APIGolinkV1GoLinkServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	GoLinkServiceDeleteResponse *shared.GoLinkServiceDeleteResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIGolinkV1GoLinkServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIGolinkV1GoLinkServiceDeleteResponse) GetGoLinkServiceDeleteResponse() *shared.GoLinkServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.GoLinkServiceDeleteResponse
}

func (c *C1APIGolinkV1GoLinkServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIGolinkV1GoLinkServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apigolinkv1golinkservicedeleteresponse
// #endregion class-body-c1apigolinkv1golinkservicedeleteresponse
