// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APISecretsV1PaperSecretAdminServiceDeleteRequest struct {
	PaperSecretAdminServiceDeleteRequest *shared.PaperSecretAdminServiceDeleteRequest `request:"mediaType=application/json"`
	VaultID                              string                                       `pathParam:"style=simple,explode=false,name=vault_id"`
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteRequest) GetPaperSecretAdminServiceDeleteRequest() *shared.PaperSecretAdminServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.PaperSecretAdminServiceDeleteRequest
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteRequest) GetVaultID() string {
	if c == nil {
		return ""
	}
	return c.VaultID
}

// #region class-body-c1apisecretsv1papersecretadminservicedeleterequest
// #endregion class-body-c1apisecretsv1papersecretadminservicedeleterequest

type C1APISecretsV1PaperSecretAdminServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	PaperSecretAdminServiceDeleteResponse *shared.PaperSecretAdminServiceDeleteResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteResponse) GetPaperSecretAdminServiceDeleteResponse() *shared.PaperSecretAdminServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.PaperSecretAdminServiceDeleteResponse
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APISecretsV1PaperSecretAdminServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apisecretsv1papersecretadminservicedeleteresponse
// #endregion class-body-c1apisecretsv1papersecretadminservicedeleteresponse
