// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ToolGatesServiceDeleteRequest struct {
	ToolGatesServiceDeleteRequest *shared.ToolGatesServiceDeleteRequest `request:"mediaType=application/json"`
	ID                            string                                `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteRequest) GetToolGatesServiceDeleteRequest() *shared.ToolGatesServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.ToolGatesServiceDeleteRequest
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiaigovernancev1toolgatesservicedeleterequest
// #endregion class-body-c1apiaigovernancev1toolgatesservicedeleterequest

type C1APIAiGovernanceV1ToolGatesServiceDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ToolGatesServiceDeleteResponse *shared.ToolGatesServiceDeleteResponse
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1ToolGatesServiceDeleteResponse) GetToolGatesServiceDeleteResponse() *shared.ToolGatesServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ToolGatesServiceDeleteResponse
}

// #region class-body-c1apiaigovernancev1toolgatesservicedeleteresponse
// #endregion class-body-c1apiaigovernancev1toolgatesservicedeleteresponse
