// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket - The bucket field.
type C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket string

const (
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucketTbTimeBucketUnspecified C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket = "TB_TIME_BUCKET_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucketTbTimeBucketHour        C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket = "TB_TIME_BUCKET_HOUR"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucketTbTimeBucketDay         C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket = "TB_TIME_BUCKET_DAY"
)

func (e C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket) ToPointer() *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TIME_BUCKET_UNSPECIFIED", "TB_TIME_BUCKET_HOUR", "TB_TIME_BUCKET_DAY":
			return true
		}
	}
	return false
}

// C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension - The dimension field.
type C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension string

const (
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimensionTbUsageAttributionDimensionUnspecified C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimensionTbUsageAttributionDimensionTeam        C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimensionTbUsageAttributionDimensionApplication C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimensionTbUsageAttributionDimensionAgent       C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimensionTbUsageAttributionDimensionCostCenter  C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension) ToPointer() *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	// The bucket field.
	Bucket *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket `queryParam:"style=form,explode=true,name=bucket"`
	// The dimension field.
	Dimension *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension `queryParam:"style=form,explode=true,name=dimension"`
	ID        string                                                        `pathParam:"style=simple,explode=false,name=id"`
	PageSize  *int                                                          `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string                                                       `queryParam:"style=form,explode=true,name=page_token"`
	Since     *int64                                                        `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64                                                        `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetBucket() *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamBucket {
	if c == nil {
		return nil
	}
	return c.Bucket
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetDimension() *C1APIEdgeV1EdgeServiceListEgressTopAgentsQueryParamDimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistegresstopagentsrequest
// #endregion class-body-c1apiedgev1edgeservicelistegresstopagentsrequest

type C1APIEdgeV1EdgeServiceListEgressTopAgentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListEgressTopAgentsResponse *shared.EdgeServiceListEgressTopAgentsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsResponse) GetEdgeServiceListEgressTopAgentsResponse() *shared.EdgeServiceListEgressTopAgentsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListEgressTopAgentsResponse
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopAgentsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistegresstopagentsresponse
// #endregion class-body-c1apiedgev1edgeservicelistegresstopagentsresponse
