// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket - The bucket field.
type C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket string

const (
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucketTbTimeBucketUnspecified C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket = "TB_TIME_BUCKET_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucketTbTimeBucketHour        C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket = "TB_TIME_BUCKET_HOUR"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucketTbTimeBucketDay         C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket = "TB_TIME_BUCKET_DAY"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TIME_BUCKET_UNSPECIFIED", "TB_TIME_BUCKET_HOUR", "TB_TIME_BUCKET_DAY":
			return true
		}
	}
	return false
}

// C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension - The dimension field.
type C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension string

const (
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimensionTbUsageAttributionDimensionUnspecified C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimensionTbUsageAttributionDimensionTeam        C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimensionTbUsageAttributionDimensionApplication C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimensionTbUsageAttributionDimensionAgent       C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimensionTbUsageAttributionDimensionCostCenter  C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension) ToPointer() *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	// The bucket field.
	Bucket *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket `queryParam:"style=form,explode=true,name=bucket"`
	// The dimension field.
	Dimension *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension `queryParam:"style=form,explode=true,name=dimension"`
	ID        string                                                          `pathParam:"style=simple,explode=false,name=id"`
	PageSize  *int                                                            `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string                                                         `queryParam:"style=form,explode=true,name=page_token"`
	Since     *int64                                                          `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64                                                          `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetBucket() *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamBucket {
	if c == nil {
		return nil
	}
	return c.Bucket
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetDimension() *C1APIEdgeV1EdgeServiceListInferenceTopToolsQueryParamDimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistinferencetoptoolsrequest
// #endregion class-body-c1apiedgev1edgeservicelistinferencetoptoolsrequest

type C1APIEdgeV1EdgeServiceListInferenceTopToolsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListInferenceTopToolsResponse *shared.EdgeServiceListInferenceTopToolsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsResponse) GetEdgeServiceListInferenceTopToolsResponse() *shared.EdgeServiceListInferenceTopToolsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListInferenceTopToolsResponse
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListInferenceTopToolsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistinferencetoptoolsresponse
// #endregion class-body-c1apiedgev1edgeservicelistinferencetoptoolsresponse
