// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessRequest struct {
	AppID           string  `pathParam:"style=simple,explode=false,name=app_id"`
	ID              string  `pathParam:"style=simple,explode=false,name=id"`
	VaultBoundaryID *string `queryParam:"style=form,explode=true,name=vault_boundary_id"`
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessRequest) GetVaultBoundaryID() *string {
	if c == nil {
		return nil
	}
	return c.VaultBoundaryID
}

// #region class-body-c1apiedgev1edgeservicecheckinferencevaultaccessrequest
// #endregion class-body-c1apiedgev1edgeservicecheckinferencevaultaccessrequest

type C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServiceCheckInferenceVaultAccessResponse reports the same Vault grant
	//  check Update runs before saving an inference route.
	EdgeServiceCheckInferenceVaultAccessResponse *shared.EdgeServiceCheckInferenceVaultAccessResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessResponse) GetEdgeServiceCheckInferenceVaultAccessResponse() *shared.EdgeServiceCheckInferenceVaultAccessResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceCheckInferenceVaultAccessResponse
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceCheckInferenceVaultAccessResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicecheckinferencevaultaccessresponse
// #endregion class-body-c1apiedgev1edgeservicecheckinferencevaultaccessresponse
