// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceListInferenceCatalogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServiceListInferenceCatalogResponse contains every catalog entry.
	EdgeServiceListInferenceCatalogResponse *shared.EdgeServiceListInferenceCatalogResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListInferenceCatalogResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListInferenceCatalogResponse) GetEdgeServiceListInferenceCatalogResponse() *shared.EdgeServiceListInferenceCatalogResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListInferenceCatalogResponse
}

func (c *C1APIEdgeV1EdgeServiceListInferenceCatalogResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListInferenceCatalogResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistinferencecatalogresponse
// #endregion class-body-c1apiedgev1edgeservicelistinferencecatalogresponse
