// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsRequest struct {
	AccessReviewAddTemplateEntitlementsRequest *shared.AccessReviewAddTemplateEntitlementsRequest `request:"mediaType=application/json"`
	AccessReviewTemplateID                     string                                             `pathParam:"style=simple,explode=false,name=access_review_template_id"`
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsRequest) GetAccessReviewAddTemplateEntitlementsRequest() *shared.AccessReviewAddTemplateEntitlementsRequest {
	if c == nil {
		return nil
	}
	return c.AccessReviewAddTemplateEntitlementsRequest
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsRequest) GetAccessReviewTemplateID() string {
	if c == nil {
		return ""
	}
	return c.AccessReviewTemplateID
}

// #region class-body-c1apiaccessreviewv1accessreviewtemplatesetupentitlementserviceaddtemplateentitlementsrequest
// #endregion class-body-c1apiaccessreviewv1accessreviewtemplatesetupentitlementserviceaddtemplateentitlementsrequest

type C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsResponse struct {
	// Successful response
	AccessReviewAddTemplateEntitlementsResponse *shared.AccessReviewAddTemplateEntitlementsResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsResponse) GetAccessReviewAddTemplateEntitlementsResponse() *shared.AccessReviewAddTemplateEntitlementsResponse {
	if c == nil {
		return nil
	}
	return c.AccessReviewAddTemplateEntitlementsResponse
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAccessreviewV1AccessReviewTemplateSetupEntitlementServiceAddTemplateEntitlementsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaccessreviewv1accessreviewtemplatesetupentitlementserviceaddtemplateentitlementsresponse
// #endregion class-body-c1apiaccessreviewv1accessreviewtemplatesetupentitlementserviceaddtemplateentitlementsresponse
