// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsRequest struct {
	PageSize  *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

// #region class-body-c1apiaigovernancev1classifierservicelistclassifierbindingsrequest
// #endregion class-body-c1apiaigovernancev1classifierservicelistclassifierbindingsrequest

type C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ListClassifierBindingsResponse *shared.ListClassifierBindingsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsResponse) GetListClassifierBindingsResponse() *shared.ListClassifierBindingsResponse {
	if c == nil {
		return nil
	}
	return c.ListClassifierBindingsResponse
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ClassifierServiceListClassifierBindingsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaigovernancev1classifierservicelistclassifierbindingsresponse
// #endregion class-body-c1apiaigovernancev1classifierservicelistclassifierbindingsresponse
