// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"conductorone-api/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppResourceServiceGetRequest struct {
	AppID             string `pathParam:"style=simple,explode=false,name=app_id"`
	AppResourceTypeID string `pathParam:"style=simple,explode=false,name=app_resource_type_id"`
	ID                string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1AppResourceServiceGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APIAppV1AppResourceServiceGetResponse *shared.C1APIAppV1AppResourceServiceGetResponse
}
