// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIIamV1ModelAPIKeyServiceListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ModelAPIKeyServiceListResponse *shared.ModelAPIKeyServiceListResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIIamV1ModelAPIKeyServiceListResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIIamV1ModelAPIKeyServiceListResponse) GetModelAPIKeyServiceListResponse() *shared.ModelAPIKeyServiceListResponse {
	if c == nil {
		return nil
	}
	return c.ModelAPIKeyServiceListResponse
}

func (c *C1APIIamV1ModelAPIKeyServiceListResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIIamV1ModelAPIKeyServiceListResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiiamv1modelapikeyservicelistresponse
// #endregion class-body-c1apiiamv1modelapikeyservicelistresponse
