// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierRequest struct {
	McpIdentifier *string `queryParam:"style=form,explode=true,name=mcp_identifier"`
}

func (c *C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierRequest) GetMcpIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.McpIdentifier
}

// #region class-body-c1apiaigovernancev1mcpserverserviceresolvemcpidentifierrequest
// #endregion class-body-c1apiaigovernancev1mcpserverserviceresolvemcpidentifierrequest

type C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// MCPServerServiceResolveMcpIdentifierResponse is exactly one of three
	//  outcomes. registered_server takes precedence over catalog_entry when both
	//  would match: a tenant that already registered a server for this product
	//  should never also be told to register it again from the catalog.
	MCPServerServiceResolveMCPIdentifierResponse *shared.MCPServerServiceResolveMCPIdentifierResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierResponse) GetMCPServerServiceResolveMCPIdentifierResponse() *shared.MCPServerServiceResolveMCPIdentifierResponse {
	if c == nil {
		return nil
	}
	return c.MCPServerServiceResolveMCPIdentifierResponse
}

func (c *C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1MCPServerServiceResolveMCPIdentifierResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaigovernancev1mcpserverserviceresolvemcpidentifierresponse
// #endregion class-body-c1apiaigovernancev1mcpserverserviceresolvemcpidentifierresponse
