// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIGolinkV1GoLinkServiceCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	GoLinkServiceCreateResponse *shared.GoLinkServiceCreateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIGolinkV1GoLinkServiceCreateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIGolinkV1GoLinkServiceCreateResponse) GetGoLinkServiceCreateResponse() *shared.GoLinkServiceCreateResponse {
	if c == nil {
		return nil
	}
	return c.GoLinkServiceCreateResponse
}

func (c *C1APIGolinkV1GoLinkServiceCreateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIGolinkV1GoLinkServiceCreateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apigolinkv1golinkservicecreateresponse
// #endregion class-body-c1apigolinkv1golinkservicecreateresponse
