// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest struct {
	PageSize *int   `queryParam:"style=form,explode=true,name=page_size"`
	Since    *int64 `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until    *int64 `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistegresstoptoolsrolluprequest
// #endregion class-body-c1apiedgev1edgeservicelistegresstoptoolsrolluprequest

type C1APIEdgeV1EdgeServiceListEgressTopToolsRollupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListEgressTopToolsRollupResponse *shared.EdgeServiceListEgressTopToolsRollupResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupResponse) GetEdgeServiceListEgressTopToolsRollupResponse() *shared.EdgeServiceListEgressTopToolsRollupResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListEgressTopToolsRollupResponse
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopToolsRollupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistegresstoptoolsrollupresponse
// #endregion class-body-c1apiedgev1edgeservicelistegresstoptoolsrollupresponse
