// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsRequest struct {
	AccessReviewAddCampaignEntitlementsRequest *shared.AccessReviewAddCampaignEntitlementsRequest `request:"mediaType=application/json"`
	AccessReviewID                             string                                             `pathParam:"style=simple,explode=false,name=access_review_id"`
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsRequest) GetAccessReviewAddCampaignEntitlementsRequest() *shared.AccessReviewAddCampaignEntitlementsRequest {
	if c == nil {
		return nil
	}
	return c.AccessReviewAddCampaignEntitlementsRequest
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsRequest) GetAccessReviewID() string {
	if c == nil {
		return ""
	}
	return c.AccessReviewID
}

// #region class-body-c1apiaccessreviewv1accessreviewsetupentitlementserviceaddcampaignentitlementsrequest
// #endregion class-body-c1apiaccessreviewv1accessreviewsetupentitlementserviceaddcampaignentitlementsrequest

type C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsResponse struct {
	// Successful response
	AccessReviewAddCampaignEntitlementsResponse *shared.AccessReviewAddCampaignEntitlementsResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsResponse) GetAccessReviewAddCampaignEntitlementsResponse() *shared.AccessReviewAddCampaignEntitlementsResponse {
	if c == nil {
		return nil
	}
	return c.AccessReviewAddCampaignEntitlementsResponse
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAccessreviewV1AccessReviewSetupEntitlementServiceAddCampaignEntitlementsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiaccessreviewv1accessreviewsetupentitlementserviceaddcampaignentitlementsresponse
// #endregion class-body-c1apiaccessreviewv1accessreviewsetupentitlementserviceaddcampaignentitlementsresponse
