// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ConductorOne/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppsGetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1AppsGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APIAppV1GetAppResponse *shared.C1APIAppV1GetAppResponse
}
