// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APITaskV1TaskServiceGetSpendRemedyStatusRequest struct {
	AppID  *string `queryParam:"style=form,explode=true,name=app_id"`
	TaskID string  `pathParam:"style=simple,explode=false,name=task_id"`
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusRequest) GetTaskID() string {
	if c == nil {
		return ""
	}
	return c.TaskID
}

// #region class-body-c1apitaskv1taskservicegetspendremedystatusrequest
// #endregion class-body-c1apitaskv1taskservicegetspendremedystatusrequest

type C1APITaskV1TaskServiceGetSpendRemedyStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	TaskServiceGetSpendRemedyStatusResponse *shared.TaskServiceGetSpendRemedyStatusResponse
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APITaskV1TaskServiceGetSpendRemedyStatusResponse) GetTaskServiceGetSpendRemedyStatusResponse() *shared.TaskServiceGetSpendRemedyStatusResponse {
	if c == nil {
		return nil
	}
	return c.TaskServiceGetSpendRemedyStatusResponse
}

// #region class-body-c1apitaskv1taskservicegetspendremedystatusresponse
// #endregion class-body-c1apitaskv1taskservicegetspendremedystatusresponse
