// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAuthzenV1AuthzenServerServiceUpdateRequest struct {
	AuthzenServerServiceUpdateRequest *shared.AuthzenServerServiceUpdateRequest `request:"mediaType=application/json"`
	AppID                             string                                    `pathParam:"style=simple,explode=false,name=app_id"`
	ID                                string                                    `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateRequest) GetAuthzenServerServiceUpdateRequest() *shared.AuthzenServerServiceUpdateRequest {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceUpdateRequest
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiauthzenv1authzenserverserviceupdaterequest
// #endregion class-body-c1apiauthzenv1authzenserverserviceupdaterequest

type C1APIAuthzenV1AuthzenServerServiceUpdateResponse struct {
	// AuthzenServerServiceUpdateResponse returns the updated server.
	AuthzenServerServiceUpdateResponse *shared.AuthzenServerServiceUpdateResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateResponse) GetAuthzenServerServiceUpdateResponse() *shared.AuthzenServerServiceUpdateResponse {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceUpdateResponse
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAuthzenV1AuthzenServerServiceUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiauthzenv1authzenserverserviceupdateresponse
// #endregion class-body-c1apiauthzenv1authzenserverserviceupdateresponse
