// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIArtifactV1ArtifactServiceDeleteRequest struct {
	ArtifactServiceDeleteRequest *shared.ArtifactServiceDeleteRequest `request:"mediaType=application/json"`
	ID                           string                               `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIArtifactV1ArtifactServiceDeleteRequest) GetArtifactServiceDeleteRequest() *shared.ArtifactServiceDeleteRequest {
	if c == nil {
		return nil
	}
	return c.ArtifactServiceDeleteRequest
}

func (c *C1APIArtifactV1ArtifactServiceDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apiartifactv1artifactservicedeleterequest
// #endregion class-body-c1apiartifactv1artifactservicedeleterequest

type C1APIArtifactV1ArtifactServiceDeleteResponse struct {
	// ArtifactServiceDeleteResponse confirms deletion without returning metadata.
	ArtifactServiceDeleteResponse *shared.ArtifactServiceDeleteResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIArtifactV1ArtifactServiceDeleteResponse) GetArtifactServiceDeleteResponse() *shared.ArtifactServiceDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ArtifactServiceDeleteResponse
}

func (c *C1APIArtifactV1ArtifactServiceDeleteResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIArtifactV1ArtifactServiceDeleteResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIArtifactV1ArtifactServiceDeleteResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiartifactv1artifactservicedeleteresponse
// #endregion class-body-c1apiartifactv1artifactservicedeleteresponse
