// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// Verdict - Restricts results to destinations with at least one row of this
//
//	outcome. TB_TRAFFIC_OUTCOME_UNSPECIFIED applies no verdict filter.
type Verdict string

const (
	VerdictTbTrafficOutcomeUnspecified Verdict = "TB_TRAFFIC_OUTCOME_UNSPECIFIED"
	VerdictTbTrafficOutcomeAllowed     Verdict = "TB_TRAFFIC_OUTCOME_ALLOWED"
	VerdictTbTrafficOutcomeDenied      Verdict = "TB_TRAFFIC_OUTCOME_DENIED"
)

func (e Verdict) ToPointer() *Verdict {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Verdict) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TRAFFIC_OUTCOME_UNSPECIFIED", "TB_TRAFFIC_OUTCOME_ALLOWED", "TB_TRAFFIC_OUTCOME_DENIED":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest struct {
	AppID         string  `pathParam:"style=simple,explode=false,name=app_id"`
	BlockedOnly   *bool   `queryParam:"style=form,explode=true,name=blocked_only"`
	HostContains  *string `queryParam:"style=form,explode=true,name=host_contains"`
	ID            string  `pathParam:"style=simple,explode=false,name=id"`
	IncludeTrend  *bool   `queryParam:"style=form,explode=true,name=include_trend"`
	Limit         *int    `queryParam:"style=form,explode=true,name=limit"`
	Offset        *int    `queryParam:"style=form,explode=true,name=offset"`
	PrincipalKind *string `queryParam:"style=form,explode=true,name=principal_kind"`
	Since         *int64  `integer:"string" queryParam:"style=form,explode=true,name=since"`
	TrendBuckets  *int    `queryParam:"style=form,explode=true,name=trend_buckets"`
	Until         *int64  `integer:"string" queryParam:"style=form,explode=true,name=until"`
	// Restricts results to destinations with at least one row of this
	//  outcome. TB_TRAFFIC_OUTCOME_UNSPECIFIED applies no verdict filter.
	Verdict *Verdict `queryParam:"style=form,explode=true,name=verdict"`
}

func (c C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetBlockedOnly() *bool {
	if c == nil {
		return nil
	}
	return c.BlockedOnly
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetHostContains() *string {
	if c == nil {
		return nil
	}
	return c.HostContains
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetIncludeTrend() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeTrend
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetLimit() *int {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetOffset() *int {
	if c == nil {
		return nil
	}
	return c.Offset
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetPrincipalKind() *string {
	if c == nil {
		return nil
	}
	return c.PrincipalKind
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetTrendBuckets() *int {
	if c == nil {
		return nil
	}
	return c.TrendBuckets
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsRequest) GetVerdict() *Verdict {
	if c == nil {
		return nil
	}
	return c.Verdict
}

// #region class-body-c1apiedgev1edgeservicelistegresstopdestinationsrequest
// #endregion class-body-c1apiedgev1edgeservicelistegresstopdestinationsrequest

type C1APIEdgeV1EdgeServiceListEgressTopDestinationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListEgressTopDestinationsResponse *shared.EdgeServiceListEgressTopDestinationsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsResponse) GetEdgeServiceListEgressTopDestinationsResponse() *shared.EdgeServiceListEgressTopDestinationsResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListEgressTopDestinationsResponse
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListEgressTopDestinationsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistegresstopdestinationsresponse
// #endregion class-body-c1apiedgev1edgeservicelistegresstopdestinationsresponse
