// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAuthzenV1AuthzenServerServiceCreateRequest struct {
	AuthzenServerServiceCreateRequest *shared.AuthzenServerServiceCreateRequest `request:"mediaType=application/json"`
	AppID                             string                                    `pathParam:"style=simple,explode=false,name=app_id"`
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateRequest) GetAuthzenServerServiceCreateRequest() *shared.AuthzenServerServiceCreateRequest {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceCreateRequest
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

// #region class-body-c1apiauthzenv1authzenserverservicecreaterequest
// #endregion class-body-c1apiauthzenv1authzenserverservicecreaterequest

type C1APIAuthzenV1AuthzenServerServiceCreateResponse struct {
	// AuthzenServerServiceCreateResponse returns the newly minted server,
	//  including its capability entitlement ids.
	AuthzenServerServiceCreateResponse *shared.AuthzenServerServiceCreateResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateResponse) GetAuthzenServerServiceCreateResponse() *shared.AuthzenServerServiceCreateResponse {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceCreateResponse
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAuthzenV1AuthzenServerServiceCreateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiauthzenv1authzenserverservicecreateresponse
// #endregion class-body-c1apiauthzenv1authzenserverservicecreateresponse
