// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppSecretAdminServiceRevokeResponse struct {
	// Successful response
	AppSecretAdminServiceRevokeResponse *shared.AppSecretAdminServiceRevokeResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAppV1AppSecretAdminServiceRevokeResponse) GetAppSecretAdminServiceRevokeResponse() *shared.AppSecretAdminServiceRevokeResponse {
	if c == nil {
		return nil
	}
	return c.AppSecretAdminServiceRevokeResponse
}

func (c *C1APIAppV1AppSecretAdminServiceRevokeResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAppV1AppSecretAdminServiceRevokeResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAppV1AppSecretAdminServiceRevokeResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiappv1appsecretadminservicerevokeresponse
// #endregion class-body-c1apiappv1appsecretadminservicerevokeresponse
