// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAuthV1AuthIntrospectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APIAuthV1IntrospectResponse *shared.C1APIAuthV1IntrospectResponse
}
