// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceCreateRequest struct {
	EdgeServiceCreateRequest *shared.EdgeServiceCreateRequest `request:"mediaType=application/json"`
	AppID                    string                           `pathParam:"style=simple,explode=false,name=app_id"`
}

func (c *C1APIEdgeV1EdgeServiceCreateRequest) GetEdgeServiceCreateRequest() *shared.EdgeServiceCreateRequest {
	if c == nil {
		return nil
	}
	return c.EdgeServiceCreateRequest
}

func (c *C1APIEdgeV1EdgeServiceCreateRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

// #region class-body-c1apiedgev1edgeservicecreaterequest
// #endregion class-body-c1apiedgev1edgeservicecreaterequest

type C1APIEdgeV1EdgeServiceCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// EdgeServiceCreateResponse returns the newly minted Edge,
	//  including its capability entitlement id.
	EdgeServiceCreateResponse *shared.EdgeServiceCreateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceCreateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceCreateResponse) GetEdgeServiceCreateResponse() *shared.EdgeServiceCreateResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceCreateResponse
}

func (c *C1APIEdgeV1EdgeServiceCreateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceCreateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicecreateresponse
// #endregion class-body-c1apiedgev1edgeservicecreateresponse
