// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

// Bucket - The bucket field.
type Bucket string

const (
	BucketTbTimeBucketUnspecified Bucket = "TB_TIME_BUCKET_UNSPECIFIED"
	BucketTbTimeBucketHour        Bucket = "TB_TIME_BUCKET_HOUR"
	BucketTbTimeBucketDay         Bucket = "TB_TIME_BUCKET_DAY"
)

func (e Bucket) ToPointer() *Bucket {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Bucket) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TIME_BUCKET_UNSPECIFIED", "TB_TIME_BUCKET_HOUR", "TB_TIME_BUCKET_DAY":
			return true
		}
	}
	return false
}

// Dimension - The dimension field.
type Dimension string

const (
	DimensionTbUsageAttributionDimensionUnspecified Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED"
	DimensionTbUsageAttributionDimensionTeam        Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM"
	DimensionTbUsageAttributionDimensionApplication Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION"
	DimensionTbUsageAttributionDimensionAgent       Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT"
	DimensionTbUsageAttributionDimensionCostCenter  Dimension = "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER"
)

func (e Dimension) ToPointer() *Dimension {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Dimension) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_USAGE_ATTRIBUTION_DIMENSION_UNSPECIFIED", "TB_USAGE_ATTRIBUTION_DIMENSION_TEAM", "TB_USAGE_ATTRIBUTION_DIMENSION_APPLICATION", "TB_USAGE_ATTRIBUTION_DIMENSION_AGENT", "TB_USAGE_ATTRIBUTION_DIMENSION_COST_CENTER":
			return true
		}
	}
	return false
}

type C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	// The bucket field.
	Bucket *Bucket `queryParam:"style=form,explode=true,name=bucket"`
	// The dimension field.
	Dimension *Dimension `queryParam:"style=form,explode=true,name=dimension"`
	ID        string     `pathParam:"style=simple,explode=false,name=id"`
	PageSize  *int       `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string    `queryParam:"style=form,explode=true,name=page_token"`
	Since     *int64     `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until     *int64     `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetBucket() *Bucket {
	if c == nil {
		return nil
	}
	return c.Bucket
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetDimension() *Dimension {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficsummaryrequest
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficsummaryrequest

type C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceGetEgressTrafficSummaryResponse *shared.EdgeServiceGetEgressTrafficSummaryResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryResponse) GetEdgeServiceGetEgressTrafficSummaryResponse() *shared.EdgeServiceGetEgressTrafficSummaryResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceGetEgressTrafficSummaryResponse
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficSummaryResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficsummaryresponse
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficsummaryresponse
