// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ConductorOne/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APIRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsResponse *shared.C1APIRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsResponse
}
