// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest struct {
	AppID    string  `pathParam:"style=simple,explode=false,name=app_id"`
	PageSize *int    `queryParam:"style=form,explode=true,name=page_size"`
	Since    *int64  `integer:"string" queryParam:"style=form,explode=true,name=since"`
	ToolName *string `queryParam:"style=form,explode=true,name=tool_name"`
	Until    *int64  `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) GetToolName() *string {
	if c == nil {
		return nil
	}
	return c.ToolName
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apitbcontrolplanev1tbcontrolplaneservicelisttopagentsrequest
// #endregion class-body-c1apitbcontrolplanev1tbcontrolplaneservicelisttopagentsrequest

type C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	TBControlPlaneServiceListTopAgentsResponse *shared.TBControlPlaneServiceListTopAgentsResponse
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APITbcontrolplaneV1TBControlPlaneServiceListTopAgentsResponse) GetTBControlPlaneServiceListTopAgentsResponse() *shared.TBControlPlaneServiceListTopAgentsResponse {
	if c == nil {
		return nil
	}
	return c.TBControlPlaneServiceListTopAgentsResponse
}

// #region class-body-c1apitbcontrolplanev1tbcontrolplaneservicelisttopagentsresponse
// #endregion class-body-c1apitbcontrolplanev1tbcontrolplaneservicelisttopagentsresponse
