// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsRequest struct {
	VirtualMCPToolsetBindingServiceCreateBindingsRequest *shared.VirtualMCPToolsetBindingServiceCreateBindingsRequest `request:"mediaType=application/json"`
	VirtualMcpServerID                                   string                                                       `pathParam:"style=simple,explode=false,name=virtual_mcp_server_id"`
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsRequest) GetVirtualMCPToolsetBindingServiceCreateBindingsRequest() *shared.VirtualMCPToolsetBindingServiceCreateBindingsRequest {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolsetBindingServiceCreateBindingsRequest
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsRequest) GetVirtualMcpServerID() string {
	if c == nil {
		return ""
	}
	return c.VirtualMcpServerID
}

// #region class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicecreatebindingsrequest
// #endregion class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicecreatebindingsrequest

type C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// VirtualMCPToolsetBindingServiceCreateBindingsResponse contains the resulting assignments.
	VirtualMCPToolsetBindingServiceCreateBindingsResponse *shared.VirtualMCPToolsetBindingServiceCreateBindingsResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolsetBindingServiceCreateBindingsResponse) GetVirtualMCPToolsetBindingServiceCreateBindingsResponse() *shared.VirtualMCPToolsetBindingServiceCreateBindingsResponse {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolsetBindingServiceCreateBindingsResponse
}

// #region class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicecreatebindingsresponse
// #endregion class-body-c1apiaigovernancev1virtualmcptoolsetbindingservicecreatebindingsresponse
