// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIGolinkV1GoLinkServiceUpdateRequest struct {
	GoLinkServiceUpdateRequest *shared.GoLinkServiceUpdateRequest `request:"mediaType=application/json"`
	ID                         string                             `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIGolinkV1GoLinkServiceUpdateRequest) GetGoLinkServiceUpdateRequest() *shared.GoLinkServiceUpdateRequest {
	if c == nil {
		return nil
	}
	return c.GoLinkServiceUpdateRequest
}

func (c *C1APIGolinkV1GoLinkServiceUpdateRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apigolinkv1golinkserviceupdaterequest
// #endregion class-body-c1apigolinkv1golinkserviceupdaterequest

type C1APIGolinkV1GoLinkServiceUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	GoLinkServiceUpdateResponse *shared.GoLinkServiceUpdateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIGolinkV1GoLinkServiceUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIGolinkV1GoLinkServiceUpdateResponse) GetGoLinkServiceUpdateResponse() *shared.GoLinkServiceUpdateResponse {
	if c == nil {
		return nil
	}
	return c.GoLinkServiceUpdateResponse
}

func (c *C1APIGolinkV1GoLinkServiceUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIGolinkV1GoLinkServiceUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apigolinkv1golinkserviceupdateresponse
// #endregion class-body-c1apigolinkv1golinkserviceupdateresponse
