// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyRequest struct {
	AuthzenServerServiceTestAuthzenPolicyRequest *shared.AuthzenServerServiceTestAuthzenPolicyRequest `request:"mediaType=application/json"`
	AppID                                        string                                               `pathParam:"style=simple,explode=false,name=app_id"`
	AuthzenServerID                              string                                               `pathParam:"style=simple,explode=false,name=authzen_server_id"`
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyRequest) GetAuthzenServerServiceTestAuthzenPolicyRequest() *shared.AuthzenServerServiceTestAuthzenPolicyRequest {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceTestAuthzenPolicyRequest
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyRequest) GetAuthzenServerID() string {
	if c == nil {
		return ""
	}
	return c.AuthzenServerID
}

// #region class-body-c1apiauthzenv1authzenserverservicetestauthzenpolicyrequest
// #endregion class-body-c1apiauthzenv1authzenserverservicetestauthzenpolicyrequest

type C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyResponse struct {
	// AuthzenServerServiceTestAuthzenPolicyResponse returns the evaluation
	//  outcome for authoring feedback.
	AuthzenServerServiceTestAuthzenPolicyResponse *shared.AuthzenServerServiceTestAuthzenPolicyResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyResponse) GetAuthzenServerServiceTestAuthzenPolicyResponse() *shared.AuthzenServerServiceTestAuthzenPolicyResponse {
	if c == nil {
		return nil
	}
	return c.AuthzenServerServiceTestAuthzenPolicyResponse
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAuthzenV1AuthzenServerServiceTestAuthzenPolicyResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiauthzenv1authzenserverservicetestauthzenpolicyresponse
// #endregion class-body-c1apiauthzenv1authzenserverservicetestauthzenpolicyresponse
