// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitRequest struct {
	MyFundLimitsServiceSetTemporaryLimitRequest *shared.MyFundLimitsServiceSetTemporaryLimitRequest `request:"mediaType=application/json"`
	AppID                                       string                                              `pathParam:"style=simple,explode=false,name=app_id"`
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitRequest) GetMyFundLimitsServiceSetTemporaryLimitRequest() *shared.MyFundLimitsServiceSetTemporaryLimitRequest {
	if c == nil {
		return nil
	}
	return c.MyFundLimitsServiceSetTemporaryLimitRequest
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

// #region class-body-c1apifundsv1myfundlimitsservicesettemporarylimitrequest
// #endregion class-body-c1apifundsv1myfundlimitsservicesettemporarylimitrequest

type C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	MyFundLimitsServiceSetTemporaryLimitResponse *shared.MyFundLimitsServiceSetTemporaryLimitResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitResponse) GetMyFundLimitsServiceSetTemporaryLimitResponse() *shared.MyFundLimitsServiceSetTemporaryLimitResponse {
	if c == nil {
		return nil
	}
	return c.MyFundLimitsServiceSetTemporaryLimitResponse
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIFundsV1MyFundLimitsServiceSetTemporaryLimitResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apifundsv1myfundlimitsservicesettemporarylimitresponse
// #endregion class-body-c1apifundsv1myfundlimitsservicesettemporarylimitresponse
