// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsRequest struct {
	VirtualMCPToolBindingServiceDeleteBindingsRequest *shared.VirtualMCPToolBindingServiceDeleteBindingsRequest `request:"mediaType=application/json"`
	VirtualMcpServerID                                string                                                    `pathParam:"style=simple,explode=false,name=virtual_mcp_server_id"`
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsRequest) GetVirtualMCPToolBindingServiceDeleteBindingsRequest() *shared.VirtualMCPToolBindingServiceDeleteBindingsRequest {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolBindingServiceDeleteBindingsRequest
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsRequest) GetVirtualMcpServerID() string {
	if c == nil {
		return ""
	}
	return c.VirtualMcpServerID
}

// #region class-body-c1apiaigovernancev1virtualmcptoolbindingservicedeletebindingsrequest
// #endregion class-body-c1apiaigovernancev1virtualmcptoolbindingservicedeletebindingsrequest

type C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// VirtualMCPToolBindingServiceDeleteBindingsResponse confirms the assignments were deleted.
	VirtualMCPToolBindingServiceDeleteBindingsResponse *shared.VirtualMCPToolBindingServiceDeleteBindingsResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1VirtualMCPToolBindingServiceDeleteBindingsResponse) GetVirtualMCPToolBindingServiceDeleteBindingsResponse() *shared.VirtualMCPToolBindingServiceDeleteBindingsResponse {
	if c == nil {
		return nil
	}
	return c.VirtualMCPToolBindingServiceDeleteBindingsResponse
}

// #region class-body-c1apiaigovernancev1virtualmcptoolbindingservicedeletebindingsresponse
// #endregion class-body-c1apiaigovernancev1virtualmcptoolbindingservicedeletebindingsresponse
