// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"net/http"
)

type C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest struct {
	AppID                 string  `pathParam:"style=simple,explode=false,name=app_id"`
	DestHost              *string `queryParam:"style=form,explode=true,name=dest_host"`
	DestHostSuffix        *string `queryParam:"style=form,explode=true,name=dest_host_suffix"`
	EgressEnforcementMode *string `queryParam:"style=form,explode=true,name=egress_enforcement_mode"`
	EgressPolicyVerdict   *string `queryParam:"style=form,explode=true,name=egress_policy_verdict"`
	ID                    string  `pathParam:"style=simple,explode=false,name=id"`
	Limit                 *int    `queryParam:"style=form,explode=true,name=limit"`
	PrincipalUserID       *string `queryParam:"style=form,explode=true,name=principal_user_id"`
	Since                 *int64  `integer:"string" queryParam:"style=form,explode=true,name=since"`
	Until                 *int64  `integer:"string" queryParam:"style=form,explode=true,name=until"`
}

func (c C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetDestHost() *string {
	if c == nil {
		return nil
	}
	return c.DestHost
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetDestHostSuffix() *string {
	if c == nil {
		return nil
	}
	return c.DestHostSuffix
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetEgressEnforcementMode() *string {
	if c == nil {
		return nil
	}
	return c.EgressEnforcementMode
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetEgressPolicyVerdict() *string {
	if c == nil {
		return nil
	}
	return c.EgressPolicyVerdict
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetLimit() *int {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetPrincipalUserID() *string {
	if c == nil {
		return nil
	}
	return c.PrincipalUserID
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetSince() *int64 {
	if c == nil {
		return nil
	}
	return c.Since
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryRequest) GetUntil() *int64 {
	if c == nil {
		return nil
	}
	return c.Until
}

// #region class-body-c1apiedgev1edgeservicelistegressdenialsummaryrequest
// #endregion class-body-c1apiedgev1edgeservicelistegressdenialsummaryrequest

type C1APIEdgeV1EdgeServiceListEgressDenialSummaryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	EdgeServiceListEgressDenialSummaryResponse *shared.EdgeServiceListEgressDenialSummaryResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryResponse) GetEdgeServiceListEgressDenialSummaryResponse() *shared.EdgeServiceListEgressDenialSummaryResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceListEgressDenialSummaryResponse
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceListEgressDenialSummaryResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-c1apiedgev1edgeservicelistegressdenialsummaryresponse
// #endregion class-body-c1apiedgev1edgeservicelistegressdenialsummaryresponse
