// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/models/shared"
	"net/http"
)

type C1APIAttributeV1AttributesListRiskLevelsRequest struct {
	PageSize  *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (o *C1APIAttributeV1AttributesListRiskLevelsRequest) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *C1APIAttributeV1AttributesListRiskLevelsRequest) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

type C1APIAttributeV1AttributesListRiskLevelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	ListRiskLevelsResponse *shared.ListRiskLevelsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *C1APIAttributeV1AttributesListRiskLevelsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *C1APIAttributeV1AttributesListRiskLevelsResponse) GetListRiskLevelsResponse() *shared.ListRiskLevelsResponse {
	if o == nil {
		return nil
	}
	return o.ListRiskLevelsResponse
}

func (o *C1APIAttributeV1AttributesListRiskLevelsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *C1APIAttributeV1AttributesListRiskLevelsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
