// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AgentMode - The mode of the agent, full control, change policy only, or comment only.
type AgentMode string

const (
	AgentModeApprovalAgentModeUnspecified      AgentMode = "APPROVAL_AGENT_MODE_UNSPECIFIED"
	AgentModeApprovalAgentModeFullControl      AgentMode = "APPROVAL_AGENT_MODE_FULL_CONTROL"
	AgentModeApprovalAgentModeChangePolicyOnly AgentMode = "APPROVAL_AGENT_MODE_CHANGE_POLICY_ONLY"
	AgentModeApprovalAgentModeCommentOnly      AgentMode = "APPROVAL_AGENT_MODE_COMMENT_ONLY"
)

func (e AgentMode) ToPointer() *AgentMode {
	return &e
}

// AgentApproval - The agent to assign the task to.
type AgentApproval struct {
	// The mode of the agent, full control, change policy only, or comment only.
	AgentMode *AgentMode `json:"agentMode,omitempty"`
	// The agent user ID to assign the task to.
	AgentUserID *string `json:"agentUserId,omitempty"`
	// Instructions for the agent.
	Instructions *string `json:"instructions,omitempty"`
	// The allow list of policy IDs to re-route the task to.
	PolicyIds []string `json:"policyIds,omitempty"`
}

func (o *AgentApproval) GetAgentMode() *AgentMode {
	if o == nil {
		return nil
	}
	return o.AgentMode
}

func (o *AgentApproval) GetAgentUserID() *string {
	if o == nil {
		return nil
	}
	return o.AgentUserID
}

func (o *AgentApproval) GetInstructions() *string {
	if o == nil {
		return nil
	}
	return o.Instructions
}

func (o *AgentApproval) GetPolicyIds() []string {
	if o == nil {
		return nil
	}
	return o.PolicyIds
}
