// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// The AppSecretResource message.
type AppSecretResource struct {
	// The app that this secret belongs to.
	AppID *string `json:"appId,omitempty"`
	// The secret type that this secret is.
	AppResourceTypeID *string    `json:"appResourceTypeId,omitempty"`
	CreatedAt         *time.Time `json:"createdAt,omitempty"`
	DeletedAt         *time.Time `json:"deletedAt,omitempty"`
	// The display name for this secret.
	DisplayName *string `json:"displayName,omitempty"`
	// The id of the secret.
	ID *string `json:"id,omitempty"`
	// The ID of the user that is associated with the AppSecret.
	IdentityAppUserID *string    `json:"identityAppUserId,omitempty"`
	LastUsedAt        *time.Time `json:"lastUsedAt,omitempty"`
	SecretCreatedAt   *time.Time `json:"secretCreatedAt,omitempty"`
	SecretExpiresAt   *time.Time `json:"secretExpiresAt,omitempty"`
	UpdatedAt         *time.Time `json:"updatedAt,omitempty"`
}

func (a AppSecretResource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppSecretResource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppSecretResource) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AppSecretResource) GetAppResourceTypeID() *string {
	if a == nil {
		return nil
	}
	return a.AppResourceTypeID
}

func (a *AppSecretResource) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AppSecretResource) GetDeletedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DeletedAt
}

func (a *AppSecretResource) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AppSecretResource) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AppSecretResource) GetIdentityAppUserID() *string {
	if a == nil {
		return nil
	}
	return a.IdentityAppUserID
}

func (a *AppSecretResource) GetLastUsedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsedAt
}

func (a *AppSecretResource) GetSecretCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.SecretCreatedAt
}

func (a *AppSecretResource) GetSecretExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.SecretExpiresAt
}

func (a *AppSecretResource) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
