// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The AppSecretExpandMask message.
type AppSecretExpandMask struct {
	// The paths field.
	Paths []string `json:"paths,omitempty"`
}

func (a *AppSecretExpandMask) GetPaths() []string {
	if a == nil {
		return nil
	}
	return a.Paths
}
