// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The AppSecretResourceView message.
//
// This message contains a oneof named destination. Only a single field of the following list may be set at a time:
//   - paperVaultId
//   - fullKnowledgeVaultId
type AppSecretResourceView struct {
	// The alertCount field.
	AlertCount *int `json:"alertCount,omitempty"`
	// The appPath field.
	AppPath              *string               `json:"appPath,omitempty"`
	AppSecret            *AppSecretResource    `json:"appSecret,omitempty"`
	CredentialRevocation *CredentialRevocation `json:"credentialRevocation,omitempty"`
	// The fullKnowledgeVaultId field.
	// This field is part of the `destination` oneof.
	// See the documentation for `c1.api.app.v1.AppSecretResourceView` for more details.
	FullKnowledgeVaultID *string `json:"fullKnowledgeVaultId,omitempty"`
	// The paperVaultId field.
	// This field is part of the `destination` oneof.
	// See the documentation for `c1.api.app.v1.AppSecretResourceView` for more details.
	PaperVaultID *string `json:"paperVaultId,omitempty"`
	// The resourceTypePath field.
	ResourceTypePath *string `json:"resourceTypePath,omitempty"`
}

func (a *AppSecretResourceView) GetAlertCount() *int {
	if a == nil {
		return nil
	}
	return a.AlertCount
}

func (a *AppSecretResourceView) GetAppPath() *string {
	if a == nil {
		return nil
	}
	return a.AppPath
}

func (a *AppSecretResourceView) GetAppSecret() *AppSecretResource {
	if a == nil {
		return nil
	}
	return a.AppSecret
}

func (a *AppSecretResourceView) GetCredentialRevocation() *CredentialRevocation {
	if a == nil {
		return nil
	}
	return a.CredentialRevocation
}

func (a *AppSecretResourceView) GetFullKnowledgeVaultID() *string {
	if a == nil {
		return nil
	}
	return a.FullKnowledgeVaultID
}

func (a *AppSecretResourceView) GetPaperVaultID() *string {
	if a == nil {
		return nil
	}
	return a.PaperVaultID
}

func (a *AppSecretResourceView) GetResourceTypePath() *string {
	if a == nil {
		return nil
	}
	return a.ResourceTypePath
}
