// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AttributeType - The AttributeType message.
type AttributeType struct {
	// The id field.
	ID *string `json:"id,omitempty"`
	// The name field.
	Name *string `json:"name,omitempty"`
}

func (o *AttributeType) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AttributeType) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
