// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// Mode - Configures the intended evaluation behavior: DISABLED and UNSPECIFIED
//
//	deny requests, OBSERVE records policy decisions without enforcing them,
//	and ENFORCE applies policy decisions. Evaluation endpoints are not served
//	by this control-plane API.
type Mode string

const (
	ModeAuthzenModeUnspecified Mode = "AUTHZEN_MODE_UNSPECIFIED"
	ModeAuthzenModeDisabled    Mode = "AUTHZEN_MODE_DISABLED"
	ModeAuthzenModeObserve     Mode = "AUTHZEN_MODE_OBSERVE"
	ModeAuthzenModeEnforce     Mode = "AUTHZEN_MODE_ENFORCE"
)

func (e Mode) ToPointer() *Mode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Mode) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTHZEN_MODE_UNSPECIFIED", "AUTHZEN_MODE_DISABLED", "AUTHZEN_MODE_OBSERVE", "AUTHZEN_MODE_ENFORCE":
			return true
		}
	}
	return false
}

// AuthzenServer is the customer-facing AuthZEN PDP endpoint for one App.
type AuthzenServer struct {
	// App identifier.
	AppID     *string    `json:"appId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// The minted "evaluate" entitlement (derived from the server id; returned
	//  for linking) -- grant it to a caller to let it POST the access
	//  evaluation endpoint.
	EvaluateEntitlementID *string `json:"evaluateEntitlementId,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// Configures the intended evaluation behavior: DISABLED and UNSPECIFIED
	//  deny requests, OBSERVE records policy decisions without enforcing them,
	//  and ENFORCE applies policy decisions. Evaluation endpoints are not served
	//  by this control-plane API.
	Mode *Mode `json:"mode,omitempty"`
	// The minted "search" entitlement (derived from the server id; returned
	//  for linking) -- grant it to a caller to let it POST the
	//  subject/resource/action search endpoints.
	SearchEntitlementID *string    `json:"searchEntitlementId,omitempty"`
	UpdatedAt           *time.Time `json:"updatedAt,omitempty"`
}

func (a AuthzenServer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthzenServer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthzenServer) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AuthzenServer) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AuthzenServer) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AuthzenServer) GetEvaluateEntitlementID() *string {
	if a == nil {
		return nil
	}
	return a.EvaluateEntitlementID
}

func (a *AuthzenServer) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AuthzenServer) GetMode() *Mode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AuthzenServer) GetSearchEntitlementID() *string {
	if a == nil {
		return nil
	}
	return a.SearchEntitlementID
}

func (a *AuthzenServer) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
