// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AuthzenRef names an AuthzenServer. An empty app_id means the Edge's own app
//
//	for rules saved before cross-app references were supported.
type AuthzenRef struct {
	// App that owns the AuthzenServer. Empty resolves to the Edge's app.
	AppID *string `json:"appId,omitempty"`
	// ID of the AuthzenServer. It must exist in the target app and be in OBSERVE
	//  or ENFORCE mode.
	ServerID *string `json:"serverId,omitempty"`
}

func (a *AuthzenRef) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AuthzenRef) GetServerID() *string {
	if a == nil {
		return nil
	}
	return a.ServerID
}
