// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AuthzenServerServiceTestAuthzenPolicyResponse returns the evaluation
//
//	outcome for authoring feedback.
type AuthzenServerServiceTestAuthzenPolicyResponse struct {
	// The policy's decision. Only meaningful when `error` is empty.
	Decision *bool `json:"decision,omitempty"`
	// Compile or runtime error, if evaluation could not produce a decision.
	Error     *string        `json:"error,omitempty"`
	Variables map[string]any `json:"variables,omitempty"`
}

func (a *AuthzenServerServiceTestAuthzenPolicyResponse) GetDecision() *bool {
	if a == nil {
		return nil
	}
	return a.Decision
}

func (a *AuthzenServerServiceTestAuthzenPolicyResponse) GetError() *string {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AuthzenServerServiceTestAuthzenPolicyResponse) GetVariables() map[string]any {
	if a == nil {
		return nil
	}
	return a.Variables
}
