// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// Kind - Type of configuration.
type Kind string

const (
	KindAuthorityKindUnspecified        Kind = "AUTHORITY_KIND_UNSPECIFIED"
	KindAuthorityKindFundPolicy         Kind = "AUTHORITY_KIND_FUND_POLICY"
	KindAuthorityKindFundAssignment     Kind = "AUTHORITY_KIND_FUND_ASSIGNMENT"
	KindAuthorityKindFundRule           Kind = "AUTHORITY_KIND_FUND_RULE"
	KindAuthorityKindTenantAppCap       Kind = "AUTHORITY_KIND_TENANT_APP_CAP"
	KindAuthorityKindSubjectAppLimit    Kind = "AUTHORITY_KIND_SUBJECT_APP_LIMIT"
	KindAuthorityKindEntitlementBinding Kind = "AUTHORITY_KIND_ENTITLEMENT_BINDING"
	KindAuthorityKindAppUser            Kind = "AUTHORITY_KIND_APP_USER"
	KindAuthorityKindUser               Kind = "AUTHORITY_KIND_USER"
)

func (e Kind) ToPointer() *Kind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Kind) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTHORITY_KIND_UNSPECIFIED", "AUTHORITY_KIND_FUND_POLICY", "AUTHORITY_KIND_FUND_ASSIGNMENT", "AUTHORITY_KIND_FUND_RULE", "AUTHORITY_KIND_TENANT_APP_CAP", "AUTHORITY_KIND_SUBJECT_APP_LIMIT", "AUTHORITY_KIND_ENTITLEMENT_BINDING", "AUTHORITY_KIND_APP_USER", "AUTHORITY_KIND_USER":
			return true
		}
	}
	return false
}

// AuthorityRef identifies a configuration and the revision admission read.
type AuthorityRef struct {
	// Whether admission found no configuration of this kind.
	Absent *bool `json:"absent,omitempty"`
	// Application entitlement ID, for entitlement-binding authorities.
	AppEntitlementID *string `json:"appEntitlementId,omitempty"`
	// Application ID the configuration applies to.
	AppID *string `json:"appId,omitempty"`
	// Application user ID, for application-user authorities.
	AppUserID *string `json:"appUserId,omitempty"`
	// Type of configuration.
	Kind *Kind `json:"kind,omitempty"`
	// Fund rule ID, for fund-rule authorities.
	RuleID *string `json:"ruleId,omitempty"`
	// User ID the configuration applies to.
	UserID *string `json:"userId,omitempty"`
	// Configuration revision read during admission.
	Version *int64 `integer:"string" json:"version,omitempty"`
}

func (a AuthorityRef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthorityRef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthorityRef) GetAbsent() *bool {
	if a == nil {
		return nil
	}
	return a.Absent
}

func (a *AuthorityRef) GetAppEntitlementID() *string {
	if a == nil {
		return nil
	}
	return a.AppEntitlementID
}

func (a *AuthorityRef) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AuthorityRef) GetAppUserID() *string {
	if a == nil {
		return nil
	}
	return a.AppUserID
}

func (a *AuthorityRef) GetKind() *Kind {
	if a == nil {
		return nil
	}
	return a.Kind
}

func (a *AuthorityRef) GetRuleID() *string {
	if a == nil {
		return nil
	}
	return a.RuleID
}

func (a *AuthorityRef) GetUserID() *string {
	if a == nil {
		return nil
	}
	return a.UserID
}

func (a *AuthorityRef) GetVersion() *int64 {
	if a == nil {
		return nil
	}
	return a.Version
}
