// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AuthzenTestResource identifies the AuthZEN resource for a test evaluation.
type AuthzenTestResource struct {
	// Resource identifier.
	ID         *string        `json:"id,omitempty"`
	Properties map[string]any `json:"properties,omitempty"`
	// Resource type, e.g. "app_resource".
	Type *string `json:"type,omitempty"`
}

func (a *AuthzenTestResource) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AuthzenTestResource) GetProperties() map[string]any {
	if a == nil {
		return nil
	}
	return a.Properties
}

func (a *AuthzenTestResource) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}
