// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIPolicyV1SelfApproval - The SelfApproval message.
type C1APIPolicyV1SelfApproval struct {
	// The assignedUserIds field.
	AssignedUserIds []string `json:"assignedUserIds,omitempty"`
	// The fallback field.
	Fallback *bool `json:"fallback,omitempty"`
	//  Self approval is the target of the ticket
	//
	FallbackUserIds []string `json:"fallbackUserIds,omitempty"`
}
