// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskRef - The TaskRef message.
type C1APITaskV1TaskRef struct {
	// The id field.
	ID *string `json:"id,omitempty"`
}
