// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1AppEntitlementView - The AppEntitlementView message.
type C1APIAppV1AppEntitlementView struct {
	// The AppEntitlement message.
	//
	// This message contains a oneof named max_grant_duration. Only a single field of the following list may be set at a time:
	//   - durationUnset
	//   - durationGrant
	//
	AppEntitlement *C1APIAppV1AppEntitlement `json:"appEntitlement,omitempty"`
	// The appPath field.
	AppPath *string `json:"appPath,omitempty"`
	// The appResourcePath field.
	AppResourcePath *string `json:"appResourcePath,omitempty"`
	// The appResourceTypePath field.
	AppResourceTypePath *string `json:"appResourceTypePath,omitempty"`
}
