// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIPolicyV1EntitlementOwnerApproval - The EntitlementOwnerApproval message.
type C1APIPolicyV1EntitlementOwnerApproval struct {
	//  Entitlement owner is based on the current entitlement's id and doesn't need to have self-contained data
	//
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty"`
	// The fallback field.
	Fallback *bool `json:"fallback,omitempty"`
	// The fallbackUserIds field.
	FallbackUserIds []string `json:"fallbackUserIds,omitempty"`
}
