// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1AppEntitlementExpandMask - The AppEntitlementExpandMask message.
type C1APIAppV1AppEntitlementExpandMask struct {
	// The paths field.
	Paths []string `json:"paths,omitempty"`
}
