// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// C1APIAppV1AppEntitlementUserBinding - The AppEntitlementUserBinding message.
type C1APIAppV1AppEntitlementUserBinding struct {
	// The appEntitlementId field.
	AppEntitlementID *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserID     *string    `json:"appUserId,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	DeletedAt     *time.Time `json:"deletedAt,omitempty"`
	DeprovisionAt *time.Time `json:"deprovisionAt,omitempty"`
}
