// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1AppEntitlementWithUserBindings - The AppEntitlementWithUserBindings message.
type C1APIAppV1AppEntitlementWithUserBindings struct {
	// The appEntitlementUserBindings field.
	AppEntitlementUserBindings []C1APIAppV1AppEntitlementUserBinding `json:"appEntitlementUserBindings,omitempty"`
	// The AppEntitlementView message.
	Entitlement *C1APIAppV1AppEntitlementView `json:"entitlement,omitempty"`
}
