// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskServiceCreateGrantRequest - The TaskServiceCreateGrantRequest message.
type C1APITaskV1TaskServiceCreateGrantRequest struct {
	// The appEntitlementId field.
	AppEntitlementID *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserID *string `json:"appUserId,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	//  Make sure to update the TicketExpandMask
	//
	ExpandMask    *C1APITaskV1TaskExpandMask `json:"expandMask,omitempty"`
	GrantDuration *string                    `json:"grantDuration,omitempty"`
	// The identityUserId field.
	IdentityUserID *string `json:"identityUserId,omitempty"`
}
