// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskServiceCreateGrantResponse - The TaskServiceCreateGrantResponse message.
type C1APITaskV1TaskServiceCreateGrantResponse struct {
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
	// The TaskView message.
	TaskView *C1APITaskV1TaskView `json:"taskView,omitempty"`
}
