// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsRequest - The RequestCatalogSearchServiceSearchEntitlementsRequest message.
type C1APIRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsRequest struct {
	// The entitlementAlias field.
	EntitlementAlias *string `json:"entitlementAlias,omitempty"`
	// The AppEntitlementExpandMask message.
	ExpandMask *C1APIAppV1AppEntitlementExpandMask `json:"expandMask,omitempty"`
	// The pageSize field.
	PageSize *float64 `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// The query field.
	Query *string `json:"query,omitempty"`
}
