// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1GetAppResponse - The GetAppResponse message.
type C1APIAppV1GetAppResponse struct {
	// The App message.
	App *C1APIAppV1App `json:"app,omitempty"`
}
