// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// C1APIPolicyV1ApprovedAction - The ApprovedAction message.
type C1APIPolicyV1ApprovedAction struct {
	ApprovedAt *time.Time `json:"approvedAt,omitempty"`
	// The entitlements field.
	Entitlements []C1APIPolicyV1AppEntitlementReference `json:"entitlements,omitempty"`
	// The userId field.
	UserID *string `json:"userId,omitempty"`
}
