// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// C1APIPolicyV1ErroredAction - The ErroredAction message.
type C1APIPolicyV1ErroredAction struct {
	// The description field.
	Description *string `json:"description,omitempty"`
	// The errorCode field.
	ErrorCode *string    `json:"errorCode,omitempty"`
	ErroredAt *time.Time `json:"erroredAt,omitempty"`
}
