// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIPolicyV1PolicySteps - The PolicySteps message.
type C1APIPolicyV1PolicySteps struct {
	// The steps field.
	Steps []C1APIPolicyV1PolicyStep `json:"steps,omitempty"`
}
