// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIPolicyV1ConnectorProvision - The ConnectorProvision message.
type C1APIPolicyV1ConnectorProvision struct {
}
