// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskActionsServiceCommentRequestInput - The TaskActionsServiceCommentRequest message.
type C1APITaskV1TaskActionsServiceCommentRequestInput struct {
	// The comment field.
	Comment *string `json:"comment,omitempty"`
	//  Make sure to update the TicketExpandMask
	//
	ExpandMask *C1APITaskV1TaskExpandMask `json:"expandMask,omitempty"`
}
