// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIPolicyV1ManualProvision - The ManualProvision message.
type C1APIPolicyV1ManualProvision struct {
	// The instructions field.
	Instructions *string `json:"instructions,omitempty"`
	// The userIds field.
	UserIds []string `json:"userIds,omitempty"`
}
