// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1GetAppEntitlementResponse - The GetAppEntitlementResponse message.
type C1APIAppV1GetAppEntitlementResponse struct {
	// The AppEntitlementView message.
	AppEntitlementView *C1APIAppV1AppEntitlementView `json:"appEntitlementView,omitempty"`
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
}
