// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// C1APIPolicyV1ApprovalInstanceState - The state field.
type C1APIPolicyV1ApprovalInstanceState string

const (
	C1APIPolicyV1ApprovalInstanceStateApprovalInstanceStateUnspecified          C1APIPolicyV1ApprovalInstanceState = "APPROVAL_INSTANCE_STATE_UNSPECIFIED"
	C1APIPolicyV1ApprovalInstanceStateApprovalInstanceStateInit                 C1APIPolicyV1ApprovalInstanceState = "APPROVAL_INSTANCE_STATE_INIT"
	C1APIPolicyV1ApprovalInstanceStateApprovalInstanceStateSendingNotifications C1APIPolicyV1ApprovalInstanceState = "APPROVAL_INSTANCE_STATE_SENDING_NOTIFICATIONS"
	C1APIPolicyV1ApprovalInstanceStateApprovalInstanceStateWaiting              C1APIPolicyV1ApprovalInstanceState = "APPROVAL_INSTANCE_STATE_WAITING"
	C1APIPolicyV1ApprovalInstanceStateApprovalInstanceStateDone                 C1APIPolicyV1ApprovalInstanceState = "APPROVAL_INSTANCE_STATE_DONE"
)

func (e C1APIPolicyV1ApprovalInstanceState) ToPointer() *C1APIPolicyV1ApprovalInstanceState {
	return &e
}

func (e *C1APIPolicyV1ApprovalInstanceState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "APPROVAL_INSTANCE_STATE_UNSPECIFIED":
		fallthrough
	case "APPROVAL_INSTANCE_STATE_INIT":
		fallthrough
	case "APPROVAL_INSTANCE_STATE_SENDING_NOTIFICATIONS":
		fallthrough
	case "APPROVAL_INSTANCE_STATE_WAITING":
		fallthrough
	case "APPROVAL_INSTANCE_STATE_DONE":
		*e = C1APIPolicyV1ApprovalInstanceState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for C1APIPolicyV1ApprovalInstanceState: %v", v)
	}
}

// C1APIPolicyV1ApprovalInstance - The ApprovalInstance message.
//
// This message contains a oneof named outcome. Only a single field of the following list may be set at a time:
//   - approved
//   - denied
//   - reassigned
//   - restarted
//   - reassignedByError
type C1APIPolicyV1ApprovalInstance struct {
	// The Approval message.
	//
	// This message contains a oneof named typ. Only a single field of the following list may be set at a time:
	//   - users
	//   - manager
	//   - appOwners
	//   - group
	//   - self
	//   - entitlementOwners
	//
	Approval *C1APIPolicyV1Approval `json:"approval,omitempty"`
	// The ApprovedAction message.
	Approved *C1APIPolicyV1ApprovedAction `json:"approved,omitempty"`
	// The DeniedAction message.
	Denied *C1APIPolicyV1DeniedAction `json:"denied,omitempty"`
	// The ReassignedAction message.
	Reassigned *C1APIPolicyV1ReassignedAction `json:"reassigned,omitempty"`
	// The ReassignedByErrorAction message.
	ReassignedByError *C1APIPolicyV1ReassignedByErrorAction `json:"reassignedByError,omitempty"`
	// The RestartAction message.
	Restarted *C1APIPolicyV1RestartAction `json:"restarted,omitempty"`
	// The state field.
	State *C1APIPolicyV1ApprovalInstanceState `json:"state,omitempty"`
}
