// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIUserV1UserAttributeMappingSource - The UserAttributeMappingSource message.
type C1APIUserV1UserAttributeMappingSource struct {
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserID *string `json:"appUserId,omitempty"`
	// The appUserProfileAttributeKey field.
	AppUserProfileAttributeKey *string `json:"appUserProfileAttributeKey,omitempty"`
	// The userAttributeMappingId field.
	UserAttributeMappingID *string `json:"userAttributeMappingId,omitempty"`
	// The value field.
	Value *string `json:"value,omitempty"`
}
