// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIUserV1UserServiceGetResponse - The UserServiceGetResponse message.
type C1APIUserV1UserServiceGetResponse struct {
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
	// The UserView message.
	UserView *C1APIUserV1UserView `json:"userView,omitempty"`
}
