// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// C1APITaskV1TaskTypeRevokeOutcome - The outcome field.
type C1APITaskV1TaskTypeRevokeOutcome string

const (
	C1APITaskV1TaskTypeRevokeOutcomeRevokeOutcomeUnspecified C1APITaskV1TaskTypeRevokeOutcome = "REVOKE_OUTCOME_UNSPECIFIED"
	C1APITaskV1TaskTypeRevokeOutcomeRevokeOutcomeRevoked     C1APITaskV1TaskTypeRevokeOutcome = "REVOKE_OUTCOME_REVOKED"
	C1APITaskV1TaskTypeRevokeOutcomeRevokeOutcomeDenied      C1APITaskV1TaskTypeRevokeOutcome = "REVOKE_OUTCOME_DENIED"
	C1APITaskV1TaskTypeRevokeOutcomeRevokeOutcomeError       C1APITaskV1TaskTypeRevokeOutcome = "REVOKE_OUTCOME_ERROR"
	C1APITaskV1TaskTypeRevokeOutcomeRevokeOutcomeCancelled   C1APITaskV1TaskTypeRevokeOutcome = "REVOKE_OUTCOME_CANCELLED"
)

func (e C1APITaskV1TaskTypeRevokeOutcome) ToPointer() *C1APITaskV1TaskTypeRevokeOutcome {
	return &e
}

func (e *C1APITaskV1TaskTypeRevokeOutcome) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "REVOKE_OUTCOME_UNSPECIFIED":
		fallthrough
	case "REVOKE_OUTCOME_REVOKED":
		fallthrough
	case "REVOKE_OUTCOME_DENIED":
		fallthrough
	case "REVOKE_OUTCOME_ERROR":
		fallthrough
	case "REVOKE_OUTCOME_CANCELLED":
		*e = C1APITaskV1TaskTypeRevokeOutcome(v)
		return nil
	default:
		return fmt.Errorf("invalid value for C1APITaskV1TaskTypeRevokeOutcome: %v", v)
	}
}

// C1APITaskV1TaskTypeRevoke - The TaskTypeRevoke message.
type C1APITaskV1TaskTypeRevoke struct {
	// The appEntitlementId field.
	AppEntitlementID *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserID *string `json:"appUserId,omitempty"`
	// The identityUserId field.
	IdentityUserID *string `json:"identityUserId,omitempty"`
	// The outcome field.
	Outcome     *C1APITaskV1TaskTypeRevokeOutcome `json:"outcome,omitempty"`
	OutcomeTime *time.Time                        `json:"outcomeTime,omitempty"`
	// The TaskRevokeSource message.
	//
	// This message contains a oneof named origin. Only a single field of the following list may be set at a time:
	//   - review
	//   - request
	//   - expired
	//   - nonUsage
	//
	Source *C1APITaskV1TaskRevokeSource `json:"source,omitempty"`
}
