// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskActionsServiceDenyRequestInput - The TaskActionsServiceDenyRequest message.
type C1APITaskV1TaskActionsServiceDenyRequestInput struct {
	// The comment field.
	Comment *string `json:"comment,omitempty"`
	//  Make sure to update the TicketExpandMask
	//
	ExpandMask *C1APITaskV1TaskExpandMask `json:"expandMask,omitempty"`
	// The policyStepId field.
	PolicyStepID *string `json:"policyStepId,omitempty"`
}
