// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// ApplicableType - The applicableType field.
type ApplicableType string

const (
	ApplicableTypeClassifierTypeUnspecified ApplicableType = "CLASSIFIER_TYPE_UNSPECIFIED"
	ApplicableTypeClassifierTypeAgent       ApplicableType = "CLASSIFIER_TYPE_AGENT"
	ApplicableTypeClassifierTypeGateway     ApplicableType = "CLASSIFIER_TYPE_GATEWAY"
)

func (e ApplicableType) ToPointer() *ApplicableType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ApplicableType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CLASSIFIER_TYPE_UNSPECIFIED", "CLASSIFIER_TYPE_AGENT", "CLASSIFIER_TYPE_GATEWAY":
			return true
		}
	}
	return false
}

// ClassifierDefaultOutcome - The defaultOutcome field.
type ClassifierDefaultOutcome string

const (
	ClassifierDefaultOutcomeAgentClassifierRuleOutcomeUnspecified ClassifierDefaultOutcome = "AGENT_CLASSIFIER_RULE_OUTCOME_UNSPECIFIED"
	ClassifierDefaultOutcomeAgentClassifierRuleOutcomeAllowed     ClassifierDefaultOutcome = "AGENT_CLASSIFIER_RULE_OUTCOME_ALLOWED"
	ClassifierDefaultOutcomeAgentClassifierRuleOutcomeDenied      ClassifierDefaultOutcome = "AGENT_CLASSIFIER_RULE_OUTCOME_DENIED"
)

func (e ClassifierDefaultOutcome) ToPointer() *ClassifierDefaultOutcome {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClassifierDefaultOutcome) IsExact() bool {
	if e != nil {
		switch *e {
		case "AGENT_CLASSIFIER_RULE_OUTCOME_UNSPECIFIED", "AGENT_CLASSIFIER_RULE_OUTCOME_ALLOWED", "AGENT_CLASSIFIER_RULE_OUTCOME_DENIED":
			return true
		}
	}
	return false
}

// ManagedBy - The managedBy field.
type ManagedBy string

const (
	ManagedByManagedByUnspecified ManagedBy = "MANAGED_BY_UNSPECIFIED"
	ManagedByManagedByTenant      ManagedBy = "MANAGED_BY_TENANT"
	ManagedByManagedBySystem      ManagedBy = "MANAGED_BY_SYSTEM"
)

func (e ManagedBy) ToPointer() *ManagedBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ManagedBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "MANAGED_BY_UNSPECIFIED", "MANAGED_BY_TENANT", "MANAGED_BY_SYSTEM":
			return true
		}
	}
	return false
}

// Classifier is a named, reusable rule cascade.
type Classifier struct {
	// The applicableType field.
	ApplicableType *ApplicableType `json:"applicableType,omitempty"`
	CreatedAt      *time.Time      `json:"createdAt,omitempty"`
	// The defaultDenyReason field.
	DefaultDenyReason *string `json:"defaultDenyReason,omitempty"`
	// The defaultOutcome field.
	DefaultOutcome *ClassifierDefaultOutcome `json:"defaultOutcome,omitempty"`
	DeletedAt      *time.Time                `json:"deletedAt,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	// The displayName field.
	DisplayName string `json:"displayName"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// The managedBy field.
	ManagedBy *ManagedBy `json:"managedBy,omitempty"`
	// The rules field.
	Rules       []AgentClassifierRule `json:"rules,omitempty"`
	TemplateRef *TemplateRef          `json:"templateRef,omitempty"`
	// The tenantId field.
	TenantID  *string    `json:"tenantId,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (c Classifier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Classifier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Classifier) GetApplicableType() *ApplicableType {
	if c == nil {
		return nil
	}
	return c.ApplicableType
}

func (c *Classifier) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Classifier) GetDefaultDenyReason() *string {
	if c == nil {
		return nil
	}
	return c.DefaultDenyReason
}

func (c *Classifier) GetDefaultOutcome() *ClassifierDefaultOutcome {
	if c == nil {
		return nil
	}
	return c.DefaultOutcome
}

func (c *Classifier) GetDeletedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.DeletedAt
}

func (c *Classifier) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *Classifier) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *Classifier) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *Classifier) GetManagedBy() *ManagedBy {
	if c == nil {
		return nil
	}
	return c.ManagedBy
}

func (c *Classifier) GetRules() []AgentClassifierRule {
	if c == nil {
		return nil
	}
	return c.Rules
}

func (c *Classifier) GetTemplateRef() *TemplateRef {
	if c == nil {
		return nil
	}
	return c.TemplateRef
}

func (c *Classifier) GetTenantID() *string {
	if c == nil {
		return nil
	}
	return c.TenantID
}

func (c *Classifier) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}
