// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateAutomationResponse1 - The CreateAutomationResponse message.
type CreateAutomationResponse1 struct {
	// The Automation message.
	//
	// This message contains a oneof named disabled_reason. Only a single field of the following list may be set at a time:
	//   - circuitBreaker
	//
	Automation *Automation `json:"automation,omitempty"`
	// If we create a new trigger with an HMAC secret we return the HMAC on this field
	WebhookHmacSecret *string `json:"webhookHmacSecret,omitempty"`
}

func (c *CreateAutomationResponse1) GetAutomation() *Automation {
	if c == nil {
		return nil
	}
	return c.Automation
}

func (c *CreateAutomationResponse1) GetWebhookHmacSecret() *string {
	if c == nil {
		return nil
	}
	return c.WebhookHmacSecret
}
