// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// AuthorityKind - Type of configuration that supplied the denying limit.
type AuthorityKind string

const (
	AuthorityKindAuthorityKindUnspecified        AuthorityKind = "AUTHORITY_KIND_UNSPECIFIED"
	AuthorityKindAuthorityKindFundPolicy         AuthorityKind = "AUTHORITY_KIND_FUND_POLICY"
	AuthorityKindAuthorityKindFundAssignment     AuthorityKind = "AUTHORITY_KIND_FUND_ASSIGNMENT"
	AuthorityKindAuthorityKindFundRule           AuthorityKind = "AUTHORITY_KIND_FUND_RULE"
	AuthorityKindAuthorityKindTenantAppCap       AuthorityKind = "AUTHORITY_KIND_TENANT_APP_CAP"
	AuthorityKindAuthorityKindSubjectAppLimit    AuthorityKind = "AUTHORITY_KIND_SUBJECT_APP_LIMIT"
	AuthorityKindAuthorityKindEntitlementBinding AuthorityKind = "AUTHORITY_KIND_ENTITLEMENT_BINDING"
	AuthorityKindAuthorityKindAppUser            AuthorityKind = "AUTHORITY_KIND_APP_USER"
	AuthorityKindAuthorityKindUser               AuthorityKind = "AUTHORITY_KIND_USER"
)

func (e AuthorityKind) ToPointer() *AuthorityKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthorityKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTHORITY_KIND_UNSPECIFIED", "AUTHORITY_KIND_FUND_POLICY", "AUTHORITY_KIND_FUND_ASSIGNMENT", "AUTHORITY_KIND_FUND_RULE", "AUTHORITY_KIND_TENANT_APP_CAP", "AUTHORITY_KIND_SUBJECT_APP_LIMIT", "AUTHORITY_KIND_ENTITLEMENT_BINDING", "AUTHORITY_KIND_APP_USER", "AUTHORITY_KIND_USER":
			return true
		}
	}
	return false
}

// PeriodKind - Length of the denied budget period.
type PeriodKind string

const (
	PeriodKindPeriodKindUnspecified PeriodKind = "PERIOD_KIND_UNSPECIFIED"
	PeriodKindPeriodKindDaily       PeriodKind = "PERIOD_KIND_DAILY"
	PeriodKindPeriodKindWeekly      PeriodKind = "PERIOD_KIND_WEEKLY"
	PeriodKindPeriodKindMonthly     PeriodKind = "PERIOD_KIND_MONTHLY"
	PeriodKindPeriodKindQuarterly   PeriodKind = "PERIOD_KIND_QUARTERLY"
	PeriodKindPeriodKindYearly      PeriodKind = "PERIOD_KIND_YEARLY"
)

func (e PeriodKind) ToPointer() *PeriodKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PeriodKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "PERIOD_KIND_UNSPECIFIED", "PERIOD_KIND_DAILY", "PERIOD_KIND_WEEKLY", "PERIOD_KIND_MONTHLY", "PERIOD_KIND_QUARTERLY", "PERIOD_KIND_YEARLY":
			return true
		}
	}
	return false
}

// DenialEpisodeReason - Reason the calls were denied.
type DenialEpisodeReason string

const (
	DenialEpisodeReasonSpendDenyReasonUnspecified      DenialEpisodeReason = "SPEND_DENY_REASON_UNSPECIFIED"
	DenialEpisodeReasonSpendDenyReasonTenantFrozen     DenialEpisodeReason = "SPEND_DENY_REASON_TENANT_FROZEN"
	DenialEpisodeReasonSpendDenyReasonSuspendedByAdmin DenialEpisodeReason = "SPEND_DENY_REASON_SUSPENDED_BY_ADMIN"
	DenialEpisodeReasonSpendDenyReasonAppSuspended     DenialEpisodeReason = "SPEND_DENY_REASON_APP_SUSPENDED"
	DenialEpisodeReasonSpendDenyReasonAppPausedByYou   DenialEpisodeReason = "SPEND_DENY_REASON_APP_PAUSED_BY_YOU"
	DenialEpisodeReasonSpendDenyReasonNoSupply         DenialEpisodeReason = "SPEND_DENY_REASON_NO_SUPPLY"
)

func (e DenialEpisodeReason) ToPointer() *DenialEpisodeReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialEpisodeReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_DENY_REASON_UNSPECIFIED", "SPEND_DENY_REASON_TENANT_FROZEN", "SPEND_DENY_REASON_SUSPENDED_BY_ADMIN", "SPEND_DENY_REASON_APP_SUSPENDED", "SPEND_DENY_REASON_APP_PAUSED_BY_YOU", "SPEND_DENY_REASON_NO_SUPPLY":
			return true
		}
	}
	return false
}

// RequestTaskState - Current state of the associated access request task.
type RequestTaskState string

const (
	RequestTaskStateTaskStateUnspecified RequestTaskState = "TASK_STATE_UNSPECIFIED"
	RequestTaskStateTaskStateOpen        RequestTaskState = "TASK_STATE_OPEN"
	RequestTaskStateTaskStateClosed      RequestTaskState = "TASK_STATE_CLOSED"
)

func (e RequestTaskState) ToPointer() *RequestTaskState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RequestTaskState) IsExact() bool {
	if e != nil {
		switch *e {
		case "TASK_STATE_UNSPECIFIED", "TASK_STATE_OPEN", "TASK_STATE_CLOSED":
			return true
		}
	}
	return false
}

// ScopeKind - Budget scope that denied the calls.
type ScopeKind string

const (
	ScopeKindSpendScopeKindUnspecified ScopeKind = "SPEND_SCOPE_KIND_UNSPECIFIED"
	ScopeKindSpendScopeKindTenant      ScopeKind = "SPEND_SCOPE_KIND_TENANT"
	ScopeKindSpendScopeKindSubject     ScopeKind = "SPEND_SCOPE_KIND_SUBJECT"
	ScopeKindSpendScopeKindApp         ScopeKind = "SPEND_SCOPE_KIND_APP"
	ScopeKindSpendScopeKindSubjectApp  ScopeKind = "SPEND_SCOPE_KIND_SUBJECT_APP"
)

func (e ScopeKind) ToPointer() *ScopeKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ScopeKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_SCOPE_KIND_UNSPECIFIED", "SPEND_SCOPE_KIND_TENANT", "SPEND_SCOPE_KIND_SUBJECT", "SPEND_SCOPE_KIND_APP", "SPEND_SCOPE_KIND_SUBJECT_APP":
			return true
		}
	}
	return false
}

// DenialEpisodeState - Whether this denial episode remains open.
type DenialEpisodeState string

const (
	DenialEpisodeStateSpendBlockStateUnspecified DenialEpisodeState = "SPEND_BLOCK_STATE_UNSPECIFIED"
	DenialEpisodeStateSpendBlockStateOpen        DenialEpisodeState = "SPEND_BLOCK_STATE_OPEN"
	DenialEpisodeStateSpendBlockStateClosed      DenialEpisodeState = "SPEND_BLOCK_STATE_CLOSED"
)

func (e DenialEpisodeState) ToPointer() *DenialEpisodeState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialEpisodeState) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_BLOCK_STATE_UNSPECIFIED", "SPEND_BLOCK_STATE_OPEN", "SPEND_BLOCK_STATE_CLOSED":
			return true
		}
	}
	return false
}

// DenialEpisode represents repeated budget refusals for one scope and budget period.
type DenialEpisode struct {
	// Best-effort lower bound for refused calls in this episode. Concurrent
	//  retry exhaustion can under-report; denial_events is exact for a window.
	AttemptCount *int64 `integer:"string" json:"attemptCount,omitempty"`
	// Identifier of the configuration that supplied the denying limit.
	AuthorityID *string `json:"authorityId,omitempty"`
	// Type of configuration that supplied the denying limit.
	AuthorityKind *AuthorityKind `json:"authorityKind,omitempty"`
	// Version of the configuration used for the first refusal.
	AuthorityVersion *int64 `integer:"string" json:"authorityVersion,omitempty"`
	// Unique identifier for this denial episode.
	BlockID *string `json:"blockId,omitempty"`
	// Stable identifier for the budget account that denied the calls.
	BudgetKey     *string    `json:"budgetKey,omitempty"`
	ClosedAt      *time.Time `json:"closedAt,omitempty"`
	FirstDeniedAt *time.Time `json:"firstDeniedAt,omitempty"`
	LastDeniedAt  *time.Time `json:"lastDeniedAt,omitempty"`
	PeriodEnd     *time.Time `json:"periodEnd,omitempty"`
	// Stable key for the denied budget period.
	PeriodKey *string `json:"periodKey,omitempty"`
	// Length of the denied budget period.
	PeriodKind  *PeriodKind `json:"periodKind,omitempty"`
	PeriodStart *time.Time  `json:"periodStart,omitempty"`
	// Reason the calls were denied.
	Reason *DenialEpisodeReason `json:"reason,omitempty"`
	// ID of the access request task associated with this episode.
	RequestTaskID *string `json:"requestTaskId,omitempty"`
	// Current state of the associated access request task.
	RequestTaskState *RequestTaskState `json:"requestTaskState,omitempty"`
	// Application ID for application-scoped episodes.
	ScopeAppID *string `json:"scopeAppId,omitempty"`
	// Budget scope that denied the calls.
	ScopeKind *ScopeKind `json:"scopeKind,omitempty"`
	// User ID for user-scoped episodes.
	ScopeUserID *string `json:"scopeUserId,omitempty"`
	// Whether this denial episode remains open.
	State *DenialEpisodeState `json:"state,omitempty"`
}

func (d DenialEpisode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DenialEpisode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DenialEpisode) GetAttemptCount() *int64 {
	if d == nil {
		return nil
	}
	return d.AttemptCount
}

func (d *DenialEpisode) GetAuthorityID() *string {
	if d == nil {
		return nil
	}
	return d.AuthorityID
}

func (d *DenialEpisode) GetAuthorityKind() *AuthorityKind {
	if d == nil {
		return nil
	}
	return d.AuthorityKind
}

func (d *DenialEpisode) GetAuthorityVersion() *int64 {
	if d == nil {
		return nil
	}
	return d.AuthorityVersion
}

func (d *DenialEpisode) GetBlockID() *string {
	if d == nil {
		return nil
	}
	return d.BlockID
}

func (d *DenialEpisode) GetBudgetKey() *string {
	if d == nil {
		return nil
	}
	return d.BudgetKey
}

func (d *DenialEpisode) GetClosedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.ClosedAt
}

func (d *DenialEpisode) GetFirstDeniedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.FirstDeniedAt
}

func (d *DenialEpisode) GetLastDeniedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.LastDeniedAt
}

func (d *DenialEpisode) GetPeriodEnd() *time.Time {
	if d == nil {
		return nil
	}
	return d.PeriodEnd
}

func (d *DenialEpisode) GetPeriodKey() *string {
	if d == nil {
		return nil
	}
	return d.PeriodKey
}

func (d *DenialEpisode) GetPeriodKind() *PeriodKind {
	if d == nil {
		return nil
	}
	return d.PeriodKind
}

func (d *DenialEpisode) GetPeriodStart() *time.Time {
	if d == nil {
		return nil
	}
	return d.PeriodStart
}

func (d *DenialEpisode) GetReason() *DenialEpisodeReason {
	if d == nil {
		return nil
	}
	return d.Reason
}

func (d *DenialEpisode) GetRequestTaskID() *string {
	if d == nil {
		return nil
	}
	return d.RequestTaskID
}

func (d *DenialEpisode) GetRequestTaskState() *RequestTaskState {
	if d == nil {
		return nil
	}
	return d.RequestTaskState
}

func (d *DenialEpisode) GetScopeAppID() *string {
	if d == nil {
		return nil
	}
	return d.ScopeAppID
}

func (d *DenialEpisode) GetScopeKind() *ScopeKind {
	if d == nil {
		return nil
	}
	return d.ScopeKind
}

func (d *DenialEpisode) GetScopeUserID() *string {
	if d == nil {
		return nil
	}
	return d.ScopeUserID
}

func (d *DenialEpisode) GetState() *DenialEpisodeState {
	if d == nil {
		return nil
	}
	return d.State
}
