// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// The EdgeServiceGetEgressTrafficSummaryResponse message.
type EdgeServiceGetEgressTrafficSummaryResponse struct {
	// Distinct source_principal per source_principal_kind.
	AgentKindCounts []AgentKindCount `json:"agentKindCounts,omitempty"`
	// The allowedEvents field.
	AllowedEvents *string `json:"allowedEvents,omitempty"`
	// The deniedEvents field.
	DeniedEvents *string `json:"deniedEvents,omitempty"`
	// The distinctAgentCount field.
	DistinctAgentCount *string `json:"distinctAgentCount,omitempty"`
	// uniqExact(dest_host) over the window, excluding empty dest_host.
	DistinctDestinationCount *int64 `integer:"string" json:"distinctDestinationCount,omitempty"`
	// The distinctToolCount field.
	DistinctToolCount *string `json:"distinctToolCount,omitempty"`
	// Distinct source_principal with at least one row whose verdict resolved
	//  via the fail-closed default rather than an explicit policy match --
	//  the "policy coverage" KPI: agents Edge saw but has no rule for yet.
	FallbackAgentCount *int64 `integer:"string" json:"fallbackAgentCount,omitempty"`
	// The series field.
	Series []TBTrafficSummaryBucket `json:"series,omitempty"`
	// The totalEvents field.
	TotalEvents *string `json:"totalEvents,omitempty"`
	// The totalRequestBytes field.
	TotalRequestBytes *string `json:"totalRequestBytes,omitempty"`
	// The totalResponseBytes field.
	TotalResponseBytes *string `json:"totalResponseBytes,omitempty"`
	// The unspecifiedEvents field.
	UnspecifiedEvents *string `json:"unspecifiedEvents,omitempty"`
}

func (e EdgeServiceGetEgressTrafficSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetAgentKindCounts() []AgentKindCount {
	if e == nil {
		return nil
	}
	return e.AgentKindCounts
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetAllowedEvents() *string {
	if e == nil {
		return nil
	}
	return e.AllowedEvents
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetDeniedEvents() *string {
	if e == nil {
		return nil
	}
	return e.DeniedEvents
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetDistinctAgentCount() *string {
	if e == nil {
		return nil
	}
	return e.DistinctAgentCount
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetDistinctDestinationCount() *int64 {
	if e == nil {
		return nil
	}
	return e.DistinctDestinationCount
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetDistinctToolCount() *string {
	if e == nil {
		return nil
	}
	return e.DistinctToolCount
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetFallbackAgentCount() *int64 {
	if e == nil {
		return nil
	}
	return e.FallbackAgentCount
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetSeries() []TBTrafficSummaryBucket {
	if e == nil {
		return nil
	}
	return e.Series
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetTotalEvents() *string {
	if e == nil {
		return nil
	}
	return e.TotalEvents
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetTotalRequestBytes() *string {
	if e == nil {
		return nil
	}
	return e.TotalRequestBytes
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetTotalResponseBytes() *string {
	if e == nil {
		return nil
	}
	return e.TotalResponseBytes
}

func (e *EdgeServiceGetEgressTrafficSummaryResponse) GetUnspecifiedEvents() *string {
	if e == nil {
		return nil
	}
	return e.UnspecifiedEvents
}
