// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The EdgeServiceListEgressRuleEntitlementIssuesResponse message.
type EdgeServiceListEgressRuleEntitlementIssuesResponse struct {
	// One entry per saved Allow or Deny rule whose entitlement does not
	//  resolve, in rule order. Rules naming more distinct entitlements than the
	//  evaluation cap are not checked past it.
	Issues []EdgeEgressRuleEntitlementIssue `json:"issues,omitempty"`
}

func (e *EdgeServiceListEgressRuleEntitlementIssuesResponse) GetIssues() []EdgeEgressRuleEntitlementIssue {
	if e == nil {
		return nil
	}
	return e.Issues
}
