// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeInferenceRegistryModel is a model C1 has registered for use.
type EdgeInferenceRegistryModel struct {
	// Zero when unknown.
	ContextWindowTokens *int64 `json:"contextWindowTokens,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// Registry model id, written to EdgeInferenceRoute.registry_model_id.
	ModelID *string `json:"modelId,omitempty"`
	// Suggested route id: the model's name in route id form.
	RouteID *string `json:"routeId,omitempty"`
	// Ways to serve the model, in C1's preferred order.
	ServeOptions []EdgeInferenceServeOption `json:"serveOptions,omitempty"`
}

func (e *EdgeInferenceRegistryModel) GetContextWindowTokens() *int64 {
	if e == nil {
		return nil
	}
	return e.ContextWindowTokens
}

func (e *EdgeInferenceRegistryModel) GetDisplayName() *string {
	if e == nil {
		return nil
	}
	return e.DisplayName
}

func (e *EdgeInferenceRegistryModel) GetModelID() *string {
	if e == nil {
		return nil
	}
	return e.ModelID
}

func (e *EdgeInferenceRegistryModel) GetRouteID() *string {
	if e == nil {
		return nil
	}
	return e.RouteID
}

func (e *EdgeInferenceRegistryModel) GetServeOptions() []EdgeInferenceServeOption {
	if e == nil {
		return nil
	}
	return e.ServeOptions
}
