// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FollowedTier - C1 tier this route follows; UNSPECIFIED means it follows no tier. On write, a route that sets a tier must
//
//	use the route_id c1-<tier>; the server replaces its targets and selection with the tier's current model,
//	served through the providers this Edge already has credentials for, and also publishes that model's name
//	as a second route. Clearing the tier (and publication) on a published route pins it to its current
//	targets.
type FollowedTier string

const (
	FollowedTierEdgeInferenceTierUnspecified FollowedTier = "EDGE_INFERENCE_TIER_UNSPECIFIED"
	FollowedTierEdgeInferenceTierFast        FollowedTier = "EDGE_INFERENCE_TIER_FAST"
	FollowedTierEdgeInferenceTierBalanced    FollowedTier = "EDGE_INFERENCE_TIER_BALANCED"
	FollowedTierEdgeInferenceTierBest        FollowedTier = "EDGE_INFERENCE_TIER_BEST"
)

func (e FollowedTier) ToPointer() *FollowedTier {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FollowedTier) IsExact() bool {
	if e != nil {
		switch *e {
		case "EDGE_INFERENCE_TIER_UNSPECIFIED", "EDGE_INFERENCE_TIER_FAST", "EDGE_INFERENCE_TIER_BALANCED", "EDGE_INFERENCE_TIER_BEST":
			return true
		}
	}
	return false
}

// EdgeInferenceRouteNativeFormat - Accepted native client request format; never inferred from caller headers.
type EdgeInferenceRouteNativeFormat string

const (
	EdgeInferenceRouteNativeFormatEdgeInferenceNativeFormatUnspecified       EdgeInferenceRouteNativeFormat = "EDGE_INFERENCE_NATIVE_FORMAT_UNSPECIFIED"
	EdgeInferenceRouteNativeFormatEdgeInferenceNativeFormatOpenaiResponses   EdgeInferenceRouteNativeFormat = "EDGE_INFERENCE_NATIVE_FORMAT_OPENAI_RESPONSES"
	EdgeInferenceRouteNativeFormatEdgeInferenceNativeFormatOpenaiChat        EdgeInferenceRouteNativeFormat = "EDGE_INFERENCE_NATIVE_FORMAT_OPENAI_CHAT"
	EdgeInferenceRouteNativeFormatEdgeInferenceNativeFormatAnthropicMessages EdgeInferenceRouteNativeFormat = "EDGE_INFERENCE_NATIVE_FORMAT_ANTHROPIC_MESSAGES"
)

func (e EdgeInferenceRouteNativeFormat) ToPointer() *EdgeInferenceRouteNativeFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EdgeInferenceRouteNativeFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "EDGE_INFERENCE_NATIVE_FORMAT_UNSPECIFIED", "EDGE_INFERENCE_NATIVE_FORMAT_OPENAI_RESPONSES", "EDGE_INFERENCE_NATIVE_FORMAT_OPENAI_CHAT", "EDGE_INFERENCE_NATIVE_FORMAT_ANTHROPIC_MESSAGES":
			return true
		}
	}
	return false
}

// Publication - Which C1-published route of a followed tier this is. Set by the server; send back the value you read.
//
//	UNSPECIFIED for a tenant-authored route.
type Publication string

const (
	PublicationEdgeInferenceRoutePublicationUnspecified Publication = "EDGE_INFERENCE_ROUTE_PUBLICATION_UNSPECIFIED"
	PublicationEdgeInferenceRoutePublicationTier        Publication = "EDGE_INFERENCE_ROUTE_PUBLICATION_TIER"
	PublicationEdgeInferenceRoutePublicationModelAlias  Publication = "EDGE_INFERENCE_ROUTE_PUBLICATION_MODEL_ALIAS"
)

func (e Publication) ToPointer() *Publication {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Publication) IsExact() bool {
	if e != nil {
		switch *e {
		case "EDGE_INFERENCE_ROUTE_PUBLICATION_UNSPECIFIED", "EDGE_INFERENCE_ROUTE_PUBLICATION_TIER", "EDGE_INFERENCE_ROUTE_PUBLICATION_MODEL_ALIAS":
			return true
		}
	}
	return false
}

// EdgeInferenceRoute declares a caller-visible model selector and a bounded
//
//	provider graph. Legacy scalar fields decode previously stored singletons;
//	new configurations use native_format, targets, and selection.
type EdgeInferenceRoute struct {
	// Explicitly authorize enabled human users holding per-capability app grants
	//  to exchange an SSO id_token with DPoP. False preserves workload-only routes.
	AllowHumanCallers *bool `json:"allowHumanCallers,omitempty"`
	// Required in workload mode; forbidden when allow_human_callers is true.
	//  Workload callers must hold both inference capability grants.
	CallerServicePrincipalID *string `json:"callerServicePrincipalId,omitempty"`
	// The workload caller's exact federation trust; forbidden in human mode.
	CallerWorkloadFederationTrustID *string `json:"callerWorkloadFederationTrustId,omitempty"`
	// The contentType field.
	ContentType *string `json:"contentType,omitempty"`
	// Deprecated setup-time pin. New writes must leave it empty; the runtime
	//  resolves the active version of each target's Vault secret.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ExpectedSecretVersion *string `json:"expectedSecretVersion,omitempty"`
	// C1 tier this route follows; UNSPECIFIED means it follows no tier. On write, a route that sets a tier must
	//  use the route_id c1-<tier>; the server replaces its targets and selection with the tier's current model,
	//  served through the providers this Edge already has credentials for, and also publishes that model's name
	//  as a second route. Clearing the tier (and publication) on a published route pins it to its current
	//  targets.
	FollowedTier *FollowedTier `json:"followedTier,omitempty"`
	// Accepted native client request format; never inferred from caller headers.
	NativeFormat *EdgeInferenceRouteNativeFormat `json:"nativeFormat,omitempty"`
	// Which C1-published route of a followed tier this is. Set by the server; send back the value you read.
	//  UNSPECIFIED for a tenant-authored route.
	Publication *Publication `json:"publication,omitempty"`
	// Registry model the route was built from; empty for a custom model.
	RegistryModelID *string `json:"registryModelId,omitempty"`
	// Tenant-owned route identifier, unique within the tenant. ListInferenceRoutes
	//  reports routes already configured for this application, not an allowlist.
	RouteID *string `json:"routeId,omitempty"`
	// The secretId field.
	SecretID  *string                 `json:"secretId,omitempty"`
	Selection *EdgeInferenceSelection `json:"selection,omitempty"`
	// Explicit upstream targets; no request may choose a target or destination.
	Targets []EdgeInferenceTarget `json:"targets,omitempty"`
	// Legacy singleton model, empty for graph routes.
	UpstreamModelID *string `json:"upstreamModelId,omitempty"`
	// Legacy singleton Vault reference, empty for graph routes.
	VaultBoundaryID *string `json:"vaultBoundaryId,omitempty"`
}

func (e *EdgeInferenceRoute) GetAllowHumanCallers() *bool {
	if e == nil {
		return nil
	}
	return e.AllowHumanCallers
}

func (e *EdgeInferenceRoute) GetCallerServicePrincipalID() *string {
	if e == nil {
		return nil
	}
	return e.CallerServicePrincipalID
}

func (e *EdgeInferenceRoute) GetCallerWorkloadFederationTrustID() *string {
	if e == nil {
		return nil
	}
	return e.CallerWorkloadFederationTrustID
}

func (e *EdgeInferenceRoute) GetContentType() *string {
	if e == nil {
		return nil
	}
	return e.ContentType
}

func (e *EdgeInferenceRoute) GetExpectedSecretVersion() *string {
	if e == nil {
		return nil
	}
	return e.ExpectedSecretVersion
}

func (e *EdgeInferenceRoute) GetFollowedTier() *FollowedTier {
	if e == nil {
		return nil
	}
	return e.FollowedTier
}

func (e *EdgeInferenceRoute) GetNativeFormat() *EdgeInferenceRouteNativeFormat {
	if e == nil {
		return nil
	}
	return e.NativeFormat
}

func (e *EdgeInferenceRoute) GetPublication() *Publication {
	if e == nil {
		return nil
	}
	return e.Publication
}

func (e *EdgeInferenceRoute) GetRegistryModelID() *string {
	if e == nil {
		return nil
	}
	return e.RegistryModelID
}

func (e *EdgeInferenceRoute) GetRouteID() *string {
	if e == nil {
		return nil
	}
	return e.RouteID
}

func (e *EdgeInferenceRoute) GetSecretID() *string {
	if e == nil {
		return nil
	}
	return e.SecretID
}

func (e *EdgeInferenceRoute) GetSelection() *EdgeInferenceSelection {
	if e == nil {
		return nil
	}
	return e.Selection
}

func (e *EdgeInferenceRoute) GetTargets() []EdgeInferenceTarget {
	if e == nil {
		return nil
	}
	return e.Targets
}

func (e *EdgeInferenceRoute) GetUpstreamModelID() *string {
	if e == nil {
		return nil
	}
	return e.UpstreamModelID
}

func (e *EdgeInferenceRoute) GetVaultBoundaryID() *string {
	if e == nil {
		return nil
	}
	return e.VaultBoundaryID
}
