// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// The EdgeServiceListEgressTopDestinationsResponse message.
type EdgeServiceListEgressTopDestinationsResponse struct {
	// Ordered by call_count descending, limited to limit. No pagination
	//  cursor -- this is a fixed top-N, not a full list.
	Destinations []TBTopDestination `json:"destinations,omitempty"`
	// uniqExact(dest_host) over the whole window, unaffected by any request
	//  filter -- lets the UI show "top N of distinct_destination_count
	//  destinations".
	DistinctDestinationCount *int64 `integer:"string" json:"distinctDestinationCount,omitempty"`
	// Count of destinations matching the request's filters (host_contains,
	//  verdict, principal_kind, blocked_only), independent of limit/offset --
	//  the paging total for the Dense table.
	MatchingDestinationCount *int64 `integer:"string" json:"matchingDestinationCount,omitempty"`
}

func (e EdgeServiceListEgressTopDestinationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EdgeServiceListEgressTopDestinationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EdgeServiceListEgressTopDestinationsResponse) GetDestinations() []TBTopDestination {
	if e == nil {
		return nil
	}
	return e.Destinations
}

func (e *EdgeServiceListEgressTopDestinationsResponse) GetDistinctDestinationCount() *int64 {
	if e == nil {
		return nil
	}
	return e.DistinctDestinationCount
}

func (e *EdgeServiceListEgressTopDestinationsResponse) GetMatchingDestinationCount() *int64 {
	if e == nil {
		return nil
	}
	return e.MatchingDestinationCount
}
