// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeEgressRuleListCheck is Update's save-time verdict on a rule list.
type EdgeEgressRuleListCheck struct {
	// Every problem Update would reject the list for, in rule order; empty when
	//  valid. Update itself reports only the first.
	Problems []EdgeEgressRuleProblem `json:"problems,omitempty"`
	// The valid field.
	Valid *bool `json:"valid,omitempty"`
	// Things worth fixing that do not stop Update from saving the list.
	Warnings []EdgeEgressRuleWarning `json:"warnings,omitempty"`
}

func (e *EdgeEgressRuleListCheck) GetProblems() []EdgeEgressRuleProblem {
	if e == nil {
		return nil
	}
	return e.Problems
}

func (e *EdgeEgressRuleListCheck) GetValid() *bool {
	if e == nil {
		return nil
	}
	return e.Valid
}

func (e *EdgeEgressRuleListCheck) GetWarnings() []EdgeEgressRuleWarning {
	if e == nil {
		return nil
	}
	return e.Warnings
}
