// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// EdgeMode - Global e-stop for the connection-routing configuration. DISABLED (and
//
//	UNSPECIFIED) denies every capability; OBSERVE evaluates policy but serves
//	the request, recording what ENFORCE would have answered; ENFORCE serves
//	the policy decision.
type EdgeMode string

const (
	EdgeModeEdgeModeUnspecified EdgeMode = "EDGE_MODE_UNSPECIFIED"
	EdgeModeEdgeModeDisabled    EdgeMode = "EDGE_MODE_DISABLED"
	EdgeModeEdgeModeObserve     EdgeMode = "EDGE_MODE_OBSERVE"
	EdgeModeEdgeModeEnforce     EdgeMode = "EDGE_MODE_ENFORCE"
)

func (e EdgeMode) ToPointer() *EdgeMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EdgeMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "EDGE_MODE_UNSPECIFIED", "EDGE_MODE_DISABLED", "EDGE_MODE_OBSERVE", "EDGE_MODE_ENFORCE":
			return true
		}
	}
	return false
}

// Edge is one App-owned connection-routing configuration. It is the
//
//	capability-neutral root for egress today and future LLM routing /
//	credential-injection features; capability-specific config lands additively.
type Edge struct {
	// App identifier.
	AppID *string `json:"appId,omitempty"`
	// Overrides the ID-JAG `client_id` this Edge asserts, keyed by the
	//  authenticating client's own id, valued by the id it should assert
	//  instead. A client with no entry keeps the default: its own id,
	//  verbatim. Not format-constrained -- a resource server that requires a
	//  particular shape (e.g. an absolute https URL) enforces that itself.
	AudienceClientIds map[string]string `json:"audienceClientIds,omitempty"`
	CreatedAt         *time.Time        `json:"createdAt,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// The minted egress.connect entitlement (derived from the Edge id) -- grant
	//  it to a caller to let it open an authenticated egress connection.
	EgressConnectEntitlementID *string `json:"egressConnectEntitlementId,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// Global e-stop for the connection-routing configuration. DISABLED (and
	//  UNSPECIFIED) denies every capability; OBSERVE evaluates policy but serves
	//  the request, recording what ENFORCE would have answered; ENFORCE serves
	//  the policy decision.
	Mode *EdgeMode `json:"mode,omitempty"`
	// The `audience` to send when exchanging a token for access to this Edge.
	//  Every Edge deployment in the tenant shares it, so it names the service;
	//  `token_resource` names this Edge.
	TokenAudience *string `json:"tokenAudience,omitempty"`
	// The `resource` to send alongside `token_audience`. It pins the exchange to
	//  this Edge, and the issued grant echoes it back, so send it exactly as
	//  given.
	TokenResource *string `json:"tokenResource,omitempty"`
	// The scopes this Edge can issue. An exchange receives the ones it requests
	//  that the caller also holds the matching capability entitlement for.
	TokenScopes []string   `json:"tokenScopes,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

func (e Edge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Edge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Edge) GetAppID() *string {
	if e == nil {
		return nil
	}
	return e.AppID
}

func (e *Edge) GetAudienceClientIds() map[string]string {
	if e == nil {
		return nil
	}
	return e.AudienceClientIds
}

func (e *Edge) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *Edge) GetDisplayName() *string {
	if e == nil {
		return nil
	}
	return e.DisplayName
}

func (e *Edge) GetEgressConnectEntitlementID() *string {
	if e == nil {
		return nil
	}
	return e.EgressConnectEntitlementID
}

func (e *Edge) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Edge) GetMode() *EdgeMode {
	if e == nil {
		return nil
	}
	return e.Mode
}

func (e *Edge) GetTokenAudience() *string {
	if e == nil {
		return nil
	}
	return e.TokenAudience
}

func (e *Edge) GetTokenResource() *string {
	if e == nil {
		return nil
	}
	return e.TokenResource
}

func (e *Edge) GetTokenScopes() []string {
	if e == nil {
		return nil
	}
	return e.TokenScopes
}

func (e *Edge) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}
