// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeInferenceRetry - Bounds the delay between provider attempts on one route. Only transient
//
//	provider failures (rate limit, provider timeout, overload, a pre-response
//	transport failure, a generic upstream error) ever wait; credential, policy,
//	configuration and other 4xx rejections stay terminal.
type EdgeInferenceRetry struct {
	// First backoff ceiling in milliseconds; doubles per consecutive transient
	//  failure in one provider traversal, up to the cap. Zero disables backoff.
	BaseMs *int64 `json:"baseMs,omitempty"`
	// Largest delay in milliseconds, including a clamped provider Retry-After.
	CapMs *int64 `json:"capMs,omitempty"`
	// Draw each delay uniformly from zero to the ceiling instead of waiting the
	//  ceiling exactly.
	Jitter *bool `json:"jitter,omitempty"`
	// Extra attempts against the same target after a transient failure, before
	//  failing over. Each one spends one of the route's attempts.
	MaxSameTargetRetries *int64 `json:"maxSameTargetRetries,omitempty"`
}

func (e *EdgeInferenceRetry) GetBaseMs() *int64 {
	if e == nil {
		return nil
	}
	return e.BaseMs
}

func (e *EdgeInferenceRetry) GetCapMs() *int64 {
	if e == nil {
		return nil
	}
	return e.CapMs
}

func (e *EdgeInferenceRetry) GetJitter() *bool {
	if e == nil {
		return nil
	}
	return e.Jitter
}

func (e *EdgeInferenceRetry) GetMaxSameTargetRetries() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxSameTargetRetries
}
