// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeServiceListInferenceRoutesResponse contains safe route selection
//
//	metadata for an application.
type EdgeServiceListInferenceRoutesResponse struct {
	// The routes field.
	Routes []EdgeInferenceRouteOption `json:"routes,omitempty"`
}

func (e *EdgeServiceListInferenceRoutesResponse) GetRoutes() []EdgeInferenceRouteOption {
	if e == nil {
		return nil
	}
	return e.Routes
}
