// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeInferenceModelFamily groups registered models, e.g. "Claude Opus".
type EdgeInferenceModelFamily struct {
	// Family name; models with no family are grouped under their own display name.
	Family *string `json:"family,omitempty"`
	// The models field.
	Models []EdgeInferenceRegistryModel `json:"models,omitempty"`
}

func (e *EdgeInferenceModelFamily) GetFamily() *string {
	if e == nil {
		return nil
	}
	return e.Family
}

func (e *EdgeInferenceModelFamily) GetModels() []EdgeInferenceRegistryModel {
	if e == nil {
		return nil
	}
	return e.Models
}
