// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Category - The category field.
type Category string

const (
	CategoryEdgeFindingCategoryUnspecified     Category = "EDGE_FINDING_CATEGORY_UNSPECIFIED"
	CategoryEdgeFindingCategoryDestinationRisk Category = "EDGE_FINDING_CATEGORY_DESTINATION_RISK"
	CategoryEdgeFindingCategoryPolicyHealth    Category = "EDGE_FINDING_CATEGORY_POLICY_HEALTH"
	CategoryEdgeFindingCategoryDataVolume      Category = "EDGE_FINDING_CATEGORY_DATA_VOLUME"
	CategoryEdgeFindingCategoryIdentity        Category = "EDGE_FINDING_CATEGORY_IDENTITY"
	CategoryEdgeFindingCategoryAiUsage         Category = "EDGE_FINDING_CATEGORY_AI_USAGE"
	CategoryEdgeFindingCategoryTransport       Category = "EDGE_FINDING_CATEGORY_TRANSPORT"
	CategoryEdgeFindingCategoryBehavior        Category = "EDGE_FINDING_CATEGORY_BEHAVIOR"
	CategoryEdgeFindingCategoryEdgeHealth      Category = "EDGE_FINDING_CATEGORY_EDGE_HEALTH"
)

func (e Category) ToPointer() *Category {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Category) IsExact() bool {
	if e != nil {
		switch *e {
		case "EDGE_FINDING_CATEGORY_UNSPECIFIED", "EDGE_FINDING_CATEGORY_DESTINATION_RISK", "EDGE_FINDING_CATEGORY_POLICY_HEALTH", "EDGE_FINDING_CATEGORY_DATA_VOLUME", "EDGE_FINDING_CATEGORY_IDENTITY", "EDGE_FINDING_CATEGORY_AI_USAGE", "EDGE_FINDING_CATEGORY_TRANSPORT", "EDGE_FINDING_CATEGORY_BEHAVIOR", "EDGE_FINDING_CATEGORY_EDGE_HEALTH":
			return true
		}
	}
	return false
}

// EdgeFindingCategorySetting is one Edge finding category's resolved switch.
type EdgeFindingCategorySetting struct {
	// The category field.
	Category *Category `json:"category,omitempty"`
	// Whether rules in this category run.
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EdgeFindingCategorySetting) GetCategory() *Category {
	if e == nil {
		return nil
	}
	return e.Category
}

func (e *EdgeFindingCategorySetting) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}
