// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FunctionTypes string

const (
	FunctionTypesFunctionTypeUnspecified FunctionTypes = "FUNCTION_TYPE_UNSPECIFIED"
	FunctionTypesFunctionTypeAny         FunctionTypes = "FUNCTION_TYPE_ANY"
)

func (e FunctionTypes) ToPointer() *FunctionTypes {
	return &e
}

// The FunctionsSearchRequest message.
type FunctionsSearchRequest struct {
	// The functionTypes field.
	FunctionTypes []FunctionTypes `json:"functionTypes,omitempty"`
	// The pageSize field.
	PageSize *int `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// The query field.
	Query *string `json:"query,omitempty"`
}

func (f *FunctionsSearchRequest) GetFunctionTypes() []FunctionTypes {
	if f == nil {
		return nil
	}
	return f.FunctionTypes
}

func (f *FunctionsSearchRequest) GetPageSize() *int {
	if f == nil {
		return nil
	}
	return f.PageSize
}

func (f *FunctionsSearchRequest) GetPageToken() *string {
	if f == nil {
		return nil
	}
	return f.PageToken
}

func (f *FunctionsSearchRequest) GetQuery() *string {
	if f == nil {
		return nil
	}
	return f.Query
}
