// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// FundsMoney - Money is a non-negative monetary value used by spending controls.
type FundsMoney struct {
	// ISO 4217 currency code.
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// Fractional nano-units, from zero through 999999999.
	Nanos *int `json:"nanos,omitempty"`
	// Whole currency units. The bound keeps nano-unit conversion within int64.
	Units *int64 `integer:"string" json:"units,omitempty"`
}

func (f FundsMoney) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FundsMoney) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FundsMoney) GetCurrencyCode() *string {
	if f == nil {
		return nil
	}
	return f.CurrencyCode
}

func (f *FundsMoney) GetNanos() *int {
	if f == nil {
		return nil
	}
	return f.Nanos
}

func (f *FundsMoney) GetUnits() *int64 {
	if f == nil {
		return nil
	}
	return f.Units
}
