// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FundsSubjectScope - SubjectScope identifies one user's account.
type FundsSubjectScope struct {
	// User ID of the account owner.
	UserID *string `json:"userId,omitempty"`
}

func (f *FundsSubjectScope) GetUserID() *string {
	if f == nil {
		return nil
	}
	return f.UserID
}
