// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FundsSubjectAppScope - SubjectAppScope identifies one user's account for an application.
type FundsSubjectAppScope struct {
	// Application ID of the account.
	AppID *string `json:"appId,omitempty"`
	// User ID of the account owner.
	UserID *string `json:"userId,omitempty"`
}

func (f *FundsSubjectAppScope) GetAppID() *string {
	if f == nil {
		return nil
	}
	return f.AppID
}

func (f *FundsSubjectAppScope) GetUserID() *string {
	if f == nil {
		return nil
	}
	return f.UserID
}
