// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Outcome - The outcome field.
type Outcome string

const (
	OutcomeGoLinkResolveOutcomeUnspecified         Outcome = "GO_LINK_RESOLVE_OUTCOME_UNSPECIFIED"
	OutcomeGoLinkResolveOutcomeRedirect            Outcome = "GO_LINK_RESOLVE_OUTCOME_REDIRECT"
	OutcomeGoLinkResolveOutcomePrerequisiteMissing Outcome = "GO_LINK_RESOLVE_OUTCOME_PREREQUISITE_MISSING"
	OutcomeGoLinkResolveOutcomeChooser             Outcome = "GO_LINK_RESOLVE_OUTCOME_CHOOSER"
	OutcomeGoLinkResolveOutcomeAction              Outcome = "GO_LINK_RESOLVE_OUTCOME_ACTION"
	OutcomeGoLinkResolveOutcomeNotFound            Outcome = "GO_LINK_RESOLVE_OUTCOME_NOT_FOUND"
	OutcomeGoLinkResolveOutcomeDisabled            Outcome = "GO_LINK_RESOLVE_OUTCOME_DISABLED"
)

func (e Outcome) ToPointer() *Outcome {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Outcome) IsExact() bool {
	if e != nil {
		switch *e {
		case "GO_LINK_RESOLVE_OUTCOME_UNSPECIFIED", "GO_LINK_RESOLVE_OUTCOME_REDIRECT", "GO_LINK_RESOLVE_OUTCOME_PREREQUISITE_MISSING", "GO_LINK_RESOLVE_OUTCOME_CHOOSER", "GO_LINK_RESOLVE_OUTCOME_ACTION", "GO_LINK_RESOLVE_OUTCOME_NOT_FOUND", "GO_LINK_RESOLVE_OUTCOME_DISABLED":
			return true
		}
	}
	return false
}

// The GoLinkServiceResolveResponse message.
type GoLinkServiceResolveResponse struct {
	// Set when outcome is ACTION. The action ID to trigger.
	ActionID *string `json:"actionId,omitempty"`
	// Set when outcome is CHOOSER. The chooser options to present to the user.
	ChooserOptions []GoLinkChooserOptionInput `json:"chooserOptions,omitempty"`
	Golink         *GoLink                    `json:"golink,omitempty"`
	// The outcome field.
	Outcome      *Outcome            `json:"outcome,omitempty"`
	Prerequisite *GoLinkPrerequisite `json:"prerequisite,omitempty"`
	// Set when outcome is REDIRECT. The fully resolved URL to redirect to.
	RedirectURL *string `json:"redirectUrl,omitempty"`
	// Set when outcome is NOT_FOUND. Suggested GoLinks that might match the path.
	Suggestions []GoLinkView `json:"suggestions,omitempty"`
}

func (g *GoLinkServiceResolveResponse) GetActionID() *string {
	if g == nil {
		return nil
	}
	return g.ActionID
}

func (g *GoLinkServiceResolveResponse) GetChooserOptions() []GoLinkChooserOptionInput {
	if g == nil {
		return nil
	}
	return g.ChooserOptions
}

func (g *GoLinkServiceResolveResponse) GetGolink() *GoLink {
	if g == nil {
		return nil
	}
	return g.Golink
}

func (g *GoLinkServiceResolveResponse) GetOutcome() *Outcome {
	if g == nil {
		return nil
	}
	return g.Outcome
}

func (g *GoLinkServiceResolveResponse) GetPrerequisite() *GoLinkPrerequisite {
	if g == nil {
		return nil
	}
	return g.Prerequisite
}

func (g *GoLinkServiceResolveResponse) GetRedirectURL() *string {
	if g == nil {
		return nil
	}
	return g.RedirectURL
}

func (g *GoLinkServiceResolveResponse) GetSuggestions() []GoLinkView {
	if g == nil {
		return nil
	}
	return g.Suggestions
}
