// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// GoLinkTargetInput - The GoLinkTarget message.
//
// This message contains a oneof named target. Only a single field of the following list may be set at a time:
//   - redirect
//   - action
//   - chooser
type GoLinkTargetInput struct {
	Action   *GoLinkActionTarget       `json:"action,omitempty"`
	Chooser  *GoLinkChooserTargetInput `json:"chooser,omitempty"`
	Redirect *GoLinkRedirectTarget     `json:"redirect,omitempty"`
}

func (g *GoLinkTargetInput) GetAction() *GoLinkActionTarget {
	if g == nil {
		return nil
	}
	return g.Action
}

func (g *GoLinkTargetInput) GetChooser() *GoLinkChooserTargetInput {
	if g == nil {
		return nil
	}
	return g.Chooser
}

func (g *GoLinkTargetInput) GetRedirect() *GoLinkRedirectTarget {
	if g == nil {
		return nil
	}
	return g.Redirect
}
