// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ListAppUsersForIdentityWithGrantResponse message.
type ListAppUsersForIdentityWithGrantResponse struct {
	// The list of app users that may also have grant information.
	Bindings []AppEntitlementUserBinding `json:"bindings,omitempty"`
}

func (o *ListAppUsersForIdentityWithGrantResponse) GetBindings() []AppEntitlementUserBinding {
	if o == nil {
		return nil
	}
	return o.Bindings
}
