// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Unmatched struct {
}

// MCPServerServiceResolveMCPIdentifierResponse - MCPServerServiceResolveMcpIdentifierResponse is exactly one of three
//
//	outcomes. registered_server takes precedence over catalog_entry when both
//	would match: a tenant that already registered a server for this product
//	should never also be told to register it again from the catalog.
//
// This message contains a oneof named match. Only a single field of the following list may be set at a time:
//   - registeredServer
//   - catalogEntry
//   - unmatched
type MCPServerServiceResolveMCPIdentifierResponse struct {
	CatalogEntry     *MCPServerCatalogEntry `json:"catalogEntry,omitempty"`
	RegisteredServer *MCPServerView         `json:"registeredServer,omitempty"`
	Unmatched        *Unmatched             `json:"unmatched,omitempty"`
}

func (m *MCPServerServiceResolveMCPIdentifierResponse) GetCatalogEntry() *MCPServerCatalogEntry {
	if m == nil {
		return nil
	}
	return m.CatalogEntry
}

func (m *MCPServerServiceResolveMCPIdentifierResponse) GetRegisteredServer() *MCPServerView {
	if m == nil {
		return nil
	}
	return m.RegisteredServer
}

func (m *MCPServerServiceResolveMCPIdentifierResponse) GetUnmatched() *Unmatched {
	if m == nil {
		return nil
	}
	return m.Unmatched
}
