// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// MySpendTrajectoryPoint represents the caller's settled spend for one UTC day.
type MySpendTrajectoryPoint struct {
	// Spend settled during the day, in billionths of the configured currency unit.
	ConsumedNano *int64     `integer:"string" json:"consumedNano,omitempty"`
	Day          *time.Time `json:"day,omitempty"`
}

func (m MySpendTrajectoryPoint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MySpendTrajectoryPoint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MySpendTrajectoryPoint) GetConsumedNano() *int64 {
	if m == nil {
		return nil
	}
	return m.ConsumedNano
}

func (m *MySpendTrajectoryPoint) GetDay() *time.Time {
	if m == nil {
		return nil
	}
	return m.Day
}
