// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PolicyFormInput - The Form message.
type PolicyFormInput struct {
	// A form is a collection of fields to be filled out by a user
	Form *Form `json:"form,omitempty"`
}

func (p *PolicyFormInput) GetForm() *Form {
	if p == nil {
		return nil
	}
	return p.Form
}
