// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RequestCatalogManagementServiceListEntitlementsForAccessResponse - The RequestCatalogManagementServiceListEntitlementsForAccessResponse message.
type RequestCatalogManagementServiceListEntitlementsForAccessResponse struct {
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
	// The list field.
	List []AppEntitlementView `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}
