// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RequestCatalogManagementServiceGetResponse - The RequestCatalogManagementServiceGetResponse message.
type RequestCatalogManagementServiceGetResponse struct {
	// The RequestCatalogView message.
	RequestCatalogView *RequestCatalogView `json:"requestCatalogView,omitempty"`
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
}
