// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// ResolvedAmount records the admitted nano-unit limit.
type ResolvedAmount struct {
	// Admitted limit, in nano-units.
	AmountNano *int64 `integer:"string" json:"amountNano,omitempty"`
}

func (r ResolvedAmount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResolvedAmount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResolvedAmount) GetAmountNano() *int64 {
	if r == nil {
		return nil
	}
	return r.AmountNano
}
