// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DenialReason - Reason spend is denied. Present only when state is DENIED.
type DenialReason string

const (
	DenialReasonSpendDenyReasonUnspecified      DenialReason = "SPEND_DENY_REASON_UNSPECIFIED"
	DenialReasonSpendDenyReasonTenantFrozen     DenialReason = "SPEND_DENY_REASON_TENANT_FROZEN"
	DenialReasonSpendDenyReasonSuspendedByAdmin DenialReason = "SPEND_DENY_REASON_SUSPENDED_BY_ADMIN"
	DenialReasonSpendDenyReasonAppSuspended     DenialReason = "SPEND_DENY_REASON_APP_SUSPENDED"
	DenialReasonSpendDenyReasonAppPausedByYou   DenialReason = "SPEND_DENY_REASON_APP_PAUSED_BY_YOU"
	DenialReasonSpendDenyReasonNoSupply         DenialReason = "SPEND_DENY_REASON_NO_SUPPLY"
)

func (e DenialReason) ToPointer() *DenialReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_DENY_REASON_UNSPECIFIED", "SPEND_DENY_REASON_TENANT_FROZEN", "SPEND_DENY_REASON_SUSPENDED_BY_ADMIN", "SPEND_DENY_REASON_APP_SUSPENDED", "SPEND_DENY_REASON_APP_PAUSED_BY_YOU", "SPEND_DENY_REASON_NO_SUPPLY":
			return true
		}
	}
	return false
}

// ResolveEffectiveLimitsResponseState - Result of resolving the user's effective limits.
type ResolveEffectiveLimitsResponseState string

const (
	ResolveEffectiveLimitsResponseStateEffectiveLimitsStateUnspecified ResolveEffectiveLimitsResponseState = "EFFECTIVE_LIMITS_STATE_UNSPECIFIED"
	ResolveEffectiveLimitsResponseStateEffectiveLimitsStateResolved    ResolveEffectiveLimitsResponseState = "EFFECTIVE_LIMITS_STATE_RESOLVED"
	ResolveEffectiveLimitsResponseStateEffectiveLimitsStateNoPolicy    ResolveEffectiveLimitsResponseState = "EFFECTIVE_LIMITS_STATE_NO_POLICY"
	ResolveEffectiveLimitsResponseStateEffectiveLimitsStateNoCeiling   ResolveEffectiveLimitsResponseState = "EFFECTIVE_LIMITS_STATE_NO_CEILING"
	ResolveEffectiveLimitsResponseStateEffectiveLimitsStateDenied      ResolveEffectiveLimitsResponseState = "EFFECTIVE_LIMITS_STATE_DENIED"
)

func (e ResolveEffectiveLimitsResponseState) ToPointer() *ResolveEffectiveLimitsResponseState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ResolveEffectiveLimitsResponseState) IsExact() bool {
	if e != nil {
		switch *e {
		case "EFFECTIVE_LIMITS_STATE_UNSPECIFIED", "EFFECTIVE_LIMITS_STATE_RESOLVED", "EFFECTIVE_LIMITS_STATE_NO_POLICY", "EFFECTIVE_LIMITS_STATE_NO_CEILING", "EFFECTIVE_LIMITS_STATE_DENIED":
			return true
		}
	}
	return false
}

// ResolveEffectiveLimitsResponse contains the limits currently applying to a user.
type ResolveEffectiveLimitsResponse struct {
	// Currency used for monetary values.
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// Reason spend is denied. Present only when state is DENIED.
	DenialReason *DenialReason `json:"denialReason,omitempty"`
	// Scope that denies spend. Present only when state is DENIED.
	DenialScopeName *string `json:"denialScopeName,omitempty"`
	// Ordered organization, user, application, and user-application scopes.
	Scopes []EffectiveScope `json:"scopes,omitempty"`
	// Result of resolving the user's effective limits.
	State *ResolveEffectiveLimitsResponseState `json:"state,omitempty"`
}

func (r *ResolveEffectiveLimitsResponse) GetCurrencyCode() *string {
	if r == nil {
		return nil
	}
	return r.CurrencyCode
}

func (r *ResolveEffectiveLimitsResponse) GetDenialReason() *DenialReason {
	if r == nil {
		return nil
	}
	return r.DenialReason
}

func (r *ResolveEffectiveLimitsResponse) GetDenialScopeName() *string {
	if r == nil {
		return nil
	}
	return r.DenialScopeName
}

func (r *ResolveEffectiveLimitsResponse) GetScopes() []EffectiveScope {
	if r == nil {
		return nil
	}
	return r.Scopes
}

func (r *ResolveEffectiveLimitsResponse) GetState() *ResolveEffectiveLimitsResponseState {
	if r == nil {
		return nil
	}
	return r.State
}
