// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// SearchAppSecretsWithAlertCountResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type SearchAppSecretsWithAlertCountResponseExpanded struct {
	// The type of the serialized message.
	AtType               *string        `json:"@type,omitempty"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (s SearchAppSecretsWithAlertCountResponseExpanded) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchAppSecretsWithAlertCountResponseExpanded) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchAppSecretsWithAlertCountResponseExpanded) GetAtType() *string {
	if s == nil {
		return nil
	}
	return s.AtType
}

func (s *SearchAppSecretsWithAlertCountResponseExpanded) GetAdditionalProperties() map[string]any {
	if s == nil {
		return nil
	}
	return s.AdditionalProperties
}

// The SearchAppSecretsWithAlertCountResponse message.
type SearchAppSecretsWithAlertCountResponse struct {
	// The expanded field.
	Expanded []SearchAppSecretsWithAlertCountResponseExpanded `json:"expanded,omitempty"`
	// The list field.
	List []AppSecretResourceView `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (s *SearchAppSecretsWithAlertCountResponse) GetExpanded() []SearchAppSecretsWithAlertCountResponseExpanded {
	if s == nil {
		return nil
	}
	return s.Expanded
}

func (s *SearchAppSecretsWithAlertCountResponse) GetList() []AppSecretResourceView {
	if s == nil {
		return nil
	}
	return s.List
}

func (s *SearchAppSecretsWithAlertCountResponse) GetNextPageToken() *string {
	if s == nil {
		return nil
	}
	return s.NextPageToken
}
