// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SearchRequestableCredentialOfferingsRequest message.
type SearchRequestableCredentialOfferingsRequest struct {
	// Limits the search to one app.
	AppID *string `json:"appId,omitempty"`
	// The pageSize field.
	PageSize *int `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// The query field.
	Query *string `json:"query,omitempty"`
	// The user to search for. Defaults to the caller.
	TargetUserID *string `json:"targetUserId,omitempty"`
}

func (s *SearchRequestableCredentialOfferingsRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *SearchRequestableCredentialOfferingsRequest) GetPageSize() *int {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SearchRequestableCredentialOfferingsRequest) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SearchRequestableCredentialOfferingsRequest) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *SearchRequestableCredentialOfferingsRequest) GetTargetUserID() *string {
	if s == nil {
		return nil
	}
	return s.TargetUserID
}
