// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CurrentAccountType - What the account is currently classified as in ConductorOne.
type CurrentAccountType string

const (
	CurrentAccountTypeAppUserTypeUnspecified    CurrentAccountType = "APP_USER_TYPE_UNSPECIFIED"
	CurrentAccountTypeAppUserTypeUser           CurrentAccountType = "APP_USER_TYPE_USER"
	CurrentAccountTypeAppUserTypeServiceAccount CurrentAccountType = "APP_USER_TYPE_SERVICE_ACCOUNT"
	CurrentAccountTypeAppUserTypeSystemAccount  CurrentAccountType = "APP_USER_TYPE_SYSTEM_ACCOUNT"
)

func (e CurrentAccountType) ToPointer() *CurrentAccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CurrentAccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "APP_USER_TYPE_UNSPECIFIED", "APP_USER_TYPE_USER", "APP_USER_TYPE_SERVICE_ACCOUNT", "APP_USER_TYPE_SYSTEM_ACCOUNT":
			return true
		}
	}
	return false
}

// DetectedAccountType - What the detector thinks the account actually is.
type DetectedAccountType string

const (
	DetectedAccountTypeAppUserTypeUnspecified    DetectedAccountType = "APP_USER_TYPE_UNSPECIFIED"
	DetectedAccountTypeAppUserTypeUser           DetectedAccountType = "APP_USER_TYPE_USER"
	DetectedAccountTypeAppUserTypeServiceAccount DetectedAccountType = "APP_USER_TYPE_SERVICE_ACCOUNT"
	DetectedAccountTypeAppUserTypeSystemAccount  DetectedAccountType = "APP_USER_TYPE_SYSTEM_ACCOUNT"
)

func (e DetectedAccountType) ToPointer() *DetectedAccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DetectedAccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "APP_USER_TYPE_UNSPECIFIED", "APP_USER_TYPE_USER", "APP_USER_TYPE_SERVICE_ACCOUNT", "APP_USER_TYPE_SYSTEM_ACCOUNT":
			return true
		}
	}
	return false
}

// ServiceAccountMisclassificationType - ServiceAccountMisclassificationType: account classified as human but
//
//	detected as service account, or vice versa.
//	Target: AppUserTarget (the misclassified account).
type ServiceAccountMisclassificationType struct {
	// What the account is currently classified as in ConductorOne.
	CurrentAccountType *CurrentAccountType `json:"currentAccountType,omitempty"`
	// What the detector thinks the account actually is.
	DetectedAccountType *DetectedAccountType `json:"detectedAccountType,omitempty"`
}

func (s *ServiceAccountMisclassificationType) GetCurrentAccountType() *CurrentAccountType {
	if s == nil {
		return nil
	}
	return s.CurrentAccountType
}

func (s *ServiceAccountMisclassificationType) GetDetectedAccountType() *DetectedAccountType {
	if s == nil {
		return nil
	}
	return s.DetectedAccountType
}
