// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SpecificAccessProfilesScope - Empty marker for access-profile scoping.
//
//	Actual profile selections stored in separate rows keyed by access_review_id.
type SpecificAccessProfilesScope struct {
}
