// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// SpendRemedyControlsSnapshotPeriod - The period field.
type SpendRemedyControlsSnapshotPeriod string

const (
	SpendRemedyControlsSnapshotPeriodPeriodKindUnspecified SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_UNSPECIFIED"
	SpendRemedyControlsSnapshotPeriodPeriodKindDaily       SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_DAILY"
	SpendRemedyControlsSnapshotPeriodPeriodKindWeekly      SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_WEEKLY"
	SpendRemedyControlsSnapshotPeriodPeriodKindMonthly     SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_MONTHLY"
	SpendRemedyControlsSnapshotPeriodPeriodKindQuarterly   SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_QUARTERLY"
	SpendRemedyControlsSnapshotPeriodPeriodKindYearly      SpendRemedyControlsSnapshotPeriod = "PERIOD_KIND_YEARLY"
)

func (e SpendRemedyControlsSnapshotPeriod) ToPointer() *SpendRemedyControlsSnapshotPeriod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SpendRemedyControlsSnapshotPeriod) IsExact() bool {
	if e != nil {
		switch *e {
		case "PERIOD_KIND_UNSPECIFIED", "PERIOD_KIND_DAILY", "PERIOD_KIND_WEEKLY", "PERIOD_KIND_MONTHLY", "PERIOD_KIND_QUARTERLY", "PERIOD_KIND_YEARLY":
			return true
		}
	}
	return false
}

// The SpendRemedyControlsSnapshot message.
type SpendRemedyControlsSnapshot struct {
	Controls *FundsSpendControls `json:"controls,omitempty"`
	// The period field.
	Period *SpendRemedyControlsSnapshotPeriod `json:"period,omitempty"`
	// The version field.
	Version *int64 `integer:"string" json:"version,omitempty"`
}

func (s SpendRemedyControlsSnapshot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpendRemedyControlsSnapshot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpendRemedyControlsSnapshot) GetControls() *FundsSpendControls {
	if s == nil {
		return nil
	}
	return s.Controls
}

func (s *SpendRemedyControlsSnapshot) GetPeriod() *SpendRemedyControlsSnapshotPeriod {
	if s == nil {
		return nil
	}
	return s.Period
}

func (s *SpendRemedyControlsSnapshot) GetVersion() *int64 {
	if s == nil {
		return nil
	}
	return s.Version
}
