// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SSFReceiverStreamServiceGetStatsResponse message.
type SSFReceiverStreamServiceGetStatsResponse struct {
	// SSFReceiverStreamStats is a lightweight read-only stats object.
	SSFReceiverStreamStats *SSFReceiverStreamStats `json:"stats,omitempty"`
}

func (s *SSFReceiverStreamServiceGetStatsResponse) GetSSFReceiverStreamStats() *SSFReceiverStreamStats {
	if s == nil {
		return nil
	}
	return s.SSFReceiverStreamStats
}
