// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSFReceiverEventSearchServiceSearchRequestOutcome - The outcome field.
type SSFReceiverEventSearchServiceSearchRequestOutcome string

const (
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeUnspecified         SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_UNSPECIFIED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeSessionsRevoked     SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_SESSIONS_REVOKED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeLogged              SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_LOGGED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomePrincipalNotFound   SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_PRINCIPAL_NOT_FOUND"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeVerified            SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_VERIFIED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeStreamStatusUpdated SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_STREAM_STATUS_UPDATED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeUnrecognized        SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_UNRECOGNIZED"
	SSFReceiverEventSearchServiceSearchRequestOutcomeSsfEventOutcomeError               SSFReceiverEventSearchServiceSearchRequestOutcome = "SSF_EVENT_OUTCOME_ERROR"
)

func (e SSFReceiverEventSearchServiceSearchRequestOutcome) ToPointer() *SSFReceiverEventSearchServiceSearchRequestOutcome {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverEventSearchServiceSearchRequestOutcome) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_EVENT_OUTCOME_UNSPECIFIED", "SSF_EVENT_OUTCOME_SESSIONS_REVOKED", "SSF_EVENT_OUTCOME_LOGGED", "SSF_EVENT_OUTCOME_PRINCIPAL_NOT_FOUND", "SSF_EVENT_OUTCOME_VERIFIED", "SSF_EVENT_OUTCOME_STREAM_STATUS_UPDATED", "SSF_EVENT_OUTCOME_UNRECOGNIZED", "SSF_EVENT_OUTCOME_ERROR":
			return true
		}
	}
	return false
}

// The SSFReceiverEventSearchServiceSearchRequest message.
type SSFReceiverEventSearchServiceSearchRequest struct {
	// The eventType field.
	EventType *string `json:"eventType,omitempty"`
	// The matchedUserId field.
	MatchedUserID *string `json:"matchedUserId,omitempty"`
	// The outcome field.
	Outcome *SSFReceiverEventSearchServiceSearchRequestOutcome `json:"outcome,omitempty"`
	// The pageSize field.
	PageSize *int `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// The query field.
	Query *string `json:"query,omitempty"`
	// The streamId field.
	StreamID *string `json:"streamId,omitempty"`
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetEventType() *string {
	if s == nil {
		return nil
	}
	return s.EventType
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetMatchedUserID() *string {
	if s == nil {
		return nil
	}
	return s.MatchedUserID
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetOutcome() *SSFReceiverEventSearchServiceSearchRequestOutcome {
	if s == nil {
		return nil
	}
	return s.Outcome
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetPageSize() *int {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *SSFReceiverEventSearchServiceSearchRequest) GetStreamID() *string {
	if s == nil {
		return nil
	}
	return s.StreamID
}
