// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SSFReceiverStreamServiceTestRequest message.
type SSFReceiverStreamServiceTestRequest struct {
	// The upstream identifier to test resolution with. Typically an email address
	//  (e.g., "alice@company.com") — the same value the IdP would send in a SET subject.
	//  The Test RPC runs resolveSubject on this to verify the identity mapping works.
	//  Optional: upstream identifier (email) to test identity resolution.
	//  If empty, only JWKS reachability is tested.
	TestSubject *string `json:"testSubject,omitempty"`
}

func (s *SSFReceiverStreamServiceTestRequest) GetTestSubject() *string {
	if s == nil {
		return nil
	}
	return s.TestSubject
}
