// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SSFReceiverStreamServiceListResponse message.
type SSFReceiverStreamServiceListResponse struct {
	// The list field.
	List []SSFReceiverStream `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (s *SSFReceiverStreamServiceListResponse) GetList() []SSFReceiverStream {
	if s == nil {
		return nil
	}
	return s.List
}

func (s *SSFReceiverStreamServiceListResponse) GetNextPageToken() *string {
	if s == nil {
		return nil
	}
	return s.NextPageToken
}
