// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// SSFReceiverStreamStats is a lightweight read-only stats object.
type SSFReceiverStreamStats struct {
	// The eventsActedOnCount field.
	EventsActedOnCount *int64 `integer:"string" json:"eventsActedOnCount,omitempty"`
	// The eventsFailedCount field.
	EventsFailedCount *int64 `integer:"string" json:"eventsFailedCount,omitempty"`
	// The eventsReceivedCount field.
	EventsReceivedCount *int64     `integer:"string" json:"eventsReceivedCount,omitempty"`
	LastErrorAt         *time.Time `json:"lastErrorAt,omitempty"`
	// The lastErrorMessage field.
	LastErrorMessage    *string    `json:"lastErrorMessage,omitempty"`
	LastEventReceivedAt *time.Time `json:"lastEventReceivedAt,omitempty"`
	LastVerifiedAt      *time.Time `json:"lastVerifiedAt,omitempty"`
	// The streamId field.
	StreamID *string `json:"streamId,omitempty"`
	// The transmitterStatus field.
	TransmitterStatus *string `json:"transmitterStatus,omitempty"`
	// The transmitterStatusReason field.
	TransmitterStatusReason *string `json:"transmitterStatusReason,omitempty"`
}

func (s SSFReceiverStreamStats) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSFReceiverStreamStats) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSFReceiverStreamStats) GetEventsActedOnCount() *int64 {
	if s == nil {
		return nil
	}
	return s.EventsActedOnCount
}

func (s *SSFReceiverStreamStats) GetEventsFailedCount() *int64 {
	if s == nil {
		return nil
	}
	return s.EventsFailedCount
}

func (s *SSFReceiverStreamStats) GetEventsReceivedCount() *int64 {
	if s == nil {
		return nil
	}
	return s.EventsReceivedCount
}

func (s *SSFReceiverStreamStats) GetLastErrorAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastErrorAt
}

func (s *SSFReceiverStreamStats) GetLastErrorMessage() *string {
	if s == nil {
		return nil
	}
	return s.LastErrorMessage
}

func (s *SSFReceiverStreamStats) GetLastEventReceivedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastEventReceivedAt
}

func (s *SSFReceiverStreamStats) GetLastVerifiedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastVerifiedAt
}

func (s *SSFReceiverStreamStats) GetStreamID() *string {
	if s == nil {
		return nil
	}
	return s.StreamID
}

func (s *SSFReceiverStreamStats) GetTransmitterStatus() *string {
	if s == nil {
		return nil
	}
	return s.TransmitterStatus
}

func (s *SSFReceiverStreamStats) GetTransmitterStatusReason() *string {
	if s == nil {
		return nil
	}
	return s.TransmitterStatusReason
}
