// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSFReceiverStreamServiceCreateRequestAccountDisabledAction - The accountDisabledAction field.
type SSFReceiverStreamServiceCreateRequestAccountDisabledAction string

const (
	SSFReceiverStreamServiceCreateRequestAccountDisabledActionSsfRevocationActionUnspecified SSFReceiverStreamServiceCreateRequestAccountDisabledAction = "SSF_REVOCATION_ACTION_UNSPECIFIED"
	SSFReceiverStreamServiceCreateRequestAccountDisabledActionSsfRevocationActionRevokeAll   SSFReceiverStreamServiceCreateRequestAccountDisabledAction = "SSF_REVOCATION_ACTION_REVOKE_ALL"
	SSFReceiverStreamServiceCreateRequestAccountDisabledActionSsfRevocationActionLogOnly     SSFReceiverStreamServiceCreateRequestAccountDisabledAction = "SSF_REVOCATION_ACTION_LOG_ONLY"
)

func (e SSFReceiverStreamServiceCreateRequestAccountDisabledAction) ToPointer() *SSFReceiverStreamServiceCreateRequestAccountDisabledAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverStreamServiceCreateRequestAccountDisabledAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_REVOCATION_ACTION_UNSPECIFIED", "SSF_REVOCATION_ACTION_REVOKE_ALL", "SSF_REVOCATION_ACTION_LOG_ONLY":
			return true
		}
	}
	return false
}

// SSFReceiverStreamServiceCreateRequestCredentialChangeAction - The credentialChangeAction field.
type SSFReceiverStreamServiceCreateRequestCredentialChangeAction string

const (
	SSFReceiverStreamServiceCreateRequestCredentialChangeActionSsfRevocationActionUnspecified SSFReceiverStreamServiceCreateRequestCredentialChangeAction = "SSF_REVOCATION_ACTION_UNSPECIFIED"
	SSFReceiverStreamServiceCreateRequestCredentialChangeActionSsfRevocationActionRevokeAll   SSFReceiverStreamServiceCreateRequestCredentialChangeAction = "SSF_REVOCATION_ACTION_REVOKE_ALL"
	SSFReceiverStreamServiceCreateRequestCredentialChangeActionSsfRevocationActionLogOnly     SSFReceiverStreamServiceCreateRequestCredentialChangeAction = "SSF_REVOCATION_ACTION_LOG_ONLY"
)

func (e SSFReceiverStreamServiceCreateRequestCredentialChangeAction) ToPointer() *SSFReceiverStreamServiceCreateRequestCredentialChangeAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverStreamServiceCreateRequestCredentialChangeAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_REVOCATION_ACTION_UNSPECIFIED", "SSF_REVOCATION_ACTION_REVOKE_ALL", "SSF_REVOCATION_ACTION_LOG_ONLY":
			return true
		}
	}
	return false
}

// SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction - The credentialCompromiseAction field.
type SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction string

const (
	SSFReceiverStreamServiceCreateRequestCredentialCompromiseActionSsfRevocationActionUnspecified SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction = "SSF_REVOCATION_ACTION_UNSPECIFIED"
	SSFReceiverStreamServiceCreateRequestCredentialCompromiseActionSsfRevocationActionRevokeAll   SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction = "SSF_REVOCATION_ACTION_REVOKE_ALL"
	SSFReceiverStreamServiceCreateRequestCredentialCompromiseActionSsfRevocationActionLogOnly     SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction = "SSF_REVOCATION_ACTION_LOG_ONLY"
)

func (e SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction) ToPointer() *SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_REVOCATION_ACTION_UNSPECIFIED", "SSF_REVOCATION_ACTION_REVOKE_ALL", "SSF_REVOCATION_ACTION_LOG_ONLY":
			return true
		}
	}
	return false
}

// SSFReceiverStreamServiceCreateRequestDeliveryMethod - The deliveryMethod field.
type SSFReceiverStreamServiceCreateRequestDeliveryMethod string

const (
	SSFReceiverStreamServiceCreateRequestDeliveryMethodSsfDeliveryMethodUnspecified SSFReceiverStreamServiceCreateRequestDeliveryMethod = "SSF_DELIVERY_METHOD_UNSPECIFIED"
	SSFReceiverStreamServiceCreateRequestDeliveryMethodSsfDeliveryMethodPush        SSFReceiverStreamServiceCreateRequestDeliveryMethod = "SSF_DELIVERY_METHOD_PUSH"
	SSFReceiverStreamServiceCreateRequestDeliveryMethodSsfDeliveryMethodPoll        SSFReceiverStreamServiceCreateRequestDeliveryMethod = "SSF_DELIVERY_METHOD_POLL"
)

func (e SSFReceiverStreamServiceCreateRequestDeliveryMethod) ToPointer() *SSFReceiverStreamServiceCreateRequestDeliveryMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverStreamServiceCreateRequestDeliveryMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_DELIVERY_METHOD_UNSPECIFIED", "SSF_DELIVERY_METHOD_PUSH", "SSF_DELIVERY_METHOD_POLL":
			return true
		}
	}
	return false
}

// SSFReceiverStreamServiceCreateRequestSessionRevokedAction - Per-event-type action configuration.
type SSFReceiverStreamServiceCreateRequestSessionRevokedAction string

const (
	SSFReceiverStreamServiceCreateRequestSessionRevokedActionSsfRevocationActionUnspecified SSFReceiverStreamServiceCreateRequestSessionRevokedAction = "SSF_REVOCATION_ACTION_UNSPECIFIED"
	SSFReceiverStreamServiceCreateRequestSessionRevokedActionSsfRevocationActionRevokeAll   SSFReceiverStreamServiceCreateRequestSessionRevokedAction = "SSF_REVOCATION_ACTION_REVOKE_ALL"
	SSFReceiverStreamServiceCreateRequestSessionRevokedActionSsfRevocationActionLogOnly     SSFReceiverStreamServiceCreateRequestSessionRevokedAction = "SSF_REVOCATION_ACTION_LOG_ONLY"
)

func (e SSFReceiverStreamServiceCreateRequestSessionRevokedAction) ToPointer() *SSFReceiverStreamServiceCreateRequestSessionRevokedAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSFReceiverStreamServiceCreateRequestSessionRevokedAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SSF_REVOCATION_ACTION_UNSPECIFIED", "SSF_REVOCATION_ACTION_REVOKE_ALL", "SSF_REVOCATION_ACTION_LOG_ONLY":
			return true
		}
	}
	return false
}

// The SSFReceiverStreamServiceCreateRequest message.
type SSFReceiverStreamServiceCreateRequest struct {
	// The accountDisabledAction field.
	AccountDisabledAction *SSFReceiverStreamServiceCreateRequestAccountDisabledAction `json:"accountDisabledAction,omitempty"`
	// The credentialChangeAction field.
	CredentialChangeAction *SSFReceiverStreamServiceCreateRequestCredentialChangeAction `json:"credentialChangeAction,omitempty"`
	// The credentialCompromiseAction field.
	CredentialCompromiseAction *SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction `json:"credentialCompromiseAction,omitempty"`
	// The deliveryMethod field.
	DeliveryMethod *SSFReceiverStreamServiceCreateRequestDeliveryMethod `json:"deliveryMethod,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	// The displayName field.
	DisplayName string `json:"displayName"`
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The expectedAudience field.
	ExpectedAudience *string `json:"expectedAudience,omitempty"`
	// The issuerUrl field.
	IssuerURL string `json:"issuerUrl"`
	// The jwksUrl field.
	JwksURL *string `json:"jwksUrl,omitempty"`
	// The pollEndpointUrl field.
	PollEndpointURL *string `json:"pollEndpointUrl,omitempty"`
	PollInterval    *string `json:"pollInterval,omitempty"`
	// Per-event-type action configuration.
	SessionRevokedAction *SSFReceiverStreamServiceCreateRequestSessionRevokedAction `json:"sessionRevokedAction,omitempty"`
}

func (s *SSFReceiverStreamServiceCreateRequest) GetAccountDisabledAction() *SSFReceiverStreamServiceCreateRequestAccountDisabledAction {
	if s == nil {
		return nil
	}
	return s.AccountDisabledAction
}

func (s *SSFReceiverStreamServiceCreateRequest) GetCredentialChangeAction() *SSFReceiverStreamServiceCreateRequestCredentialChangeAction {
	if s == nil {
		return nil
	}
	return s.CredentialChangeAction
}

func (s *SSFReceiverStreamServiceCreateRequest) GetCredentialCompromiseAction() *SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction {
	if s == nil {
		return nil
	}
	return s.CredentialCompromiseAction
}

func (s *SSFReceiverStreamServiceCreateRequest) GetDeliveryMethod() *SSFReceiverStreamServiceCreateRequestDeliveryMethod {
	if s == nil {
		return nil
	}
	return s.DeliveryMethod
}

func (s *SSFReceiverStreamServiceCreateRequest) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SSFReceiverStreamServiceCreateRequest) GetDisplayName() string {
	if s == nil {
		return ""
	}
	return s.DisplayName
}

func (s *SSFReceiverStreamServiceCreateRequest) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SSFReceiverStreamServiceCreateRequest) GetExpectedAudience() *string {
	if s == nil {
		return nil
	}
	return s.ExpectedAudience
}

func (s *SSFReceiverStreamServiceCreateRequest) GetIssuerURL() string {
	if s == nil {
		return ""
	}
	return s.IssuerURL
}

func (s *SSFReceiverStreamServiceCreateRequest) GetJwksURL() *string {
	if s == nil {
		return nil
	}
	return s.JwksURL
}

func (s *SSFReceiverStreamServiceCreateRequest) GetPollEndpointURL() *string {
	if s == nil {
		return nil
	}
	return s.PollEndpointURL
}

func (s *SSFReceiverStreamServiceCreateRequest) GetPollInterval() *string {
	if s == nil {
		return nil
	}
	return s.PollInterval
}

func (s *SSFReceiverStreamServiceCreateRequest) GetSessionRevokedAction() *SSFReceiverStreamServiceCreateRequestSessionRevokedAction {
	if s == nil {
		return nil
	}
	return s.SessionRevokedAction
}
