// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SSFReceiverEventServiceListResponse message.
type SSFReceiverEventServiceListResponse struct {
	// The list field.
	List []SSFReceiverEvent `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (s *SSFReceiverEventServiceListResponse) GetList() []SSFReceiverEvent {
	if s == nil {
		return nil
	}
	return s.List
}

func (s *SSFReceiverEventServiceListResponse) GetNextPageToken() *string {
	if s == nil {
		return nil
	}
	return s.NextPageToken
}
