// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The TaskServiceGetSpendRemedyStatusResponse message.
type TaskServiceGetSpendRemedyStatusResponse struct {
	Status *SpendRemedyStatus `json:"status,omitempty"`
}

func (t *TaskServiceGetSpendRemedyStatusResponse) GetStatus() *SpendRemedyStatus {
	if t == nil {
		return nil
	}
	return t.Status
}
