// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// TBTopDestination is one dest_host group, excluding rows with an empty
//
//	dest_host (non-egress or unresolved calls).
type TBTopDestination struct {
	// The allowedCount field.
	AllowedCount *int64 `integer:"string" json:"allowedCount,omitempty"`
	// The callCount field.
	CallCount *int64 `integer:"string" json:"callCount,omitempty"`
	// The deniedCount field.
	DeniedCount *int64 `integer:"string" json:"deniedCount,omitempty"`
	// The destHost field.
	DestHost *string `json:"destHost,omitempty"`
	// The distinctAgentCount field.
	DistinctAgentCount *int64 `integer:"string" json:"distinctAgentCount,omitempty"`
	// The requestBytes field.
	RequestBytes *int64 `integer:"string" json:"requestBytes,omitempty"`
	// The responseBytes field.
	ResponseBytes *int64 `integer:"string" json:"responseBytes,omitempty"`
	// Zero-filled call_count series of length trend_buckets, oldest first.
	//  Only populated when the request set include_trend.
	Trend []int64 `integer:"string" json:"trend,omitempty"`
	// The unspecifiedCount field.
	UnspecifiedCount *int64 `integer:"string" json:"unspecifiedCount,omitempty"`
}

func (t TBTopDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TBTopDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TBTopDestination) GetAllowedCount() *int64 {
	if t == nil {
		return nil
	}
	return t.AllowedCount
}

func (t *TBTopDestination) GetCallCount() *int64 {
	if t == nil {
		return nil
	}
	return t.CallCount
}

func (t *TBTopDestination) GetDeniedCount() *int64 {
	if t == nil {
		return nil
	}
	return t.DeniedCount
}

func (t *TBTopDestination) GetDestHost() *string {
	if t == nil {
		return nil
	}
	return t.DestHost
}

func (t *TBTopDestination) GetDistinctAgentCount() *int64 {
	if t == nil {
		return nil
	}
	return t.DistinctAgentCount
}

func (t *TBTopDestination) GetRequestBytes() *int64 {
	if t == nil {
		return nil
	}
	return t.RequestBytes
}

func (t *TBTopDestination) GetResponseBytes() *int64 {
	if t == nil {
		return nil
	}
	return t.ResponseBytes
}

func (t *TBTopDestination) GetTrend() []int64 {
	if t == nil {
		return nil
	}
	return t.Trend
}

func (t *TBTopDestination) GetUnspecifiedCount() *int64 {
	if t == nil {
		return nil
	}
	return t.UnspecifiedCount
}
