// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
	"time"
)

// Capability - The capability field.
type Capability string

const (
	CapabilityTbTrafficCapabilityUnspecified Capability = "TB_TRAFFIC_CAPABILITY_UNSPECIFIED"
	CapabilityTbTrafficCapabilityEgress      Capability = "TB_TRAFFIC_CAPABILITY_EGRESS"
	CapabilityTbTrafficCapabilityLlm         Capability = "TB_TRAFFIC_CAPABILITY_LLM"
)

func (e Capability) ToPointer() *Capability {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Capability) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TRAFFIC_CAPABILITY_UNSPECIFIED", "TB_TRAFFIC_CAPABILITY_EGRESS", "TB_TRAFFIC_CAPABILITY_LLM":
			return true
		}
	}
	return false
}

// CostLookup - The costLookup field.
type CostLookup string

const (
	CostLookupTbCostLookupUnspecified CostLookup = "TB_COST_LOOKUP_UNSPECIFIED"
	CostLookupTbCostLookupPriced      CostLookup = "TB_COST_LOOKUP_PRICED"
	CostLookupTbCostLookupUnpriced    CostLookup = "TB_COST_LOOKUP_UNPRICED"
	CostLookupTbCostLookupUnmatched   CostLookup = "TB_COST_LOOKUP_UNMATCHED"
	CostLookupTbCostLookupRoute       CostLookup = "TB_COST_LOOKUP_ROUTE"
)

func (e CostLookup) ToPointer() *CostLookup {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CostLookup) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_COST_LOOKUP_UNSPECIFIED", "TB_COST_LOOKUP_PRICED", "TB_COST_LOOKUP_UNPRICED", "TB_COST_LOOKUP_UNMATCHED", "TB_COST_LOOKUP_ROUTE":
			return true
		}
	}
	return false
}

// TBTrafficEventOutcome - The outcome field.
type TBTrafficEventOutcome string

const (
	TBTrafficEventOutcomeTbTrafficOutcomeUnspecified TBTrafficEventOutcome = "TB_TRAFFIC_OUTCOME_UNSPECIFIED"
	TBTrafficEventOutcomeTbTrafficOutcomeAllowed     TBTrafficEventOutcome = "TB_TRAFFIC_OUTCOME_ALLOWED"
	TBTrafficEventOutcomeTbTrafficOutcomeDenied      TBTrafficEventOutcome = "TB_TRAFFIC_OUTCOME_DENIED"
)

func (e TBTrafficEventOutcome) ToPointer() *TBTrafficEventOutcome {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TBTrafficEventOutcome) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_TRAFFIC_OUTCOME_UNSPECIFIED", "TB_TRAFFIC_OUTCOME_ALLOWED", "TB_TRAFFIC_OUTCOME_DENIED":
			return true
		}
	}
	return false
}

// TBTrafficEvent is a curated projection of one ClickHouse audit row -- only
//
//	the columns the Traffic UI needs. dest_host/dest_port/request_authority
//	(egress-shaped) and model_route/model_target/logical_model (LLM-shaped)
//	are separate raw fields rather than one pre-formatted "target" string,
//	since which fields apply depends on `capability` and that formatting
//	choice belongs to the UI layer, not this API.
type TBTrafficEvent struct {
	// One-based provider attempt; 0 on the listener-flow row. A retried call
	//  bills once per attempt.
	AttemptOrdinal *string `json:"attemptOrdinal,omitempty"`
	// The cacheReadTokens field.
	CacheReadTokens *string `json:"cacheReadTokens,omitempty"`
	// The cacheWriteTokens field.
	CacheWriteTokens *string `json:"cacheWriteTokens,omitempty"`
	// answer | auxiliary. An auxiliary call bills on top of the answer call.
	CallRole *string `json:"callRole,omitempty"`
	// The capability field.
	Capability *Capability `json:"capability,omitempty"`
	// Time Bandit's own sha256 content hash of its daemon config -- not an
	//  Edge/C1 policy generation. Set on LLM rows only; empty on every egress
	//  row.
	ConfigGeneration *string `json:"configGeneration,omitempty"`
	// The costLookup field.
	CostLookup *CostLookup `json:"costLookup,omitempty"`
	// Computed on read from the token counts above via pkg/inferenceprice; 0
	//  and not a real price unless cost_lookup is PRICED.
	CostNanoUsd *int64 `integer:"string" json:"costNanoUsd,omitempty"`
	// The counterLatencyMs field.
	CounterLatencyMs *string `json:"counterLatencyMs,omitempty"`
	// The counterRequestBytes field.
	CounterRequestBytes *string `json:"counterRequestBytes,omitempty"`
	// The counterResponseBytes field.
	CounterResponseBytes *string `json:"counterResponseBytes,omitempty"`
	// Egress-shaped destination fields; empty when capability is LLM and no
	//  egress connection underlies the call.
	DestHost *string `json:"destHost,omitempty"`
	// The destPort field.
	DestPort *int64 `json:"destPort,omitempty"`
	// observe | enforce -- the Edge mode the egress access policy ran under
	//  for this row. Empty when no Edge egress-policy decision was made (every
	//  LLM/ingress row, and an Edge whose egress rules were never configured).
	EgressEnforcementMode *string `json:"egressEnforcementMode,omitempty"`
	// allow | deny -- what the Edge egress access policy decided, which is NOT
	//  always what was acted on. Under egress_enforcement_mode = "observe" a
	//  deny here rides a row whose outcome is allowed: the policy would have
	//  refused the CONNECT, and observe let it through anyway. Reading outcome
	//  alone cannot tell that row apart from one no rule objected to. Empty
	//  alongside egress_enforcement_mode.
	EgressPolicyVerdict *string `json:"egressPolicyVerdict,omitempty"`
	// Deterministic over tenant+flow+event_time.
	EventID          *string             `json:"eventId,omitempty"`
	EventTime        *time.Time          `json:"eventTime,omitempty"`
	FederatedSession *TBFederatedSession `json:"federatedSession,omitempty"`
	// The flowId field.
	FlowID *string `json:"flowId,omitempty"`
	// enforce | ...; empty alongside ingress_scope.
	IngressEnforcementMode *string `json:"ingressEnforcementMode,omitempty"`
	// The direct-listener scope this call authenticated through, e.g.
	//  "squire-idjag-llm"; empty on capture/legacy ingress with no listener
	//  scope.
	IngressScope *string `json:"ingressScope,omitempty"`
	// LLM token counts; zero on egress rows and on a listener-flow row that
	//  never reached a provider (see attempt_ordinal).
	InputTokens *string `json:"inputTokens,omitempty"`
	// The logicalModel field.
	LogicalModel *string `json:"logicalModel,omitempty"`
	// The provider-native served model, e.g. "claude-opus-5" -- what cost is
	//  priced against. logical_model is only the caller-facing alias.
	ModelName *string `json:"modelName,omitempty"`
	// LLM-shaped fields; empty when capability is EGRESS.
	ModelRoute *string `json:"modelRoute,omitempty"`
	// The modelTarget field.
	ModelTarget *string `json:"modelTarget,omitempty"`
	// observed | over_limit | malformed. Anything but "observed" means the
	//  audit body wasn't fully parsed, so the token counts above are a floor,
	//  not a total.
	ObservationStatus *string `json:"observationStatus,omitempty"`
	// The outcome field.
	Outcome *TBTrafficEventOutcome `json:"outcome,omitempty"`
	// The outputTokens field.
	OutputTokens *string `json:"outputTokens,omitempty"`
	// The C1 user id source_principal resolves to, when it's an OIDC
	//  principal whose subject is a real C1 user; empty for a service/agent
	//  principal or one c1 couldn't resolve to a user.
	PrincipalUserID *string `json:"principalUserId,omitempty"`
	// The requestAuthority field.
	RequestAuthority *string `json:"requestAuthority,omitempty"`
	// Joins the listener-flow row and its provider-attempt child row -- one
	//  LLM request writes both; empty on non-LLM rows.
	RoutingRunID *string `json:"routingRunId,omitempty"`
	// A | B | C | D | "" (unresolved).
	SourceConfidence *string `json:"sourceConfidence,omitempty"`
	// Caller identity. source_principal_kind and source_confidence qualify
	//  how source_principal was resolved (see AuditSource in the TB sink).
	SourcePrincipal *string `json:"sourcePrincipal,omitempty"`
	// The sourcePrincipalKind field.
	SourcePrincipalKind *string `json:"sourcePrincipalKind,omitempty"`
	// True when this row's verdict is the fail-closed default rather than an
	//  explicit rule match, so an empty verdict_reasons isn't a missing-data
	//  gap.
	VerdictFromFallback *bool `json:"verdictFromFallback,omitempty"`
	// Why `outcome` resolved as it did. Can be legitimately empty even on a
	//  DENY -- see verdict_from_fallback.
	VerdictReasons []string `json:"verdictReasons,omitempty"`
	// The verdictResolvedRaw field.
	VerdictResolvedRaw *string `json:"verdictResolvedRaw,omitempty"`
}

func (t TBTrafficEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TBTrafficEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TBTrafficEvent) GetAttemptOrdinal() *string {
	if t == nil {
		return nil
	}
	return t.AttemptOrdinal
}

func (t *TBTrafficEvent) GetCacheReadTokens() *string {
	if t == nil {
		return nil
	}
	return t.CacheReadTokens
}

func (t *TBTrafficEvent) GetCacheWriteTokens() *string {
	if t == nil {
		return nil
	}
	return t.CacheWriteTokens
}

func (t *TBTrafficEvent) GetCallRole() *string {
	if t == nil {
		return nil
	}
	return t.CallRole
}

func (t *TBTrafficEvent) GetCapability() *Capability {
	if t == nil {
		return nil
	}
	return t.Capability
}

func (t *TBTrafficEvent) GetConfigGeneration() *string {
	if t == nil {
		return nil
	}
	return t.ConfigGeneration
}

func (t *TBTrafficEvent) GetCostLookup() *CostLookup {
	if t == nil {
		return nil
	}
	return t.CostLookup
}

func (t *TBTrafficEvent) GetCostNanoUsd() *int64 {
	if t == nil {
		return nil
	}
	return t.CostNanoUsd
}

func (t *TBTrafficEvent) GetCounterLatencyMs() *string {
	if t == nil {
		return nil
	}
	return t.CounterLatencyMs
}

func (t *TBTrafficEvent) GetCounterRequestBytes() *string {
	if t == nil {
		return nil
	}
	return t.CounterRequestBytes
}

func (t *TBTrafficEvent) GetCounterResponseBytes() *string {
	if t == nil {
		return nil
	}
	return t.CounterResponseBytes
}

func (t *TBTrafficEvent) GetDestHost() *string {
	if t == nil {
		return nil
	}
	return t.DestHost
}

func (t *TBTrafficEvent) GetDestPort() *int64 {
	if t == nil {
		return nil
	}
	return t.DestPort
}

func (t *TBTrafficEvent) GetEgressEnforcementMode() *string {
	if t == nil {
		return nil
	}
	return t.EgressEnforcementMode
}

func (t *TBTrafficEvent) GetEgressPolicyVerdict() *string {
	if t == nil {
		return nil
	}
	return t.EgressPolicyVerdict
}

func (t *TBTrafficEvent) GetEventID() *string {
	if t == nil {
		return nil
	}
	return t.EventID
}

func (t *TBTrafficEvent) GetEventTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.EventTime
}

func (t *TBTrafficEvent) GetFederatedSession() *TBFederatedSession {
	if t == nil {
		return nil
	}
	return t.FederatedSession
}

func (t *TBTrafficEvent) GetFlowID() *string {
	if t == nil {
		return nil
	}
	return t.FlowID
}

func (t *TBTrafficEvent) GetIngressEnforcementMode() *string {
	if t == nil {
		return nil
	}
	return t.IngressEnforcementMode
}

func (t *TBTrafficEvent) GetIngressScope() *string {
	if t == nil {
		return nil
	}
	return t.IngressScope
}

func (t *TBTrafficEvent) GetInputTokens() *string {
	if t == nil {
		return nil
	}
	return t.InputTokens
}

func (t *TBTrafficEvent) GetLogicalModel() *string {
	if t == nil {
		return nil
	}
	return t.LogicalModel
}

func (t *TBTrafficEvent) GetModelName() *string {
	if t == nil {
		return nil
	}
	return t.ModelName
}

func (t *TBTrafficEvent) GetModelRoute() *string {
	if t == nil {
		return nil
	}
	return t.ModelRoute
}

func (t *TBTrafficEvent) GetModelTarget() *string {
	if t == nil {
		return nil
	}
	return t.ModelTarget
}

func (t *TBTrafficEvent) GetObservationStatus() *string {
	if t == nil {
		return nil
	}
	return t.ObservationStatus
}

func (t *TBTrafficEvent) GetOutcome() *TBTrafficEventOutcome {
	if t == nil {
		return nil
	}
	return t.Outcome
}

func (t *TBTrafficEvent) GetOutputTokens() *string {
	if t == nil {
		return nil
	}
	return t.OutputTokens
}

func (t *TBTrafficEvent) GetPrincipalUserID() *string {
	if t == nil {
		return nil
	}
	return t.PrincipalUserID
}

func (t *TBTrafficEvent) GetRequestAuthority() *string {
	if t == nil {
		return nil
	}
	return t.RequestAuthority
}

func (t *TBTrafficEvent) GetRoutingRunID() *string {
	if t == nil {
		return nil
	}
	return t.RoutingRunID
}

func (t *TBTrafficEvent) GetSourceConfidence() *string {
	if t == nil {
		return nil
	}
	return t.SourceConfidence
}

func (t *TBTrafficEvent) GetSourcePrincipal() *string {
	if t == nil {
		return nil
	}
	return t.SourcePrincipal
}

func (t *TBTrafficEvent) GetSourcePrincipalKind() *string {
	if t == nil {
		return nil
	}
	return t.SourcePrincipalKind
}

func (t *TBTrafficEvent) GetVerdictFromFallback() *bool {
	if t == nil {
		return nil
	}
	return t.VerdictFromFallback
}

func (t *TBTrafficEvent) GetVerdictReasons() []string {
	if t == nil {
		return nil
	}
	return t.VerdictReasons
}

func (t *TBTrafficEvent) GetVerdictResolvedRaw() *string {
	if t == nil {
		return nil
	}
	return t.VerdictResolvedRaw
}
