// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpdateOnboardingSettingsRequestStatus - The status field.
type UpdateOnboardingSettingsRequestStatus string

const (
	UpdateOnboardingSettingsRequestStatusOnboardingStatusUnspecified UpdateOnboardingSettingsRequestStatus = "ONBOARDING_STATUS_UNSPECIFIED"
	UpdateOnboardingSettingsRequestStatusOnboardingStatusNotStarted  UpdateOnboardingSettingsRequestStatus = "ONBOARDING_STATUS_NOT_STARTED"
	UpdateOnboardingSettingsRequestStatusOnboardingStatusInProgress  UpdateOnboardingSettingsRequestStatus = "ONBOARDING_STATUS_IN_PROGRESS"
	UpdateOnboardingSettingsRequestStatusOnboardingStatusComplete    UpdateOnboardingSettingsRequestStatus = "ONBOARDING_STATUS_COMPLETE"
	UpdateOnboardingSettingsRequestStatusOnboardingStatusDismissed   UpdateOnboardingSettingsRequestStatus = "ONBOARDING_STATUS_DISMISSED"
)

func (e UpdateOnboardingSettingsRequestStatus) ToPointer() *UpdateOnboardingSettingsRequestStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdateOnboardingSettingsRequestStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "ONBOARDING_STATUS_UNSPECIFIED", "ONBOARDING_STATUS_NOT_STARTED", "ONBOARDING_STATUS_IN_PROGRESS", "ONBOARDING_STATUS_COMPLETE", "ONBOARDING_STATUS_DISMISSED":
			return true
		}
	}
	return false
}

// The UpdateOnboardingSettingsRequest message.
type UpdateOnboardingSettingsRequest struct {
	// The conversationId field.
	ConversationID *string `json:"conversationId,omitempty"`
	// The status field.
	Status *UpdateOnboardingSettingsRequestStatus `json:"status,omitempty"`
}

func (u *UpdateOnboardingSettingsRequest) GetConversationID() *string {
	if u == nil {
		return nil
	}
	return u.ConversationID
}

func (u *UpdateOnboardingSettingsRequest) GetStatus() *UpdateOnboardingSettingsRequestStatus {
	if u == nil {
		return nil
	}
	return u.Status
}
