// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/conductorone-sdk-go/pkg/utils"
)

// UserAttributeManagementServiceUpdateResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type UserAttributeManagementServiceUpdateResponseExpanded struct {
	// The type of the serialized message.
	AtType               *string        `json:"@type,omitempty"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (u UserAttributeManagementServiceUpdateResponseExpanded) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserAttributeManagementServiceUpdateResponseExpanded) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserAttributeManagementServiceUpdateResponseExpanded) GetAtType() *string {
	if u == nil {
		return nil
	}
	return u.AtType
}

func (u *UserAttributeManagementServiceUpdateResponseExpanded) GetAdditionalProperties() map[string]any {
	if u == nil {
		return nil
	}
	return u.AdditionalProperties
}

// The UserAttributeManagementServiceUpdateResponse message.
type UserAttributeManagementServiceUpdateResponse struct {
	Attribute *UserAttributeMappingView `json:"attribute,omitempty"`
	// The expanded field.
	Expanded []UserAttributeManagementServiceUpdateResponseExpanded `json:"expanded,omitempty"`
}

func (u *UserAttributeManagementServiceUpdateResponse) GetAttribute() *UserAttributeMappingView {
	if u == nil {
		return nil
	}
	return u.Attribute
}

func (u *UserAttributeManagementServiceUpdateResponse) GetExpanded() []UserAttributeManagementServiceUpdateResponseExpanded {
	if u == nil {
		return nil
	}
	return u.Expanded
}
