// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// VirtualMCPAssignedTools marks a Virtual MCP Server composed from selected
//
//	Toolsets and individual tools. Binding management is introduced separately.
type VirtualMCPAssignedTools struct {
}
