// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The Workflow message.
type Workflow struct {
	// The WorkflowContext message.
	WorkflowContext *WorkflowContext `json:"context,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// The triggers field.
	Triggers []WorkflowTrigger `json:"triggers,omitempty"`
	// The workflowSteps field.
	WorkflowSteps []WorkflowStep `json:"workflowSteps,omitempty"`
}

func (o *Workflow) GetWorkflowContext() *WorkflowContext {
	if o == nil {
		return nil
	}
	return o.WorkflowContext
}

func (o *Workflow) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Workflow) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *Workflow) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *Workflow) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Workflow) GetTriggers() []WorkflowTrigger {
	if o == nil {
		return nil
	}
	return o.Triggers
}

func (o *Workflow) GetWorkflowSteps() []WorkflowStep {
	if o == nil {
		return nil
	}
	return o.WorkflowSteps
}
