// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// WorkflowInput - The Workflow message.
type WorkflowInput struct {
	// The WorkflowContext message.
	WorkflowContext *WorkflowContext `json:"context,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The triggers field.
	Triggers []WorkflowTrigger `json:"triggers,omitempty"`
	// The workflowSteps field.
	WorkflowSteps []WorkflowStep `json:"workflowSteps,omitempty"`
}

func (o *WorkflowInput) GetWorkflowContext() *WorkflowContext {
	if o == nil {
		return nil
	}
	return o.WorkflowContext
}

func (o *WorkflowInput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *WorkflowInput) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *WorkflowInput) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *WorkflowInput) GetTriggers() []WorkflowTrigger {
	if o == nil {
		return nil
	}
	return o.Triggers
}

func (o *WorkflowInput) GetWorkflowSteps() []WorkflowStep {
	if o == nil {
		return nil
	}
	return o.WorkflowSteps
}
