name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build the test cli
        run: go build -o cli ./.ci

  test:
    name: 'Acc. Tests (OS: ${{ matrix.os }})'
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-go@4
        with:
          go-version-file: 'go.mod'

      - name: Run acceptance test
        run: make testacc
